# Generated by Django 6.1 on 2026-08-10 14:52

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models

import api_auth.models.manager
import api_utils.db


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api_core", "0002_immutable_unaccent"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                ("email", models.EmailField(db_default="", default="", max_length=254)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=False, default=False)),
                ("is_staff", models.BooleanField(db_default=False, default=False)),
                ("is_superuser", models.BooleanField(db_default=False, default=False)),
            ],
            options={
                "ordering": ("username",),
                "abstract": False,
            },
            managers=[
                ("objects", api_auth.models.manager.ApiUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ApiUserGroups",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserGroupsEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserPermissions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserPermissionsEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(db_default="", default="", max_length=100),
                ),
                ("email", models.EmailField(db_default="", default="", max_length=254)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=128)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=False, default=False)),
                ("is_staff", models.BooleanField(db_default=False, default=False)),
                ("is_superuser", models.BooleanField(db_default=False, default=False)),
            ],
            options={
                "abstract": False,
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        condition=models.Q(("pgh_context__isnull", False)),
                        fields=["pgh_context"],
                        name="gin_apiuserevent_ctx_path",
                        opclasses=["jsonb_path_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            expression=django.db.models.fields.json.KeyTextTransform(
                                "url", "pgh_context"
                            ),
                            name="gin_trgm_ops",
                        ),
                        condition=models.Q(("pgh_context__isnull", False)),
                        name="gin_apiuserevent_ctx_url",
                    ),
                    models.Index(
                        django.db.models.fields.json.KeyTransform(
                            "id",
                            django.db.models.fields.json.KeyTransform(
                                "user", "pgh_context"
                            ),
                        ),
                        condition=models.Q(
                            ("pgh_context__has_key", "user"),
                            ("pgh_context__isnull", False),
                        ),
                        name="idx_apiuserevent_ctx_userid",
                    ),
                    models.Index(
                        fields=["pgh_created_at"], name="idx_apiuserevent_pghcreatedat"
                    ),
                    models.Index(
                        fields=["pgh_label"], name="idx_apiuserevent_pghlabel"
                    ),
                    models.Index(fields=["id"], name="idx_apiuserevent_id"),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="ca51136be1814a0b0d189ecc405d3e06baba7b11",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_ef24d",
                    table="api_auth_apiuserevent",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddField(
            model_name="apiusergroups",
            name="api_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiusergroups",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="+",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="groups",
            field=models.ManyToManyField(
                related_name="users", through="api_auth.ApiUserGroups", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="apiusergroupsevent",
            name="api_user",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiusergroupsevent",
            name="group",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="apiuserpermissions",
            name="api_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiuserpermissions",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="auth.permission",
            ),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="permissions",
            field=models.ManyToManyField(
                related_name="users",
                through="api_auth.ApiUserPermissions",
                to="auth.permission",
            ),
        ),
        migrations.AddField(
            model_name="apiuserpermissionsevent",
            name="api_user",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiuserpermissionsevent",
            name="permission",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="auth.permission",
            ),
        ),
        migrations.AddConstraint(
            model_name="apiusergroups",
            constraint=models.UniqueConstraint(
                fields=("api_user", "group"), name="unq_apiusergroups_apiuser_group"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroups",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="140c6693d5d4285edebb3883b4099a812d387696",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_d6a18",
                    table="api_auth_apiusergroups",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroups",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="10ed55d110c6658e1be41f080bf4d04c1f1dc7d2",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_6638a",
                    table="api_auth_apiusergroups",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroups",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "api_auth_apiusergroupsevent" ("api_user_id", "group_id", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."api_user_id", OLD."group_id", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="8072cd8518c81120fe0955c05b9ff594ff1cfb54",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_e8d83",
                    table="api_auth_apiusergroups",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroups",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "api_auth_apiusergroupsevent" ("api_user_id", "group_id", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."group_id", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="e32fc94cf45a1c8da6b04fcdbb944d399e443b26",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_d31f5",
                    table="api_auth_apiusergroups",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroups",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "api_auth_apiusergroupsevent" ("api_user_id", "group_id", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."group_id", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="e5caea1eb8c5188e721adab0546e87ad4064e290",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_4ec4c",
                    table="api_auth_apiusergroups",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_apiusergroupsevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_apiusergroupsevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_apiusergroupsevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_apiusergroupsevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_apiusergroupsevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusergroupsevent",
            index=models.Index(fields=["id"], name="idx_apiusergroupsevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusergroupsevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="b46e048adf0dda827e94975525dcd7852a479e92",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_1578c",
                    table="api_auth_apiusergroupsevent",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="apiuserpermissions",
            constraint=models.UniqueConstraint(
                fields=("api_user", "permission"),
                name="unq_apiuserpermissions_apiuser_permission",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissions",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="d9d92e44b29811cc19f07464f3139dce00a62a1b",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_b4fc1",
                    table="api_auth_apiuserpermissions",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissions",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="be3ba8ecf4ad07066d507d48b559a28cb224b557",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_754cd",
                    table="api_auth_apiuserpermissions",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissions",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "api_auth_apiuserpermissionsevent" ("api_user_id", "id", "permission_id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."api_user_id", OLD."id", OLD."permission_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="cf5766cb85b7de351fb46fb13620be8847fe7d6b",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_e4610",
                    table="api_auth_apiuserpermissions",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissions",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "api_auth_apiuserpermissionsevent" ("api_user_id", "id", "permission_id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."id", NEW."permission_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="c67b80018a4e4f97f895fcfcdf4767c78849e95b",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_1cee7",
                    table="api_auth_apiuserpermissions",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissions",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "api_auth_apiuserpermissionsevent" ("api_user_id", "id", "permission_id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."id", NEW."permission_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="1b6ab836f15d3e66be49829ce78562008c45b372",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_cf3c0",
                    table="api_auth_apiuserpermissions",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.functions.text.Upper(
                        api_utils.db.ImmutableUnaccent("username")
                    ),
                    name="gin_trgm_ops",
                ),
                name="gin_apiuser_username",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.functions.text.Upper(
                        api_utils.db.ImmutableUnaccent("email")
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("email__len__gt", 0)),
                name="gin_apiuser_email",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=models.Index(fields=["created_at"], name="idx_apiuser_createdat"),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=models.Index(fields=["is_active"], name="idx_apiuser_isactive"),
        ),
        migrations.AddConstraint(
            model_name="apiuser",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email__len__gt", 0)),
                name="unq_apiuser_email",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="7e66dbe1054afbaa5c19cb41a80c9d7ec094c36f",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_b9962",
                    table="api_auth_apiuser",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="16820df82dc22190e457f4536543dc33f6d295c3",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_aaa91",
                    table="api_auth_apiuser",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiuser_readonly_createdat",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="dd8daa0964600df49f93c8e325ae3e8d7b5deca6",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiuser_readonly_createdat_59ec0",
                    table="api_auth_apiuser",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiuser_protect_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot insert rows from % table', TG_TABLE_NAME;",
                    hash="85751d3f9d068c528fdf554ce96fd72fcb297b51",
                    operation="INSERT",
                    pgid="pgtrigger_trg_apiuser_protect_insert_f823f",
                    table="api_auth_apiuser",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "api_auth_apiuserevent" ("created_at", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "password", "pgh_context", "pgh_created_at", "pgh_label", "username") VALUES (OLD."created_at", OLD."email", OLD."first_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_name", OLD."password", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."username"); RETURN NULL;',
                    hash="7e48c022ed7aa115f9e0fd65af63805c5ad58cfe",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_48419",
                    table="api_auth_apiuser",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "api_auth_apiuserevent" ("created_at", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "password", "pgh_context", "pgh_created_at", "pgh_label", "username") VALUES (NEW."created_at", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", NEW."password", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."username"); RETURN NULL;',
                    hash="d7bc681a34ad21ef04622aefd87862be3d1d99ad",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_28abd",
                    table="api_auth_apiuser",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "api_auth_apiuserevent" ("created_at", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "password", "pgh_context", "pgh_created_at", "pgh_label", "username") VALUES (NEW."created_at", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", NEW."password", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."username"); RETURN NULL;',
                    hash="d436be2992e72f7033885edf1b6325c1891ed01c",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_725e6",
                    table="api_auth_apiuser",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_apiuserpermissionsevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_apiuserpermissionsevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_apiuserpermissionsevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=models.Index(
                fields=["pgh_created_at"],
                name="idx_apiuserpermissionsevent_pghcreatedat",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_apiuserpermissionsevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserpermissionsevent",
            index=models.Index(fields=["id"], name="idx_apiuserpermissionsevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserpermissionsevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="aaa465412f7700000299e2c00d9dce548f10396e",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_86084",
                    table="api_auth_apiuserpermissionsevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
