# Generated by Django 6.1 on 2026-09-06 01:45

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apiauth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiUserTotpDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("secret", models.CharField(max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
                (
                    "locked_until",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
                ("failures", models.PositiveSmallIntegerField(db_default=0, default=0)),
                ("last_step", models.PositiveBigIntegerField(db_default=0, default=0)),
                (
                    "api_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DB_CASCADE,
                        related_name="totp_device",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserRecoveryCodeEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
                (
                    "device",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiauth.apiusertotpdevice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserRecoveryCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DB_CASCADE,
                        related_name="recovery_codes",
                        to="apiauth.apiusertotpdevice",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiUserTotpDeviceEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
                (
                    "locked_until",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
                ("failures", models.PositiveSmallIntegerField(db_default=0, default=0)),
                ("last_step", models.PositiveBigIntegerField(db_default=0, default=0)),
                (
                    "api_user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="apiusertotpdevice",
            index=models.Index(
                fields=["confirmed_at"], name="idx_apiusertotpdevice_confirmedat"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusertotpdevice",
            index=models.Index(
                fields=["locked_until"], name="idx_apiusertotpdevice_lockeduntil"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="992c84780255bb1335d646923595ed3a64c4b88f",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_e6814",
                    table="apiauth_apiusertotpdevice",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="ceb96653aba759cad52c5876053924bed26c2fc8",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_15d81",
                    table="apiauth_apiusertotpdevice",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiusertotpdevice_readonly",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."api_user_id" IS DISTINCT FROM (NEW."api_user_id") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="40dadc64a610ffd9a1ca091be6a314a75d0b1c62",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiusertotpdevice_readonly_7d6d2",
                    table="apiauth_apiusertotpdevice",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiusertotpdevice_protect_secret",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."confirmed_at" IS NOT NULL AND NEW."secret" IS DISTINCT FROM (OLD."secret"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="637c1c4957dc284340cc329c5bb6c30ae62552e7",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiusertotpdevice_protect_secret_dabaa",
                    table="apiauth_apiusertotpdevice",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiusertotpdevice_protect_confirmedat",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."confirmed_at" IS NOT NULL AND NEW."confirmed_at" IS NULL)',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="285936dc24f1624c78cb64c9ca0c575346a5adc5",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiusertotpdevice_protect_confirmedat_b78da",
                    table="apiauth_apiusertotpdevice",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiusertotpdeviceevent" ("api_user_id", "confirmed_at", "created_at", "failures", "id", "last_step", "locked_until", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."api_user_id", OLD."confirmed_at", OLD."created_at", OLD."failures", OLD."id", OLD."last_step", OLD."locked_until", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="98a5f726f4b1c064fbe2eb203af74896a4e9c50c",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_b057a",
                    table="apiauth_apiusertotpdevice",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiusertotpdeviceevent" ("api_user_id", "confirmed_at", "created_at", "failures", "id", "last_step", "locked_until", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."confirmed_at", NEW."created_at", NEW."failures", NEW."id", NEW."last_step", NEW."locked_until", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="94aab84c828f8b9efdde8d314fedb8bf00bc657b",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_e5ab9",
                    table="apiauth_apiusertotpdevice",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdevice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."api_user_id" IS DISTINCT FROM (NEW."api_user_id") OR OLD."confirmed_at" IS DISTINCT FROM (NEW."confirmed_at") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."failures" IS DISTINCT FROM (NEW."failures") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."last_step" IS DISTINCT FROM (NEW."last_step") OR OLD."locked_until" IS DISTINCT FROM (NEW."locked_until"))',
                    func='INSERT INTO "apiauth_apiusertotpdeviceevent" ("api_user_id", "confirmed_at", "created_at", "failures", "id", "last_step", "locked_until", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."api_user_id", NEW."confirmed_at", NEW."created_at", NEW."failures", NEW."id", NEW."last_step", NEW."locked_until", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="cd3a60be5aa7c29f555e66479aa7ab7ef4db4f0c",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_670d2",
                    table="apiauth_apiusertotpdevice",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserrecoverycodeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_apiuserrecoverycodeevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserrecoverycodeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_apiuserrecoverycodeevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserrecoverycodeevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_apiuserrecoverycodeevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserrecoverycodeevent",
            index=models.Index(
                fields=["pgh_created_at"],
                name="idx_apiuserrecoverycodeevent_pghcreatedat",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserrecoverycodeevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_apiuserrecoverycodeevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserrecoverycodeevent",
            index=models.Index(fields=["id"], name="idx_apiuserrecoverycodeevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycodeevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="99891496740eee8790ee2c3ca03c89aeb38791dd",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_d727e",
                    table="apiauth_apiuserrecoverycodeevent",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiuserrecoverycode",
            index=models.Index(
                fields=["used_at"], name="idx_apiuserrecoverycode_usedat"
            ),
        ),
        migrations.AddConstraint(
            model_name="apiuserrecoverycode",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unq_apiuserrecoverycode_code"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="966a88fdb6ca44070401f6a365c22983157ec65a",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_6d55b",
                    table="apiauth_apiuserrecoverycode",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="580e4c7294d667f39fd6029fba0bea07ea62094f",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_e50a9",
                    table="apiauth_apiuserrecoverycode",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiuserrecoverycode_readonly",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."code" IS DISTINCT FROM (NEW."code") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."device_id" IS DISTINCT FROM (NEW."device_id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="b80cd6498ff476e9cc236963dd30a9efdbba97d9",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiuserrecoverycode_readonly_54540",
                    table="apiauth_apiuserrecoverycode",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiuserrecoverycode_protect_used",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."used_at" IS NOT NULL)',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="d613750808a64babd5d695331532dfcde11209f8",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiuserrecoverycode_protect_used_f1cd7",
                    table="apiauth_apiuserrecoverycode",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiuserrecoverycodeevent" ("created_at", "device_id", "id", "pgh_context", "pgh_created_at", "pgh_label", "used_at") VALUES (OLD."created_at", OLD."device_id", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."used_at"); RETURN NULL;',
                    hash="07db1ceae415a7596251e4ccbfe48551be062a72",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_c609b",
                    table="apiauth_apiuserrecoverycode",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiuserrecoverycodeevent" ("created_at", "device_id", "id", "pgh_context", "pgh_created_at", "pgh_label", "used_at") VALUES (NEW."created_at", NEW."device_id", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."used_at"); RETURN NULL;',
                    hash="768d884fd9f7edac4d811a2d9a21249abe27999a",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_82c50",
                    table="apiauth_apiuserrecoverycode",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuserrecoverycode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."device_id" IS DISTINCT FROM (NEW."device_id") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."used_at" IS DISTINCT FROM (NEW."used_at"))',
                    func='INSERT INTO "apiauth_apiuserrecoverycodeevent" ("created_at", "device_id", "id", "pgh_context", "pgh_created_at", "pgh_label", "used_at") VALUES (NEW."created_at", NEW."device_id", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."used_at"); RETURN NULL;',
                    hash="f7090b36202b6c50fc34002c1eeaf44b89a18ea6",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_481c5",
                    table="apiauth_apiuserrecoverycode",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiusertotpdeviceevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_apiusertotpdeviceevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="apiusertotpdeviceevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_apiusertotpdeviceevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="apiusertotpdeviceevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_apiusertotpdeviceevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="apiusertotpdeviceevent",
            index=models.Index(
                fields=["pgh_created_at"],
                name="idx_apiusertotpdeviceevent_pghcreatedat",
            ),
        ),
        migrations.AddIndex(
            model_name="apiusertotpdeviceevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_apiusertotpdeviceevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusertotpdeviceevent",
            index=models.Index(fields=["id"], name="idx_apiusertotpdeviceevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiusertotpdeviceevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="c79b5372ed73608170502d3372a5c4b7b828d344",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_4fa30",
                    table="apiauth_apiusertotpdeviceevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
