# Generated by Django 6.1 on 2026-10-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apiauth", "0002_two_factor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiusertotpdevice",
            name="secret",
            field=models.CharField(max_length=255),
        ),
    ]
