# Generated by Django 6.1 on 2026-10-05 22:26

import re
import uuid

from typing import TYPE_CHECKING

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.db.models.functions.uuid
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models

import api_utils.db

if TYPE_CHECKING:
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.state import StateApps

# TLD reservado (RFC 2606): nunca recibe correo
PLACEHOLDER_DOMAIN = "sin-correo.example"


def backfill_existing_users(
    apps: StateApps,  # ruff: ignore[unused-function-argument]
    schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    # Deja a los usuarios existentes listos para el login por correo:
    # - correos en minúsculas;
    # - quien no tenía correo (un superusuario creado solo con usuario y contraseña)
    #   recibe `<usuario>@sin-correo.example`, que hay que cambiar por uno real;
    # - las cuentas inactivas pasan a `suspended` y todas se dan por verificadas,
    #   que es como funcionaban hasta ahora.
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE apiauth_apiuser SET email = lower(btrim(email)) WHERE email <> ''"
        )

        cursor.execute(
            "SELECT id, username FROM apiauth_apiuser WHERE email = '' "
            "ORDER BY created_at, id"
        )
        blank = cursor.fetchall()

        cursor.execute("SELECT email FROM apiauth_apiuser WHERE email <> ''")
        taken = {row[0] for row in cursor.fetchall()}

        for pk, username in blank:
            slug = re.sub(r"[^a-z0-9._-]+", "-", (username or "").lower()).strip("-")
            base = slug or "usuario"

            candidate, suffix = f"{base}@{PLACEHOLDER_DOMAIN}", 1
            while candidate in taken:
                suffix += 1
                candidate = f"{base}-{suffix}@{PLACEHOLDER_DOMAIN}"

            taken.add(candidate)
            cursor.execute(
                "UPDATE apiauth_apiuser SET email = %s WHERE id = %s",
                [candidate, pk],
            )

        cursor.execute(
            "UPDATE apiauth_apiuser SET status = 'suspended' WHERE NOT is_active"
        )
        cursor.execute(
            "UPDATE apiauth_apiuser SET verified_at = created_at "
            "WHERE verified_at IS NULL"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("apiauth", "0003_totp_secret_encrypted"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiLoginAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identifier", models.CharField(max_length=254)),
                ("key", models.CharField(max_length=254)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_default=None, default=None, null=True
                    ),
                ),
                ("succeeded", models.BooleanField()),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiLoginLock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=254)),
                ("locked_until", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiVerificationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("invitation", "Invitation"),
                            ("password_reset", "Password Reset"),
                        ],
                        max_length=24,
                    ),
                ),
                ("destination", models.EmailField(max_length=254)),
                ("code_hash", models.CharField(max_length=64)),
                ("attempts", models.PositiveSmallIntegerField(db_default=0, default=0)),
                ("expires_at", models.DateTimeField()),
                (
                    "consumed_at",
                    models.DateTimeField(db_default=None, default=None, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="apiuser",
            options={"ordering": ("email",)},
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="apiuser",
            name="trg_log_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="apiuser",
            name="trg_log_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="apiuser",
            name="trg_log_update",
        ),
        migrations.RemoveConstraint(
            model_name="apiuser",
            name="unq_apiuser_email",
        ),
        migrations.RemoveIndex(
            model_name="apiuser",
            name="gin_apiuser_email",
        ),
        migrations.AddField(
            model_name="apiuser",
            name="birth_date",
            field=models.DateField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="closing_effective_at",
            field=models.DateTimeField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="nationality",
            field=models.CharField(db_default="", default="", max_length=2),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="sessions_revoked_at",
            field=models.DateTimeField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("expelled", "Expelled"),
                    ("closing", "Closing"),
                ],
                db_default="active",
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="verified_at",
            field=models.DateTimeField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="apiuserevent",
            name="birth_date",
            field=models.DateField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="apiuserevent",
            name="closing_effective_at",
            field=models.DateTimeField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="apiuserevent",
            name="nationality",
            field=models.CharField(db_default="", default="", max_length=2),
        ),
        migrations.AddField(
            model_name="apiuserevent",
            name="sessions_revoked_at",
            field=models.DateTimeField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="apiuserevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("expelled", "Expelled"),
                    ("closing", "Closing"),
                ],
                db_default="active",
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="apiuserevent",
            name="verified_at",
            field=models.DateTimeField(db_default=None, default=None, null=True),
        ),
        # - las cuentas que ya existen tienen que cumplir las restricciones nuevas antes
        #   de que se creen (correo obligatorio, único y en minúsculas; estado alineado
        #   con `is_active`)
        migrations.RunPython(backfill_existing_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="apiuser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="apiuser",
            name="username",
            field=models.CharField(
                blank=True,
                db_default=None,
                default=None,
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="apiuserevent",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="apiuserevent",
            name="username",
            field=models.CharField(
                blank=True, db_default=None, default=None, max_length=100, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.functions.text.Upper(
                        api_utils.db.ImmutableUnaccent("email")
                    ),
                    name="gin_trgm_ops",
                ),
                name="gin_apiuser_email",
            ),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=models.Index(fields=["status"], name="idx_apiuser_status"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiuserevent" ("birth_date", "closing_effective_at", "created_at", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "nationality", "password", "pgh_context", "pgh_created_at", "pgh_label", "sessions_revoked_at", "status", "username", "verified_at") VALUES (OLD."birth_date", OLD."closing_effective_at", OLD."created_at", OLD."email", OLD."first_name", OLD."id", OLD."is_active", OLD."is_staff", OLD."is_superuser", OLD."last_name", OLD."nationality", OLD."password", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."sessions_revoked_at", OLD."status", OLD."username", OLD."verified_at"); RETURN NULL;',
                    hash="3c8b8cc7c2d45d73b8b7fd16cd131dff291cfb4d",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_70bb8",
                    table="apiauth_apiuser",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiuserevent" ("birth_date", "closing_effective_at", "created_at", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "nationality", "password", "pgh_context", "pgh_created_at", "pgh_label", "sessions_revoked_at", "status", "username", "verified_at") VALUES (NEW."birth_date", NEW."closing_effective_at", NEW."created_at", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", NEW."nationality", NEW."password", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."sessions_revoked_at", NEW."status", NEW."username", NEW."verified_at"); RETURN NULL;',
                    hash="ce27a6530d5bf4d600f4ae5d5b6284e5edb0c79a",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_bf524",
                    table="apiauth_apiuser",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiuser",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "apiauth_apiuserevent" ("birth_date", "closing_effective_at", "created_at", "email", "first_name", "id", "is_active", "is_staff", "is_superuser", "last_name", "nationality", "password", "pgh_context", "pgh_created_at", "pgh_label", "sessions_revoked_at", "status", "username", "verified_at") VALUES (NEW."birth_date", NEW."closing_effective_at", NEW."created_at", NEW."email", NEW."first_name", NEW."id", NEW."is_active", NEW."is_staff", NEW."is_superuser", NEW."last_name", NEW."nationality", NEW."password", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."sessions_revoked_at", NEW."status", NEW."username", NEW."verified_at"); RETURN NULL;',
                    hash="a60807a7637f25778e4ab46c8a0c049a24767708",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_819c8",
                    table="apiauth_apiuser",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="apiuser",
            constraint=models.UniqueConstraint(
                fields=("email",), name="unq_apiuser_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="apiuser",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "email",
                    django.db.models.functions.text.Lower("email"),
                )),
                name="chk_apiuser_email_lower",
            ),
        ),
        migrations.AddConstraint(
            model_name="apiuser",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("username__isnull", True),
                    models.Q(("username", ""), _negated=True),
                    _connector="OR",
                ),
                name="chk_apiuser_username_notblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="apiuser",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "status__in",
                    ["pending", "active", "suspended", "expelled", "closing"],
                )),
                name="chk_apiuser_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="apiuser",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_active", True), ("status", "active")),
                    models.Q(
                        ("is_active", False),
                        models.Q(("status", "active"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="chk_apiuser_active_matches_status",
            ),
        ),
        migrations.AddIndex(
            model_name="apiloginattempt",
            index=models.Index(
                condition=models.Q(("succeeded", False)),
                fields=["key", "-created_at"],
                name="idx_apiloginattempt_failed",
            ),
        ),
        migrations.AddIndex(
            model_name="apiloginattempt",
            index=models.Index(
                fields=["created_at"], name="idx_apiloginattempt_createdat"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiloginattempt",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="8a12f70b48e238ffe773fa5d4923fdd69962acb8",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_daf10",
                    table="apiauth_apiloginattempt",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiloginattempt",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="a50764095644647ac2ad609586e86f89ec81ccc2",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_5796e",
                    table="apiauth_apiloginattempt",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiloginattempt",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiloginattempt_noupdate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="60bee9649b8be11f6e684df358277970f4b1ccf4",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiloginattempt_noupdate_44bea",
                    table="apiauth_apiloginattempt",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiloginlock",
            index=models.Index(
                fields=["locked_until"], name="idx_apiloginlock_lockeduntil"
            ),
        ),
        migrations.AddConstraint(
            model_name="apiloginlock",
            constraint=models.UniqueConstraint(
                fields=("key",), name="unq_apiloginlock_key"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiloginlock",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="d19f32ef7235d90b06d0b90db949fee6834e2898",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_7668a",
                    table="apiauth_apiloginlock",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiloginlock",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="f787b8cdcf42d2634cd7c315332775dbcfb245e3",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_815b2",
                    table="apiauth_apiloginlock",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddField(
            model_name="apiverificationcode",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DB_CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="apiverificationcode",
            index=models.Index(
                fields=["destination", "purpose", "-created_at"],
                name="idx_apiverificationcode_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="apiverificationcode",
            index=models.Index(
                fields=["expires_at"], name="idx_apiverificationcode_expiresat"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiverificationcode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="0d42e2b2ea37a1fdc2ceb8769aebcb79d8795612",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_0c55b",
                    table="apiauth_apiverificationcode",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiverificationcode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="c9f4d457a869e37bc712af7aa4e36eadd4058ab9",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_1974d",
                    table="apiauth_apiverificationcode",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiverificationcode",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiverificationcode_readonly",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."code_hash" IS DISTINCT FROM (NEW."code_hash") OR OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."destination" IS DISTINCT FROM (NEW."destination") OR OLD."purpose" IS DISTINCT FROM (NEW."purpose") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="91b46d30901cab96d14f11e63eeb10a41b52ab27",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiverificationcode_readonly_cf8bd",
                    table="apiauth_apiverificationcode",
                    when="BEFORE",
                ),
            ),
        ),
    ]
