# Generated by Django 6.1 on 2026-10-05 23:07

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apiauth", "0004_identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiExternalIdentityEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(choices=[("google", "Google")], max_length=24),
                ),
                ("subject", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiExternalIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(choices=[("google", "Google")], max_length=24),
                ),
                ("subject", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DB_CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "subject"),
                        name="unq_apiexternalidentity_subject",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "provider"), name="unq_apiexternalidentity_user"
                    ),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiexternalidentity",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="83ea02a5e87bd1686ea830ec230538a75debba20",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_d3df5",
                    table="apiauth_apiexternalidentity",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiexternalidentity",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="844e44477be3be76d11d9f0775dd029a8a0569ef",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_377f7",
                    table="apiauth_apiexternalidentity",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiexternalidentity",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apiexternalidentity_readonly",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."provider" IS DISTINCT FROM (NEW."provider") OR OLD."subject" IS DISTINCT FROM (NEW."subject") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="fe04414bdaf23ffcf2196de42150c30bad29fb69",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apiexternalidentity_readonly_c8e42",
                    table="apiauth_apiexternalidentity",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiexternalidentity",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiexternalidentityevent" ("created_at", "email", "id", "pgh_context", "pgh_created_at", "pgh_label", "provider", "subject", "user_id") VALUES (OLD."created_at", OLD."email", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."provider", OLD."subject", OLD."user_id"); RETURN NULL;',
                    hash="c6e85d4b6cd24d3cb00fb257ded40455aa34af32",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_fdd3d",
                    table="apiauth_apiexternalidentity",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiexternalidentity",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apiexternalidentityevent" ("created_at", "email", "id", "pgh_context", "pgh_created_at", "pgh_label", "provider", "subject", "user_id") VALUES (NEW."created_at", NEW."email", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."provider", NEW."subject", NEW."user_id"); RETURN NULL;',
                    hash="b225397292e59301657b391baab71b6b8dcf0049",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_166dc",
                    table="apiauth_apiexternalidentity",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiexternalidentity",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "apiauth_apiexternalidentityevent" ("created_at", "email", "id", "pgh_context", "pgh_created_at", "pgh_label", "provider", "subject", "user_id") VALUES (NEW."created_at", NEW."email", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."provider", NEW."subject", NEW."user_id"); RETURN NULL;',
                    hash="556076e96e9f7d20f711ee8f3ad334038793003d",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_d3c05",
                    table="apiauth_apiexternalidentity",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apiexternalidentityevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_apiexternalidentityevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="apiexternalidentityevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_apiexternalidentityevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="apiexternalidentityevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_apiexternalidentityevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="apiexternalidentityevent",
            index=models.Index(
                fields=["pgh_created_at"],
                name="idx_apiexternalidentityevent_pghcreatedat",
            ),
        ),
        migrations.AddIndex(
            model_name="apiexternalidentityevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_apiexternalidentityevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="apiexternalidentityevent",
            index=models.Index(fields=["id"], name="idx_apiexternalidentityevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apiexternalidentityevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="d6992d7b24a28469865271804b569ee42e008e79",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_4492c",
                    table="apiauth_apiexternalidentityevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
