# Generated by Django 6.1 on 2026-10-06 15:47

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apiauth", "0005_external_identity"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiGroupProfileEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("operator", "Operator"),
                            ("public", "Public"),
                            ("staff", "Staff"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("alcaldia", "Alcaldia"),
                            ("guia", "Guia"),
                            ("institucion", "Institucion"),
                            ("negocio", "Negocio"),
                            ("traductor", "Traductor"),
                            ("turista", "Turista"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_default="", default="", max_length=300
                    ),
                ),
                (
                    "requires_two_factor",
                    models.BooleanField(db_default=False, default=False),
                ),
                ("is_system", models.BooleanField(db_default=False, default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiGroupProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("operator", "Operator"),
                            ("public", "Public"),
                            ("staff", "Staff"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("alcaldia", "Alcaldia"),
                            ("guia", "Guia"),
                            ("institucion", "Institucion"),
                            ("negocio", "Negocio"),
                            ("traductor", "Traductor"),
                            ("turista", "Turista"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_default="", default="", max_length=300
                    ),
                ),
                (
                    "requires_two_factor",
                    models.BooleanField(db_default=False, default=False),
                ),
                ("is_system", models.BooleanField(db_default=False, default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DB_CASCADE,
                        related_name="profile",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q((
                            "kind__in",
                            ["operator", "public", "staff"],
                        )),
                        name="chk_apigroupprofile_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q((
                            "role__in",
                            [
                                "admin",
                                "alcaldia",
                                "guia",
                                "institucion",
                                "negocio",
                                "traductor",
                                "turista",
                            ],
                        )),
                        name="chk_apigroupprofile_role",
                    ),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apigroupprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="c87526ed03b858baeec8ea49c37938a1938d1a98",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_71c9f",
                    table="apiauth_apigroupprofile",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apigroupprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="93b0189e66edc8b48e46609e025c4a97626d6c69",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_ca3cc",
                    table="apiauth_apigroupprofile",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apigroupprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_apigroupprofile_readonly",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."created_at" IS DISTINCT FROM (NEW."created_at") OR OLD."group_id" IS DISTINCT FROM (NEW."group_id") OR OLD."kind" IS DISTINCT FROM (NEW."kind"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="d15b9cac989f89f3e72c2ce6e2d20650d934a231",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_apigroupprofile_readonly_de61e",
                    table="apiauth_apigroupprofile",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apigroupprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apigroupprofileevent" ("created_at", "description", "group_id", "id", "is_system", "kind", "pgh_context", "pgh_created_at", "pgh_label", "requires_two_factor", "role") VALUES (OLD."created_at", OLD."description", OLD."group_id", OLD."id", OLD."is_system", OLD."kind", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."requires_two_factor", OLD."role"); RETURN NULL;',
                    hash="f05c861c595883b4aba5520dfb3c74de01d69715",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_be7cf",
                    table="apiauth_apigroupprofile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apigroupprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apigroupprofileevent" ("created_at", "description", "group_id", "id", "is_system", "kind", "pgh_context", "pgh_created_at", "pgh_label", "requires_two_factor", "role") VALUES (NEW."created_at", NEW."description", NEW."group_id", NEW."id", NEW."is_system", NEW."kind", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."requires_two_factor", NEW."role"); RETURN NULL;',
                    hash="ff90723f3d334bb33cd35656e7921a95b5dd4420",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_1ead6",
                    table="apiauth_apigroupprofile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apigroupprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "apiauth_apigroupprofileevent" ("created_at", "description", "group_id", "id", "is_system", "kind", "pgh_context", "pgh_created_at", "pgh_label", "requires_two_factor", "role") VALUES (NEW."created_at", NEW."description", NEW."group_id", NEW."id", NEW."is_system", NEW."kind", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."requires_two_factor", NEW."role"); RETURN NULL;',
                    hash="431e0ac5a0fd34335be767d4b6ec05d8d21c02e9",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_2bc98",
                    table="apiauth_apigroupprofile",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="apigroupprofileevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_apigroupprofileevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="apigroupprofileevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_apigroupprofileevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="apigroupprofileevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_apigroupprofileevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="apigroupprofileevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_apigroupprofileevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="apigroupprofileevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_apigroupprofileevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="apigroupprofileevent",
            index=models.Index(fields=["id"], name="idx_apigroupprofileevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apigroupprofileevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="2823bb4d43ed72e80bab80d83c05a9d5d56a4a97",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_aa0af",
                    table="apiauth_apigroupprofileevent",
                    when="BEFORE",
                ),
            ),
        ),
    ]
