# Generated by Django 6.1 on 2026-10-06 17:34

from typing import TYPE_CHECKING

import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.state import StateApps

# Los operadores que ya existían quedaron con ámbito global (el valor por defecto): antes
# de exigir que un operador tenga ámbito, se les pone el de su organización.
OPERATOR_SCOPES = {
    "alcaldia": "municipality",
    "institucion": "institution",
    "negocio": "business",
}


def set_operator_scopes(
    apps: StateApps,
    schema_editor: BaseDatabaseSchemaEditor,  # ruff: ignore[unused-function-argument]
) -> None:
    profile = apps.get_model("apiauth", "ApiGroupProfile")

    for role, scope in OPERATOR_SCOPES.items():
        profile.objects.filter(kind="operator", role=role).update(scope=scope)


class Migration(migrations.Migration):
    dependencies = [
        ("apiauth", "0006_group_profile"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="apigroupprofile",
            name="trg_log_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="apigroupprofile",
            name="trg_log_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="apigroupprofile",
            name="trg_log_update",
        ),
        migrations.AddField(
            model_name="apigroupprofile",
            name="scope",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("business", "Business"),
                    ("institution", "Institution"),
                    ("municipality", "Municipality"),
                ],
                db_default="global",
                default="global",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="apigroupprofileevent",
            name="scope",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("business", "Business"),
                    ("institution", "Institution"),
                    ("municipality", "Municipality"),
                ],
                db_default="global",
                default="global",
                max_length=16,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apigroupprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apigroupprofileevent" ("created_at", "description", "group_id", "id", "is_system", "kind", "pgh_context", "pgh_created_at", "pgh_label", "requires_two_factor", "role", "scope") VALUES (OLD."created_at", OLD."description", OLD."group_id", OLD."id", OLD."is_system", OLD."kind", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."requires_two_factor", OLD."role", OLD."scope"); RETURN NULL;',
                    hash="a7d2acf37eae1281864e00a356c95afef7fded9c",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_be7cf",
                    table="apiauth_apigroupprofile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apigroupprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "apiauth_apigroupprofileevent" ("created_at", "description", "group_id", "id", "is_system", "kind", "pgh_context", "pgh_created_at", "pgh_label", "requires_two_factor", "role", "scope") VALUES (NEW."created_at", NEW."description", NEW."group_id", NEW."id", NEW."is_system", NEW."kind", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."requires_two_factor", NEW."role", NEW."scope"); RETURN NULL;',
                    hash="43f76ac40ccb685ed96f8cfd06034e23d2d09539",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_1ead6",
                    table="apiauth_apigroupprofile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apigroupprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "apiauth_apigroupprofileevent" ("created_at", "description", "group_id", "id", "is_system", "kind", "pgh_context", "pgh_created_at", "pgh_label", "requires_two_factor", "role", "scope") VALUES (NEW."created_at", NEW."description", NEW."group_id", NEW."id", NEW."is_system", NEW."kind", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."requires_two_factor", NEW."role", NEW."scope"); RETURN NULL;',
                    hash="ba9821caa7b42c74b8d2cb9470e1309ac6e6ca1e",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_2bc98",
                    table="apiauth_apigroupprofile",
                    when="AFTER",
                ),
            ),
        ),
        migrations.RunPython(set_operator_scopes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="apigroupprofile",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "scope__in",
                    ["global", "business", "institution", "municipality"],
                )),
                name="chk_apigroupprofile_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="apigroupprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "operator"),
                        models.Q(("scope", "global"), _negated=True),
                    ),
                    models.Q(
                        models.Q(("kind", "operator"), _negated=True),
                        ("scope", "global"),
                    ),
                    _connector="OR",
                ),
                name="chk_apigroupprofile_scope_kind",
            ),
        ),
    ]
