# Generated by Django 6.1 on 2026-10-06 17:33

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    # los índices del historial usan `gin_trgm_ops`: la extensión va antes
    dependencies = [("apicore", "0002_immutable_unaccent")]

    operations = [
        migrations.CreateModel(
            name="CityEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("name", models.CharField(db_column="nombre", max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        db_column="latitud", decimal_places=6, max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        db_column="longitud", decimal_places=6, max_digits=9
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="activa", db_default=False, default=False
                    ),
                ),
            ],
            options={
                "db_table": "ciudad_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="nombre", max_length=150)),
                (
                    "contact_email",
                    models.EmailField(db_column="correo_contacto", max_length=254),
                ),
                ("phone", models.CharField(db_column="telefono", max_length=30)),
                (
                    "document_key",
                    models.CharField(db_column="documento_id", max_length=255),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        db_column="dada_de_alta_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        db_column="verificado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "alcaldia",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MunicipalityEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="nombre", max_length=150)),
                (
                    "contact_email",
                    models.EmailField(db_column="correo_contacto", max_length=254),
                ),
                ("phone", models.CharField(db_column="telefono", max_length=30)),
                (
                    "document_key",
                    models.CharField(db_column="documento_id", max_length=255),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        db_column="dada_de_alta_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        db_column="verificado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "alcaldia_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("name", models.CharField(db_column="nombre", max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        db_column="latitud", decimal_places=6, max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        db_column="longitud", decimal_places=6, max_digits=9
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="activa", db_default=False, default=False
                    ),
                ),
            ],
            options={
                "db_table": "ciudad",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="unq_ciudad_codigo")
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="city",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="f1b96b7d7da5c96d543efc03ee3dcb8d04ab472a",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_63fab",
                    table="ciudad",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="city",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="22a9d911b3d2149c51d97cfa354ac5b9aa9f8722",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_c16ff",
                    table="ciudad",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="city",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "ciudad_cambio" ("activa", "codigo", "id", "latitud", "longitud", "nombre", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."activa", OLD."codigo", OLD."id", OLD."latitud", OLD."longitud", OLD."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="30b105884ead0fef6635a04a7c86e8efc352751f",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_ec505",
                    table="ciudad",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="city",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "ciudad_cambio" ("activa", "codigo", "id", "latitud", "longitud", "nombre", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activa", NEW."codigo", NEW."id", NEW."latitud", NEW."longitud", NEW."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="83ac24d1fac13d51b70f71274b221f0516dded6b",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_25e86",
                    table="ciudad",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="city",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "ciudad_cambio" ("activa", "codigo", "id", "latitud", "longitud", "nombre", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activa", NEW."codigo", NEW."id", NEW."latitud", NEW."longitud", NEW."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="bb39b32ad24fa76d98de28dc2b594cfa0090aeff",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_e1187",
                    table="ciudad",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="cityevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_cityevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="cityevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_cityevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="cityevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_cityevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="cityevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_cityevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="cityevent",
            index=models.Index(fields=["pgh_label"], name="idx_cityevent_pghlabel"),
        ),
        migrations.AddIndex(
            model_name="cityevent",
            index=models.Index(fields=["id"], name="idx_cityevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="cityevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="d1a6429b07a61f3d2a7785d163b68f193c7ae750",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_af198",
                    table="ciudad_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddField(
            model_name="municipality",
            name="city",
            field=models.OneToOneField(
                db_column="ciudad_id",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="municipality",
                to="apiterritory.city",
            ),
        ),
        migrations.AddField(
            model_name="municipalityevent",
            name="city",
            field=models.ForeignKey(
                db_column="ciudad_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiterritory.city",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="municipality",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="678f6dde6a0efd6b1636836380955b5da4185d52",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_6a01f",
                    table="alcaldia",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="municipality",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="16005648abc3aea205563871de3388e9c434b9a7",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_e10dc",
                    table="alcaldia",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="municipality",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_alcaldia_noreverifica",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."verificado_en" IS NULL AND OLD."verificado_en" IS NOT NULL)',
                    func="RAISE EXCEPTION 'La verificación de una alcaldía no se revierte.';",
                    hash="299e8fbb34016d37316c056ae147138561825ebd",
                    operation='UPDATE OF "verificado_en"',
                    pgid="pgtrigger_trg_alcaldia_noreverifica_f60a6",
                    table="alcaldia",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="municipality",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "alcaldia_cambio" ("ciudad_id", "correo_contacto", "dada_de_alta_en", "documento_id", "id", "nombre", "pgh_context", "pgh_created_at", "pgh_label", "telefono", "verificado_en") VALUES (OLD."ciudad_id", OLD."correo_contacto", OLD."dada_de_alta_en", OLD."documento_id", OLD."id", OLD."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."telefono", OLD."verificado_en"); RETURN NULL;',
                    hash="69dfb854a715bcdee9a8b50b2e46dec84f13b758",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_e8a59",
                    table="alcaldia",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="municipality",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "alcaldia_cambio" ("ciudad_id", "correo_contacto", "dada_de_alta_en", "documento_id", "id", "nombre", "pgh_context", "pgh_created_at", "pgh_label", "telefono", "verificado_en") VALUES (NEW."ciudad_id", NEW."correo_contacto", NEW."dada_de_alta_en", NEW."documento_id", NEW."id", NEW."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."telefono", NEW."verificado_en"); RETURN NULL;',
                    hash="0d356cee1a789c2e78534ab6581f5fd39304270d",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_3b0f3",
                    table="alcaldia",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="municipality",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "alcaldia_cambio" ("ciudad_id", "correo_contacto", "dada_de_alta_en", "documento_id", "id", "nombre", "pgh_context", "pgh_created_at", "pgh_label", "telefono", "verificado_en") VALUES (NEW."ciudad_id", NEW."correo_contacto", NEW."dada_de_alta_en", NEW."documento_id", NEW."id", NEW."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."telefono", NEW."verificado_en"); RETURN NULL;',
                    hash="80653f16c63f186f63b675d61418e7a28c7f830d",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_d25b8",
                    table="alcaldia",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="municipalityevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_municipalityevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="municipalityevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_municipalityevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="municipalityevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_municipalityevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="municipalityevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_municipalityevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="municipalityevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_municipalityevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="municipalityevent",
            index=models.Index(fields=["id"], name="idx_municipalityevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="municipalityevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="728f6f1a0defec61fa68a9aff901c6772d20c9ff",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_201b8",
                    table="alcaldia_cambio",
                    when="BEFORE",
                ),
            ),
        ),
    ]
