# Generated by Django 6.1 on 2026-10-07 23:54

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations, models

import api_utils.db


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apicatalogs", "0004_agenda_cupones"),
        ("apiorganizations", "0003_foto_lugares_circuitos"),
        ("apiterritory", "0002_lugares_circuitos"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventStatusEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=24)),
                ("label", models.CharField(db_column="etiqueta", max_length=60)),
                ("is_visible", models.BooleanField(db_column="es_visible")),
                ("allows_editing", models.BooleanField(db_column="admite_edicion")),
                ("generates_alerts", models.BooleanField(db_column="genera_avisos")),
                ("is_terminal", models.BooleanField(db_column="es_terminal")),
            ],
            options={
                "db_table": "estado_evento_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="nombre", max_length=120)),
                (
                    "description",
                    models.TextField(
                        blank=True, db_column="descripcion", db_default="", default=""
                    ),
                ),
                ("venue", models.CharField(db_column="recinto", max_length=150)),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_column="direccion",
                        db_default="",
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        db_column="latitud", decimal_places=6, max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        db_column="longitud", decimal_places=6, max_digits=9
                    ),
                ),
                ("start_date", models.DateField(db_column="fecha_inicio")),
                ("end_date", models.DateField(db_column="fecha_fin")),
                ("start_time", models.TimeField(db_column="hora_inicio")),
                ("end_time", models.TimeField(db_column="hora_fin")),
                (
                    "entry_price",
                    models.IntegerField(
                        db_column="precio_entrada", db_default=0, default=0
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        db_column="destacado", db_default=False, default=False
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        db_column="motivo_cancelacion",
                        db_default="",
                        default="",
                        max_length=500,
                    ),
                ),
                (
                    "hidden_at",
                    models.DateTimeField(
                        db_column="oculto_en", db_default=None, default=None, null=True
                    ),
                ),
                (
                    "hidden_reason",
                    models.CharField(
                        blank=True,
                        db_column="motivo_oculto",
                        db_default="",
                        default="",
                        max_length=500,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_column="categoria_evento_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="events",
                        to="apicatalogs.eventcategory",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        db_column="ciudad_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="events",
                        to="apiterritory.city",
                    ),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        db_column="clonado_de_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clones",
                        to="apiagenda.event",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        db_column="institucion_cultural_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="events",
                        to="apiorganizations.culturalinstitution",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        db_column="alcaldia_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="events",
                        to="apiterritory.municipality",
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        db_column="punto_interes_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="apiterritory.pointofinterest",
                    ),
                ),
            ],
            options={
                "db_table": "evento",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=24)),
                ("label", models.CharField(db_column="etiqueta", max_length=60)),
                ("is_visible", models.BooleanField(db_column="es_visible")),
                ("allows_editing", models.BooleanField(db_column="admite_edicion")),
                ("generates_alerts", models.BooleanField(db_column="genera_avisos")),
                ("is_terminal", models.BooleanField(db_column="es_terminal")),
            ],
            options={
                "db_table": "estado_evento",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",), name="unq_estadoevento_codigo"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="nombre", max_length=120)),
                (
                    "description",
                    models.TextField(
                        blank=True, db_column="descripcion", db_default="", default=""
                    ),
                ),
                ("venue", models.CharField(db_column="recinto", max_length=150)),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_column="direccion",
                        db_default="",
                        default="",
                        max_length=200,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        db_column="latitud", decimal_places=6, max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        db_column="longitud", decimal_places=6, max_digits=9
                    ),
                ),
                ("start_date", models.DateField(db_column="fecha_inicio")),
                ("end_date", models.DateField(db_column="fecha_fin")),
                ("start_time", models.TimeField(db_column="hora_inicio")),
                ("end_time", models.TimeField(db_column="hora_fin")),
                (
                    "entry_price",
                    models.IntegerField(
                        db_column="precio_entrada", db_default=0, default=0
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        db_column="destacado", db_default=False, default=False
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        db_column="motivo_cancelacion",
                        db_default="",
                        default="",
                        max_length=500,
                    ),
                ),
                (
                    "hidden_at",
                    models.DateTimeField(
                        db_column="oculto_en", db_default=None, default=None, null=True
                    ),
                ),
                (
                    "hidden_reason",
                    models.CharField(
                        blank=True,
                        db_column="motivo_oculto",
                        db_default="",
                        default="",
                        max_length=500,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_column="categoria_evento_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apicatalogs.eventcategory",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        db_column="ciudad_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiterritory.city",
                    ),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        db_column="clonado_de_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiagenda.event",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        db_column="institucion_cultural_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiorganizations.culturalinstitution",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        db_column="alcaldia_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiterritory.municipality",
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        db_column="punto_interes_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiterritory.pointofinterest",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        db_column="estado_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiagenda.eventstatus",
                    ),
                ),
            ],
            options={
                "db_table": "evento_cambio",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.ForeignKey(
                db_column="estado_id",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="events",
                to="apiagenda.eventstatus",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="1aad41b0612727ba5d46edd7970523b359ce743a",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_0f6ee",
                    table="estado_evento",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="893cb659f654d7adcbbc3d6b6d563b6ec320a4dc",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_72974",
                    table="estado_evento",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estado_evento_cambio" ("admite_edicion", "codigo", "es_terminal", "es_visible", "etiqueta", "genera_avisos", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."admite_edicion", OLD."codigo", OLD."es_terminal", OLD."es_visible", OLD."etiqueta", OLD."genera_avisos", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="05faab8173bf1c100783313d3d4130f23e520dd8",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_43bac",
                    table="estado_evento",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estado_evento_cambio" ("admite_edicion", "codigo", "es_terminal", "es_visible", "etiqueta", "genera_avisos", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."admite_edicion", NEW."codigo", NEW."es_terminal", NEW."es_visible", NEW."etiqueta", NEW."genera_avisos", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="d25b44271f58d6f9b7fe5852e567620f9fb16897",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_0f0d6",
                    table="estado_evento",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "estado_evento_cambio" ("admite_edicion", "codigo", "es_terminal", "es_visible", "etiqueta", "genera_avisos", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."admite_edicion", NEW."codigo", NEW."es_terminal", NEW."es_visible", NEW."etiqueta", NEW."genera_avisos", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="96bb9cc0b3db52ffe770941576858ffa28b70640",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_66df4",
                    table="estado_evento",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="eventstatusevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_eventstatusevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="eventstatusevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_eventstatusevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="eventstatusevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_eventstatusevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="eventstatusevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_eventstatusevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="eventstatusevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_eventstatusevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="eventstatusevent",
            index=models.Index(fields=["id"], name="idx_eventstatusevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventstatusevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="dbfc2e3651c5f5de96afc32a504aa7d9623f3e27",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_9c52a",
                    table="estado_evento_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="eventevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_eventevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="eventevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_eventevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="eventevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_eventevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="eventevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_eventevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="eventevent",
            index=models.Index(fields=["pgh_label"], name="idx_eventevent_pghlabel"),
        ),
        migrations.AddIndex(
            model_name="eventevent",
            index=models.Index(fields=["id"], name="idx_eventevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="4cecbd5bde3add2000e38f207fba251f4ae5b806",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_cff22",
                    table="evento_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["city", "start_date"], name="idx_evento_agenda"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["start_date", "end_date"], name="idx_evento_vigencia"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                condition=models.Q(("cloned_from__isnull", False)),
                fields=["cloned_from"],
                name="idx_evento_clonado",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.functions.text.Upper(
                        api_utils.db.ImmutableUnaccent("name")
                    ),
                    name="gin_trgm_ops",
                ),
                name="gin_evento_nombre",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("institution__isnull", True),
                    ("municipality__isnull", True),
                    _connector="OR",
                ),
                name="chk_evento_organizador_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="chk_evento_fechas_orden",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time", models.F("start_time")), _negated=True),
                name="chk_evento_horas_distintas",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("entry_price__gte", 0)),
                name="chk_evento_precio_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", 10.7), ("latitude__lte", 15.1)),
                name="chk_evento_latitud_rango",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("longitude__gte", -87.7), ("longitude__lte", -82.6)
                ),
                name="chk_evento_longitud_rango",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("cloned_from", models.F("id")), _negated=True),
                name="chk_evento_no_autoclon",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="event",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="c8136623b088ec27d51e7013a67133cf6746cd91",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_a9257",
                    table="evento",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="event",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="99caa6d8f3e1ed99c5fcc000d25197783daa6540",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_09d34",
                    table="evento",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="event",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_evento_readonly_creadoen",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."creado_en" IS DISTINCT FROM (NEW."creado_en"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="4513dd83a6d3e52ec47a49fd437138571619d94f",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_evento_readonly_creadoen_1d371",
                    table="evento",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="event",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "evento_cambio" ("alcaldia_id", "categoria_evento_id", "ciudad_id", "clonado_de_id", "creado_en", "descripcion", "destacado", "direccion", "estado_id", "fecha_fin", "fecha_inicio", "hora_fin", "hora_inicio", "id", "institucion_cultural_id", "latitud", "longitud", "motivo_cancelacion", "motivo_oculto", "nombre", "oculto_en", "pgh_context", "pgh_created_at", "pgh_label", "precio_entrada", "punto_interes_id", "recinto") VALUES (OLD."alcaldia_id", OLD."categoria_evento_id", OLD."ciudad_id", OLD."clonado_de_id", OLD."creado_en", OLD."descripcion", OLD."destacado", OLD."direccion", OLD."estado_id", OLD."fecha_fin", OLD."fecha_inicio", OLD."hora_fin", OLD."hora_inicio", OLD."id", OLD."institucion_cultural_id", OLD."latitud", OLD."longitud", OLD."motivo_cancelacion", OLD."motivo_oculto", OLD."nombre", OLD."oculto_en", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."precio_entrada", OLD."punto_interes_id", OLD."recinto"); RETURN NULL;',
                    hash="222684e063917c73a9bcd7f2e3c3896575a0c08f",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_6bbce",
                    table="evento",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="event",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "evento_cambio" ("alcaldia_id", "categoria_evento_id", "ciudad_id", "clonado_de_id", "creado_en", "descripcion", "destacado", "direccion", "estado_id", "fecha_fin", "fecha_inicio", "hora_fin", "hora_inicio", "id", "institucion_cultural_id", "latitud", "longitud", "motivo_cancelacion", "motivo_oculto", "nombre", "oculto_en", "pgh_context", "pgh_created_at", "pgh_label", "precio_entrada", "punto_interes_id", "recinto") VALUES (NEW."alcaldia_id", NEW."categoria_evento_id", NEW."ciudad_id", NEW."clonado_de_id", NEW."creado_en", NEW."descripcion", NEW."destacado", NEW."direccion", NEW."estado_id", NEW."fecha_fin", NEW."fecha_inicio", NEW."hora_fin", NEW."hora_inicio", NEW."id", NEW."institucion_cultural_id", NEW."latitud", NEW."longitud", NEW."motivo_cancelacion", NEW."motivo_oculto", NEW."nombre", NEW."oculto_en", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."precio_entrada", NEW."punto_interes_id", NEW."recinto"); RETURN NULL;',
                    hash="f321dfcfd7d3a42a83d88d0fdaf1e7d0f9515b82",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_1bdaf",
                    table="evento",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="event",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "evento_cambio" ("alcaldia_id", "categoria_evento_id", "ciudad_id", "clonado_de_id", "creado_en", "descripcion", "destacado", "direccion", "estado_id", "fecha_fin", "fecha_inicio", "hora_fin", "hora_inicio", "id", "institucion_cultural_id", "latitud", "longitud", "motivo_cancelacion", "motivo_oculto", "nombre", "oculto_en", "pgh_context", "pgh_created_at", "pgh_label", "precio_entrada", "punto_interes_id", "recinto") VALUES (NEW."alcaldia_id", NEW."categoria_evento_id", NEW."ciudad_id", NEW."clonado_de_id", NEW."creado_en", NEW."descripcion", NEW."destacado", NEW."direccion", NEW."estado_id", NEW."fecha_fin", NEW."fecha_inicio", NEW."hora_fin", NEW."hora_inicio", NEW."id", NEW."institucion_cultural_id", NEW."latitud", NEW."longitud", NEW."motivo_cancelacion", NEW."motivo_oculto", NEW."nombre", NEW."oculto_en", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."precio_entrada", NEW."punto_interes_id", NEW."recinto"); RETURN NULL;',
                    hash="907f913651754b899663d7519e94d2d947a3cd0c",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_697c3",
                    table="evento",
                    when="AFTER",
                ),
            ),
        ),
    ]
