services:
  migrate:
    build:
      cache_from:
        - type=gha,scope=kplanapi-prod

  kplanapi-prod:
    build:
      cache_from:
        - type=gha,scope=kplanapi-prod
      cache_to:
        - type=gha,mode=max,scope=kplanapi-prod
