services:
  migrate:
    build:
      cache_from:
        - type=gha,scope=kplan-api-prod

  kplan-api-prod:
    build:
      cache_from:
        - type=gha,scope=kplan-api-prod
      cache_to:
        - type=gha,mode=max,scope=kplan-api-prod
