[project]
  edit_uri  = "edit/staging/docs/"
  repo_name = "Los-Come-Tuani/api"
  repo_url  = "https://github.com/Los-Come-Tuani/api"

  site_author      = "Joaquín Zúñiga"
  site_description = "Microservicios para la aplicación móvil K'Plan."
  site_name        = "api-docs"

  nav = [
    { "Inicio" = "index.md" },
    {
      "Requerimientos" = [
        "requerimientos/index.md",
        {
          "Funcionales" = [
            "requerimientos/funcionales/plataforma.md",
            "requerimientos/funcionales/app-movil.md",
            "requerimientos/funcionales/portal-prestadores.md",
            "requerimientos/funcionales/portal-comercios.md",
            "requerimientos/funcionales/portal-alcaldias.md",
            "requerimientos/funcionales/portal-instituciones.md",
            "requerimientos/funcionales/backoffice.md",
          ],
        },
        "requerimientos/no-funcionales.md",
      ],
    },
  ]

  [project.markdown_extensions]
    abbr       = {}
    admonition = {}
    attr_list  = {}
    def_list   = {}
    md_in_html = {}
    tables     = {}

    toc = {
      permalink = true,
      toc_depth = 3,
    }

    [project.markdown_extensions.pymdownx]
      blocks.caption = {}
      caret          = {}
      details        = {}
      emoji          = {}
      highlight      = {}
      keys           = {}
      mark           = {}
      tilde          = {}

      tasklist.custom_checkbox = true

      snippets.auto_append = [
        "docs/snippets/abbrs.md",
        "docs/snippets/links.md",
      ]

      superfences.custom_fences = [
        {
          name   = "mermaid",
          class  = "mermaid",
          format = "pymdownx.superfences.fence_code_format",
        },
      ]

      [project.markdown_extensions.pymdownx.tabbed]
        alternate_style = true

        slugify = {
          kwds.case = "lower",
          object    = "pymdownx.slugs.slugify",
        }

  [project.theme]
    features = [
      "content.code.copy",
      "content.tooltips",
      "navigation.footer",
      "navigation.indexes",
      "navigation.instant",
      "navigation.instant.prefetch",
      "navigation.instant.progress",
      "navigation.path",
    ]

    favicon = "favicon.svg"
    logo    = "logo.svg"
    variant = "modern"

    [[project.theme.palette]]
      media       = "(prefers-color-scheme: light)"
      scheme      = "default"
      toggle.icon = "lucide/sun"
      toggle.name = "Go to dark mode!"

    [[project.theme.palette]]
      media       = "(prefers-color-scheme: dark)"
      scheme      = "slate"
      toggle.icon = "lucide/moon"
      toggle.name = "Go to light mode!"

  [project.validation]
    invalid_link_anchors  = false
    invalid_links         = false
    shadowed_definitions  = false
    shadowed_footnotes    = false
    unresolved_footnotes  = false
    unresolved_references = false
    unused_definitions    = false
    unused_footnotes      = false
