# Generated by Django 6.1 on 2026-10-06 17:33

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessTypeEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("label", models.CharField(db_column="etiqueta", max_length=100)),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "tipo_negocio_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=3)),
                ("name", models.CharField(db_column="nombre", max_length=100)),
                (
                    "decimals",
                    models.SmallIntegerField(
                        db_column="decimales", db_default=2, default=2
                    ),
                ),
            ],
            options={
                "db_table": "moneda",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CurrencyEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=3)),
                ("name", models.CharField(db_column="nombre", max_length=100)),
                (
                    "decimals",
                    models.SmallIntegerField(
                        db_column="decimales", db_default=2, default=2
                    ),
                ),
            ],
            options={
                "db_table": "moneda_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstitutionType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("label", models.CharField(db_column="etiqueta", max_length=100)),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "tipo_institucion",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstitutionTypeEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("label", models.CharField(db_column="etiqueta", max_length=100)),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "tipo_institucion_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=60)),
                ("label", models.CharField(db_column="etiqueta", max_length=150)),
                (
                    "requires_text",
                    models.BooleanField(
                        db_column="exige_texto", db_default=False, default=False
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "motivo",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReasonContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("context", models.CharField(db_column="contexto", max_length=60)),
                (
                    "order",
                    models.SmallIntegerField(
                        db_column="orden", db_default=0, default=0
                    ),
                ),
            ],
            options={
                "db_table": "motivo_contexto",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReasonContextEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("context", models.CharField(db_column="contexto", max_length=60)),
                (
                    "order",
                    models.SmallIntegerField(
                        db_column="orden", db_default=0, default=0
                    ),
                ),
            ],
            options={
                "db_table": "motivo_contexto_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReasonEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=60)),
                ("label", models.CharField(db_column="etiqueta", max_length=150)),
                (
                    "requires_text",
                    models.BooleanField(
                        db_column="exige_texto", db_default=False, default=False
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "motivo_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BusinessType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("label", models.CharField(db_column="etiqueta", max_length=100)),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "tipo_negocio",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",), name="unq_tiponegocio_codigo"
                    )
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="businesstype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="a7ffe52e8350c05f25eb7451f2d8901655ca3a57",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_0286a",
                    table="tipo_negocio",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="businesstype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="c24be1f63369c51fc0ddb1cda0bce181e44be9ff",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_20db6",
                    table="tipo_negocio",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="businesstype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tipo_negocio_cambio" ("activo", "codigo", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."activo", OLD."codigo", OLD."etiqueta", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="477719484ce458d4c68518e236d1806f492c2f70",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_83b53",
                    table="tipo_negocio",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="businesstype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tipo_negocio_cambio" ("activo", "codigo", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="a803a83a0d777bfeab20d60b717269b7d8c86b7d",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_3ae27",
                    table="tipo_negocio",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="businesstype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "tipo_negocio_cambio" ("activo", "codigo", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="716722ad1827c77e8cfa5c502e07314f45857c12",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_86479",
                    table="tipo_negocio",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="businesstypeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_businesstypeevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="businesstypeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_businesstypeevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="businesstypeevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_businesstypeevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="businesstypeevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_businesstypeevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="businesstypeevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_businesstypeevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="businesstypeevent",
            index=models.Index(fields=["id"], name="idx_businesstypeevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="businesstypeevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="b7257928c654237cc9af92953ea66e8f4fd0f754",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_0532b",
                    table="tipo_negocio_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="currency",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unq_moneda_codigo"
            ),
        ),
        migrations.AddConstraint(
            model_name="currency",
            constraint=models.CheckConstraint(
                condition=models.Q(("decimals__gte", 0), ("decimals__lte", 6)),
                name="chk_moneda_decimales_rango",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="currency",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="b509d006db2334d91d51ba054dad5ccaead6b5a9",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_c173f",
                    table="moneda",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="currency",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="0f1e6f48af651fd9298a8b2c391fd4334a4efb54",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_ae4bd",
                    table="moneda",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="currency",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "moneda_cambio" ("codigo", "decimales", "id", "nombre", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."codigo", OLD."decimales", OLD."id", OLD."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="529eb3f156281038c1bc76e4c3c7dc47f0e8505c",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_2ddd8",
                    table="moneda",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="currency",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "moneda_cambio" ("codigo", "decimales", "id", "nombre", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."codigo", NEW."decimales", NEW."id", NEW."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="2e59d27074300222338a36ae4f47f003950b40e6",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_d8d91",
                    table="moneda",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="currency",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "moneda_cambio" ("codigo", "decimales", "id", "nombre", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."codigo", NEW."decimales", NEW."id", NEW."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="d27e336abb20e58528a5e63c62410c146be8f943",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_3401f",
                    table="moneda",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="currencyevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_currencyevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="currencyevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_currencyevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="currencyevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_currencyevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="currencyevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_currencyevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="currencyevent",
            index=models.Index(fields=["pgh_label"], name="idx_currencyevent_pghlabel"),
        ),
        migrations.AddIndex(
            model_name="currencyevent",
            index=models.Index(fields=["id"], name="idx_currencyevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="currencyevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="b149256647f28da942e222b34b9d8ece303e5bf1",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_f09e3",
                    table="moneda_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="institutiontype",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unq_tipoinstitucion_codigo"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="institutiontype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="6e1c957b50d41ccf2fcc938198de04a5b9010cbf",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_62ce8",
                    table="tipo_institucion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="institutiontype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="b7169fd8228eee57e48e81c96e3ab22636e1b285",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_153e4",
                    table="tipo_institucion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="institutiontype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tipo_institucion_cambio" ("activo", "codigo", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."activo", OLD."codigo", OLD."etiqueta", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="4dcb8a06f0ea64c2720b0729e0a82e52ccab6498",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_db30b",
                    table="tipo_institucion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="institutiontype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tipo_institucion_cambio" ("activo", "codigo", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="b5f495b9c58323740bd2b8f2332188e0ea33f3e6",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_c1899",
                    table="tipo_institucion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="institutiontype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "tipo_institucion_cambio" ("activo", "codigo", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="25bff788df2833b04a3480977a17d59b96e873d9",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_95d07",
                    table="tipo_institucion",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="institutiontypeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_institutiontypeevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="institutiontypeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_institutiontypeevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="institutiontypeevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_institutiontypeevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="institutiontypeevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_institutiontypeevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="institutiontypeevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_institutiontypeevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="institutiontypeevent",
            index=models.Index(fields=["id"], name="idx_institutiontypeevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="institutiontypeevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="2da5bea468cde994ce3079bd047ccc7ce52ed518",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_902db",
                    table="tipo_institucion_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="reason",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unq_motivo_codigo"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reason",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="52e82b93225056e5aff32fde3a3fa43716a716af",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_87479",
                    table="motivo",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reason",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="95010a0a9c51c0fcf4cf38858991f537b3403350",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_2dac6",
                    table="motivo",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reason",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "motivo_cambio" ("activo", "codigo", "etiqueta", "exige_texto", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."activo", OLD."codigo", OLD."etiqueta", OLD."exige_texto", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="e3a05c32e8fdbc4a914ec72c8bee2159fd2cc3a2",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_1fdd9",
                    table="motivo",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reason",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "motivo_cambio" ("activo", "codigo", "etiqueta", "exige_texto", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."etiqueta", NEW."exige_texto", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="e7b494c89e4c4debe4b933236390739cc0e99902",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_96612",
                    table="motivo",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reason",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "motivo_cambio" ("activo", "codigo", "etiqueta", "exige_texto", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."etiqueta", NEW."exige_texto", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="bd053a7f0af9d842651d3ee399e2039800d224c9",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_36cf7",
                    table="motivo",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="reasoncontext",
            name="reason",
            field=models.ForeignKey(
                db_column="motivo_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contexts",
                to="apicatalogs.reason",
            ),
        ),
        migrations.AddField(
            model_name="reasoncontextevent",
            name="reason",
            field=models.ForeignKey(
                db_column="motivo_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apicatalogs.reason",
            ),
        ),
        migrations.AddIndex(
            model_name="reasonevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_reasonevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="reasonevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_reasonevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="reasonevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_reasonevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="reasonevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_reasonevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="reasonevent",
            index=models.Index(fields=["pgh_label"], name="idx_reasonevent_pghlabel"),
        ),
        migrations.AddIndex(
            model_name="reasonevent",
            index=models.Index(fields=["id"], name="idx_reasonevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reasonevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="e9c3906006b75141e7cd3bc880d0511e05c42307",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_6989f",
                    table="motivo_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="reasoncontext",
            constraint=models.UniqueConstraint(
                fields=("reason", "context"), name="unq_motivocontexto_par"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reasoncontext",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="1f93f7bd9f199c976c413eda7e14a63705352214",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_5b6ef",
                    table="motivo_contexto",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reasoncontext",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="5f30fc942d801cf9e7b1349b8f67d1785ccd5870",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_e7114",
                    table="motivo_contexto",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reasoncontext",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "motivo_contexto_cambio" ("contexto", "id", "motivo_id", "orden", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."contexto", OLD."id", OLD."motivo_id", OLD."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="d015612a9a964884aa9bfd3129cab5ff0c91fa69",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_28c5f",
                    table="motivo_contexto",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reasoncontext",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "motivo_contexto_cambio" ("contexto", "id", "motivo_id", "orden", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."contexto", NEW."id", NEW."motivo_id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="6d1a3735d280f2136b462a3d0af2e83a8082df0b",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_57e43",
                    table="motivo_contexto",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reasoncontext",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "motivo_contexto_cambio" ("contexto", "id", "motivo_id", "orden", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."contexto", NEW."id", NEW."motivo_id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="4b1fd5e7a66b4a271cc49c887c6d95290a15e60d",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_2afe7",
                    table="motivo_contexto",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="reasoncontextevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_reasoncontextevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="reasoncontextevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_reasoncontextevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="reasoncontextevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_reasoncontextevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="reasoncontextevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_reasoncontextevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="reasoncontextevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_reasoncontextevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="reasoncontextevent",
            index=models.Index(fields=["id"], name="idx_reasoncontextevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reasoncontextevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="5b4a0c00fe1d9320abdb7fa50f3eb37f729b6095",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_38726",
                    table="motivo_contexto_cambio",
                    when="BEFORE",
                ),
            ),
        ),
    ]
