# Generated by Django 6.1 on 2026-10-06 22:57

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apicatalogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("label", models.CharField(db_column="etiqueta", max_length=100)),
                (
                    "requires_expiry",
                    models.BooleanField(
                        db_column="exige_vencimiento", db_default=True, default=True
                    ),
                ),
                (
                    "requires_vehicle",
                    models.BooleanField(
                        db_column="exige_vehiculo", db_default=False, default=False
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        db_column="orden", db_default=0, default=0
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "tipo_acreditacion",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CredentialTypeEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("label", models.CharField(db_column="etiqueta", max_length=100)),
                (
                    "requires_expiry",
                    models.BooleanField(
                        db_column="exige_vencimiento", db_default=True, default=True
                    ),
                ),
                (
                    "requires_vehicle",
                    models.BooleanField(
                        db_column="exige_vehiculo", db_default=False, default=False
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        db_column="orden", db_default=0, default=0
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "tipo_acreditacion_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LanguageEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=8)),
                ("name", models.CharField(db_column="nombre", max_length=100)),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "idioma_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("label", models.CharField(db_column="etiqueta", max_length=100)),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "tipo_servicio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceTypeEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("label", models.CharField(db_column="etiqueta", max_length=100)),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "tipo_servicio_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=8)),
                ("name", models.CharField(db_column="nombre", max_length=100)),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "idioma",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="unq_idioma_codigo")
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="language",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="75d29fab8dfb94762dd33d1be067cfa5279a9bb0",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_d1890",
                    table="idioma",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="language",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="90eaa08104acc0d969988261014e74d1d18d6661",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_a1959",
                    table="idioma",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="language",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "idioma_cambio" ("activo", "codigo", "id", "nombre", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."activo", OLD."codigo", OLD."id", OLD."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="9edcea57215d37177ccd7966991ca594272ea978",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_eba58",
                    table="idioma",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="language",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "idioma_cambio" ("activo", "codigo", "id", "nombre", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."id", NEW."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="42073f1decf9c765e2b39c6c50ab75bce1a858d6",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_54285",
                    table="idioma",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="language",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "idioma_cambio" ("activo", "codigo", "id", "nombre", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."id", NEW."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="dff0b43541f2418d52e3bb71ccc8bc9e0d835ab7",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_4e216",
                    table="idioma",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="languageevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_languageevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="languageevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_languageevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="languageevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_languageevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="languageevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_languageevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="languageevent",
            index=models.Index(fields=["pgh_label"], name="idx_languageevent_pghlabel"),
        ),
        migrations.AddIndex(
            model_name="languageevent",
            index=models.Index(fields=["id"], name="idx_languageevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="languageevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="a72fde5efb11b6c90092f0b3e0531da26f27cf1f",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_c1c6c",
                    table="idioma_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetype",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unq_tiposervicio_codigo"
            ),
        ),
        migrations.AddField(
            model_name="credentialtypeevent",
            name="service",
            field=models.ForeignKey(
                db_column="tipo_servicio_id",
                db_constraint=False,
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apicatalogs.servicetype",
            ),
        ),
        migrations.AddField(
            model_name="credentialtype",
            name="service",
            field=models.ForeignKey(
                db_column="tipo_servicio_id",
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="credential_types",
                to="apicatalogs.servicetype",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="servicetype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="576d0c7bdd7964ffb44ddbd7738da9fda2537865",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_30261",
                    table="tipo_servicio",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="servicetype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="7a1a3585bfb65cddb54f031a7971909544c56916",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_79ea8",
                    table="tipo_servicio",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="servicetype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tipo_servicio_cambio" ("activo", "codigo", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."activo", OLD."codigo", OLD."etiqueta", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="a312b04e94d0eaf5017f7c962f686678b75b860f",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_e4da6",
                    table="tipo_servicio",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="servicetype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tipo_servicio_cambio" ("activo", "codigo", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="3c6c05156a4632e9eab4863ce535842b471b2e77",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_f09bd",
                    table="tipo_servicio",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="servicetype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "tipo_servicio_cambio" ("activo", "codigo", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="89ed86c49cd8c67af7a9534e9e60a568edb96234",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_e5cf4",
                    table="tipo_servicio",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="servicetypeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_servicetypeevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="servicetypeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_servicetypeevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="servicetypeevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_servicetypeevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="servicetypeevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_servicetypeevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="servicetypeevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_servicetypeevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="servicetypeevent",
            index=models.Index(fields=["id"], name="idx_servicetypeevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="servicetypeevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="be80b3bfdf84e13fa1e01c853aa341991e1b37eb",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_95781",
                    table="tipo_servicio_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="credentialtypeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_credentialtypeevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="credentialtypeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_credentialtypeevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="credentialtypeevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_credentialtypeevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="credentialtypeevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_credentialtypeevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="credentialtypeevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_credentialtypeevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="credentialtypeevent",
            index=models.Index(fields=["id"], name="idx_credentialtypeevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credentialtypeevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="f6108c6190da0eb772502a3dffe1068485baa1c2",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_dbe65",
                    table="tipo_acreditacion_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="credentialtype",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unq_tipoacreditacion_codigo"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credentialtype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="ae8001d567eb9589f7c802b03d37bceecde76a2b",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_df364",
                    table="tipo_acreditacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credentialtype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="77028a4f0449b894a5047506d3b58ca470b8d46d",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_154de",
                    table="tipo_acreditacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credentialtype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tipo_acreditacion_cambio" ("activo", "codigo", "etiqueta", "exige_vehiculo", "exige_vencimiento", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label", "tipo_servicio_id") VALUES (OLD."activo", OLD."codigo", OLD."etiqueta", OLD."exige_vehiculo", OLD."exige_vencimiento", OLD."id", OLD."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."tipo_servicio_id"); RETURN NULL;',
                    hash="40d5487f9bbe9ea7cfdb77911c201ec8083740ef",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_1e640",
                    table="tipo_acreditacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credentialtype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tipo_acreditacion_cambio" ("activo", "codigo", "etiqueta", "exige_vehiculo", "exige_vencimiento", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label", "tipo_servicio_id") VALUES (NEW."activo", NEW."codigo", NEW."etiqueta", NEW."exige_vehiculo", NEW."exige_vencimiento", NEW."id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."tipo_servicio_id"); RETURN NULL;',
                    hash="0c12e4eb6d5812b49917691deaffde4fe7c9204d",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_7c18d",
                    table="tipo_acreditacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credentialtype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "tipo_acreditacion_cambio" ("activo", "codigo", "etiqueta", "exige_vehiculo", "exige_vencimiento", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label", "tipo_servicio_id") VALUES (NEW."activo", NEW."codigo", NEW."etiqueta", NEW."exige_vehiculo", NEW."exige_vencimiento", NEW."id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."tipo_servicio_id"); RETURN NULL;',
                    hash="351f954533959c93161e4e5166cee4fd5d59f6bc",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_dbc1d",
                    table="tipo_acreditacion",
                    when="AFTER",
                ),
            ),
        ),
    ]
