# Generated by Django 6.1 on 2026-10-07 22:11

import uuid

import django.contrib.postgres.indexes
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apicatalogs", "0002_prestadores"),
    ]

    operations = [
        migrations.CreateModel(
            name="CulturalPillarEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("label", models.CharField(db_column="etiqueta", max_length=100)),
                (
                    "order",
                    models.SmallIntegerField(
                        db_column="orden", db_default=0, default=0
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "pilar_cultural_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CulturalPillar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("label", models.CharField(db_column="etiqueta", max_length=100)),
                (
                    "order",
                    models.SmallIntegerField(
                        db_column="orden", db_default=0, default=0
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "pilar_cultural",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",), name="unq_pilarcultural_codigo"
                    )
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="culturalpillar",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="837199ff219e94caea717a5807ffdd12641727dc",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_df678",
                    table="pilar_cultural",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="culturalpillar",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="4510f813432a03b6b69cf6fca28e6a3614ac7b13",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_0cd20",
                    table="pilar_cultural",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="culturalpillar",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pilar_cultural_cambio" ("activo", "codigo", "etiqueta", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."activo", OLD."codigo", OLD."etiqueta", OLD."id", OLD."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="ce4fda72d510d295800cea51757b0fa554b48d39",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_2712b",
                    table="pilar_cultural",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="culturalpillar",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "pilar_cultural_cambio" ("activo", "codigo", "etiqueta", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."etiqueta", NEW."id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="b40b38518b591e9a30dc231693b7d80b2b54a024",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_aa96c",
                    table="pilar_cultural",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="culturalpillar",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "pilar_cultural_cambio" ("activo", "codigo", "etiqueta", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."etiqueta", NEW."id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="406037743b9276e88809adb5786fa7a9689bf0ed",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_250e7",
                    table="pilar_cultural",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="culturalpillarevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_culturalpillarevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="culturalpillarevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_culturalpillarevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="culturalpillarevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_culturalpillarevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="culturalpillarevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_culturalpillarevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="culturalpillarevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_culturalpillarevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="culturalpillarevent",
            index=models.Index(fields=["id"], name="idx_culturalpillarevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="culturalpillarevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="2231dcecc6cb2dc120af41e0d95e088bee63c5d6",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_4ea1f",
                    table="pilar_cultural_cambio",
                    when="BEFORE",
                ),
            ),
        ),
    ]
