# Generated by Django 6.1 on 2026-10-07 23:53

import uuid

import django.contrib.postgres.indexes
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apicatalogs", "0003_pilares"),
    ]

    operations = [
        migrations.CreateModel(
            name="BenefitTypeEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("label", models.CharField(db_column="etiqueta", max_length=100)),
                (
                    "requires_amount",
                    models.BooleanField(
                        db_column="exige_monto", db_default=False, default=False
                    ),
                ),
                (
                    "is_percentage",
                    models.BooleanField(
                        db_column="es_porcentaje", db_default=False, default=False
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "tipo_beneficio_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("label", models.CharField(db_column="etiqueta", max_length=100)),
                (
                    "order",
                    models.SmallIntegerField(
                        db_column="orden", db_default=0, default=0
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "categoria_evento",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventCategoryEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("label", models.CharField(db_column="etiqueta", max_length=100)),
                (
                    "order",
                    models.SmallIntegerField(
                        db_column="orden", db_default=0, default=0
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "categoria_evento_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BenefitType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=40)),
                ("label", models.CharField(db_column="etiqueta", max_length=100)),
                (
                    "requires_amount",
                    models.BooleanField(
                        db_column="exige_monto", db_default=False, default=False
                    ),
                ),
                (
                    "is_percentage",
                    models.BooleanField(
                        db_column="es_porcentaje", db_default=False, default=False
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_column="activo", db_default=True, default=True
                    ),
                ),
            ],
            options={
                "db_table": "tipo_beneficio",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",), name="unq_tipobeneficio_codigo"
                    )
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="benefittype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="9e8690a8b8b0a4d47ea0f7ca0b7d69b08f6efd0c",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_cbda2",
                    table="tipo_beneficio",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="benefittype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="c9c181c685d01bd3ea3ef426e5f8c47d8bfc5147",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_5d4df",
                    table="tipo_beneficio",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="benefittype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tipo_beneficio_cambio" ("activo", "codigo", "es_porcentaje", "etiqueta", "exige_monto", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."activo", OLD."codigo", OLD."es_porcentaje", OLD."etiqueta", OLD."exige_monto", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="a93354cf5cf4bac3850970457de19f20427285c6",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_9b967",
                    table="tipo_beneficio",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="benefittype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tipo_beneficio_cambio" ("activo", "codigo", "es_porcentaje", "etiqueta", "exige_monto", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."es_porcentaje", NEW."etiqueta", NEW."exige_monto", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="89cdf4afd58692b27c00cc2f5ffd0b7d6249b87d",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_dd0e4",
                    table="tipo_beneficio",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="benefittype",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "tipo_beneficio_cambio" ("activo", "codigo", "es_porcentaje", "etiqueta", "exige_monto", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."es_porcentaje", NEW."etiqueta", NEW."exige_monto", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="e645a9dd9c282409b25f22e7ebdd23cb609dbe87",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_ddc98",
                    table="tipo_beneficio",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="benefittypeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_benefittypeevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="benefittypeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_benefittypeevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="benefittypeevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_benefittypeevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="benefittypeevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_benefittypeevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="benefittypeevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_benefittypeevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="benefittypeevent",
            index=models.Index(fields=["id"], name="idx_benefittypeevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="benefittypeevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="dccda3137bfbb80078d5da3d1773bbccc116d1ac",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_00a65",
                    table="tipo_beneficio_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="eventcategory",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unq_categoriaevento_codigo"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventcategory",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="f38d926321f7b2f36d6a06c94bbe82011e83b9b7",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_36c76",
                    table="categoria_evento",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventcategory",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="c75d2a7ebfa778a00cc4a74e4b510109ba33ae8d",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_ffdc5",
                    table="categoria_evento",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventcategory",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "categoria_evento_cambio" ("activo", "codigo", "etiqueta", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."activo", OLD."codigo", OLD."etiqueta", OLD."id", OLD."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="0007409e266bc1b52755a0f335c8d0c043e85c2a",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_1e744",
                    table="categoria_evento",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventcategory",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "categoria_evento_cambio" ("activo", "codigo", "etiqueta", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."etiqueta", NEW."id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="0c32e2f71bd4661a524848f1c8220689814998e9",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_6c4d3",
                    table="categoria_evento",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventcategory",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "categoria_evento_cambio" ("activo", "codigo", "etiqueta", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."activo", NEW."codigo", NEW."etiqueta", NEW."id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="4082d7336bfc8dcbcfeb456aed25946b4eac65d7",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_e6848",
                    table="categoria_evento",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="eventcategoryevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_eventcategoryevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="eventcategoryevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_eventcategoryevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="eventcategoryevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_eventcategoryevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="eventcategoryevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_eventcategoryevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="eventcategoryevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_eventcategoryevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="eventcategoryevent",
            index=models.Index(fields=["id"], name="idx_eventcategoryevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="eventcategoryevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="3ab805b3f1862252bbf2e4966e71fb401a25e50e",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_cc9c5",
                    table="categoria_evento_cambio",
                    when="BEFORE",
                ),
            ),
        ),
    ]
