# Generated by Django 6.1 on 2026-10-08 00:14

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.db.models.functions.uuid
import django.db.models.lookups
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apiservices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creada_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        db_column="reserva_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation",
                        to="apiservices.booking",
                    ),
                ),
            ],
            options={
                "db_table": "conversacion",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConversationEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creada_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        db_column="reserva_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiservices.booking",
                    ),
                ),
            ],
            options={
                "db_table": "conversacion_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField(db_column="cuerpo")),
                (
                    "sent_at",
                    models.DateTimeField(
                        db_column="enviado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        db_column="conversacion_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="apimessaging.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        db_column="remitente_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mensaje",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MessageEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField(db_column="cuerpo")),
                (
                    "sent_at",
                    models.DateTimeField(
                        db_column="enviado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        db_column="conversacion_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apimessaging.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        db_column="remitente_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mensaje_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        db_column="leido_hasta",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        db_column="conversacion_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="apimessaging.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conversacion_participante",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParticipantEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        db_column="leido_hasta",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        db_column="conversacion_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apimessaging.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conversacion_participante_cambio",
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="conversation",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="0367def35213a22a488f29fd3ee01e743b34f8d7",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_64cfe",
                    table="conversacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="conversation",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="6e46c52f6bf12228a3dbd9b0e3e52d3f47f70bbb",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_1375b",
                    table="conversacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="conversation",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "conversacion_cambio" ("creada_en", "id", "pgh_context", "pgh_created_at", "pgh_label", "reserva_id") VALUES (OLD."creada_en", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."reserva_id"); RETURN NULL;',
                    hash="8279fb1acb37cfa48fd816f111610b8c783d5fa5",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_0f571",
                    table="conversacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="conversation",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "conversacion_cambio" ("creada_en", "id", "pgh_context", "pgh_created_at", "pgh_label", "reserva_id") VALUES (NEW."creada_en", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."reserva_id"); RETURN NULL;',
                    hash="a6f870926ccb348128ac2285e6fe9d12aa1060f1",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_10a33",
                    table="conversacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="conversation",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "conversacion_cambio" ("creada_en", "id", "pgh_context", "pgh_created_at", "pgh_label", "reserva_id") VALUES (NEW."creada_en", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."reserva_id"); RETURN NULL;',
                    hash="eb1dc8c2090ed95c65ee551c4e216668e6aae5a5",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_9fc2b",
                    table="conversacion",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="conversationevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_conversationevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="conversationevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_conversationevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_conversationevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_conversationevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_conversationevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationevent",
            index=models.Index(fields=["id"], name="idx_conversationevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="conversationevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="fb37e2370b917d0436062bf6c02aa2e4a1ea32a9",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_ae31a",
                    table="conversacion_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "sent_at"], name="idx_mensaje_sala"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.GreaterThan(
                    django.db.models.functions.text.Length("body"), 0
                ),
                name="chk_mensaje_cuerpo_presente",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="3dfbedcebd9925a85c9caf1afc676862d6e7bc62",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_bb1a3",
                    table="mensaje",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="3559fe47c1d5475489da6452729242360abcf134",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_f55ee",
                    table="mensaje",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_mensaje_inmutable",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."cuerpo" IS DISTINCT FROM (NEW."cuerpo") OR OLD."conversacion_id" IS DISTINCT FROM (NEW."conversacion_id") OR OLD."remitente_id" IS DISTINCT FROM (NEW."remitente_id") OR OLD."enviado_en" IS DISTINCT FROM (NEW."enviado_en"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="3f9802d5c81e56b09c324fa09385861554e2084a",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_mensaje_inmutable_66891",
                    table="mensaje",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "mensaje_cambio" ("conversacion_id", "cuerpo", "enviado_en", "id", "pgh_context", "pgh_created_at", "pgh_label", "remitente_id") VALUES (OLD."conversacion_id", OLD."cuerpo", OLD."enviado_en", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."remitente_id"); RETURN NULL;',
                    hash="0cb5af4237ef738c89aa16553692499654ff0a5f",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_680a6",
                    table="mensaje",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "mensaje_cambio" ("conversacion_id", "cuerpo", "enviado_en", "id", "pgh_context", "pgh_created_at", "pgh_label", "remitente_id") VALUES (NEW."conversacion_id", NEW."cuerpo", NEW."enviado_en", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."remitente_id"); RETURN NULL;',
                    hash="52a9e393be9f4b13a61b4308c64afb0e22d22ce8",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_98343",
                    table="mensaje",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="message",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "mensaje_cambio" ("conversacion_id", "cuerpo", "enviado_en", "id", "pgh_context", "pgh_created_at", "pgh_label", "remitente_id") VALUES (NEW."conversacion_id", NEW."cuerpo", NEW."enviado_en", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."remitente_id"); RETURN NULL;',
                    hash="00ffadcf3bd7348de2a5db8838d1f740dd4101e0",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_9e76e",
                    table="mensaje",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="messageevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_messageevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="messageevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_messageevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="messageevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_messageevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="messageevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_messageevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="messageevent",
            index=models.Index(fields=["pgh_label"], name="idx_messageevent_pghlabel"),
        ),
        migrations.AddIndex(
            model_name="messageevent",
            index=models.Index(fields=["id"], name="idx_messageevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="messageevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="efe68a588f20a0fb65eb55d91364997ff5745bbd",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_4cfd3",
                    table="mensaje_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("conversation", "user"), name="unq_conversacionparticipante_par"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="participant",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="5359cfa53c4f25686b68e7ec67e7a97e97a15128",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_9582c",
                    table="conversacion_participante",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="participant",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="2c8b659f722305dacb0a9b52084780fcda1b25e0",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_f4e0a",
                    table="conversacion_participante",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="participant",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "conversacion_participante_cambio" ("conversacion_id", "id", "leido_hasta", "pgh_context", "pgh_created_at", "pgh_label", "usuario_id") VALUES (OLD."conversacion_id", OLD."id", OLD."leido_hasta", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."usuario_id"); RETURN NULL;',
                    hash="68977ded24ab860a79689bd212ad394bda63e0a2",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_11a28",
                    table="conversacion_participante",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="participant",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "conversacion_participante_cambio" ("conversacion_id", "id", "leido_hasta", "pgh_context", "pgh_created_at", "pgh_label", "usuario_id") VALUES (NEW."conversacion_id", NEW."id", NEW."leido_hasta", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."usuario_id"); RETURN NULL;',
                    hash="04f115a9e934cd18e91425bf8a51bb1d3aaa7a84",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_ec8d2",
                    table="conversacion_participante",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="participant",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "conversacion_participante_cambio" ("conversacion_id", "id", "leido_hasta", "pgh_context", "pgh_created_at", "pgh_label", "usuario_id") VALUES (NEW."conversacion_id", NEW."id", NEW."leido_hasta", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."usuario_id"); RETURN NULL;',
                    hash="bdde2574f3555704444a2061781530aafdeac8e9",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_8a5e6",
                    table="conversacion_participante",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="participantevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_participantevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="participantevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_participantevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="participantevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_participantevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="participantevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_participantevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="participantevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_participantevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="participantevent",
            index=models.Index(fields=["id"], name="idx_participantevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="participantevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="b23f89f68aa183919b11a3947ade0cb97f9ad6d1",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_e7bbc",
                    table="conversacion_participante_cambio",
                    when="BEFORE",
                ),
            ),
        ),
    ]
