# Generated by Django 6.1 on 2026-10-08 15:47

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apiagenda", "0001_initial"),
        ("apicatalogs", "0004_agenda_cupones"),
        ("apireputation", "0001_initial"),
        ("apiterritory", "0002_lugares_circuitos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, db_column="nota", db_default="", default=""
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_column="estado",
                        db_default="pendiente",
                        default="pendiente",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        db_column="resuelto_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(
                        blank=True,
                        db_column="nota_resolucion",
                        db_default="",
                        default="",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        db_column="motivo_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="apicatalogs.reason",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        db_column="reportado_por",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        db_column="resuelto_por",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_event",
                    models.ForeignKey(
                        db_column="evento_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="apiagenda.event",
                    ),
                ),
                (
                    "target_point",
                    models.ForeignKey(
                        db_column="punto_interes_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="apiterritory.pointofinterest",
                    ),
                ),
                (
                    "target_review",
                    models.ForeignKey(
                        db_column="resena_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="apireputation.review",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reporte",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReportEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, db_column="nota", db_default="", default=""
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_column="estado",
                        db_default="pendiente",
                        default="pendiente",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        db_column="resuelto_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(
                        blank=True,
                        db_column="nota_resolucion",
                        db_default="",
                        default="",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        db_column="motivo_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apicatalogs.reason",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        db_column="reportado_por",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        db_column="resuelto_por",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_event",
                    models.ForeignKey(
                        db_column="evento_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiagenda.event",
                    ),
                ),
                (
                    "target_point",
                    models.ForeignKey(
                        db_column="punto_interes_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiterritory.pointofinterest",
                    ),
                ),
                (
                    "target_review",
                    models.ForeignKey(
                        db_column="resena_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apireputation.review",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reporte_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sanction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(db_column="tipo", max_length=16)),
                ("reason", models.TextField(db_column="motivo")),
                (
                    "starts_at",
                    models.DateTimeField(
                        db_column="inicia_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        db_column="termina_en", db_default=None, default=None, null=True
                    ),
                ),
                (
                    "lifted_at",
                    models.DateTimeField(
                        db_column="levantada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="impuesta_por",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lifted_by",
                    models.ForeignKey(
                        db_column="levantada_por",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        db_column="reporte_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sanctions",
                        to="apireports.report",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sanctions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sancion",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SanctionEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(db_column="tipo", max_length=16)),
                ("reason", models.TextField(db_column="motivo")),
                (
                    "starts_at",
                    models.DateTimeField(
                        db_column="inicia_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        db_column="termina_en", db_default=None, default=None, null=True
                    ),
                ),
                (
                    "lifted_at",
                    models.DateTimeField(
                        db_column="levantada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="impuesta_por",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lifted_by",
                    models.ForeignKey(
                        db_column="levantada_por",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        db_column="reporte_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apireports.report",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sancion_cambio",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "created_at"], name="idx_reporte_bandeja"
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "status__in",
                    ["pendiente", "atendido", "descartado"],
                )),
                name="chk_reporte_estado",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="report",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="3026acac059685d3c9faa64fd9e36f4ee8d4e98f",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_a50a0",
                    table="reporte",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="report",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="666a15ca30f3625dfced6099e5a348fbf47586fa",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_e0a40",
                    table="reporte",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="report",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "reporte_cambio" ("creado_en", "estado", "evento_id", "id", "motivo_id", "nota", "nota_resolucion", "pgh_context", "pgh_created_at", "pgh_label", "punto_interes_id", "reportado_por", "resena_id", "resuelto_en", "resuelto_por", "usuario_id") VALUES (OLD."creado_en", OLD."estado", OLD."evento_id", OLD."id", OLD."motivo_id", OLD."nota", OLD."nota_resolucion", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."punto_interes_id", OLD."reportado_por", OLD."resena_id", OLD."resuelto_en", OLD."resuelto_por", OLD."usuario_id"); RETURN NULL;',
                    hash="f194766b3387eb18a52affaffe768bf070ce59e7",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_9fbd1",
                    table="reporte",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="report",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "reporte_cambio" ("creado_en", "estado", "evento_id", "id", "motivo_id", "nota", "nota_resolucion", "pgh_context", "pgh_created_at", "pgh_label", "punto_interes_id", "reportado_por", "resena_id", "resuelto_en", "resuelto_por", "usuario_id") VALUES (NEW."creado_en", NEW."estado", NEW."evento_id", NEW."id", NEW."motivo_id", NEW."nota", NEW."nota_resolucion", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."punto_interes_id", NEW."reportado_por", NEW."resena_id", NEW."resuelto_en", NEW."resuelto_por", NEW."usuario_id"); RETURN NULL;',
                    hash="29d2e4a25b665f1fdb8cacedb7010a293eb23f09",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_aa4bd",
                    table="reporte",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="report",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "reporte_cambio" ("creado_en", "estado", "evento_id", "id", "motivo_id", "nota", "nota_resolucion", "pgh_context", "pgh_created_at", "pgh_label", "punto_interes_id", "reportado_por", "resena_id", "resuelto_en", "resuelto_por", "usuario_id") VALUES (NEW."creado_en", NEW."estado", NEW."evento_id", NEW."id", NEW."motivo_id", NEW."nota", NEW."nota_resolucion", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."punto_interes_id", NEW."reportado_por", NEW."resena_id", NEW."resuelto_en", NEW."resuelto_por", NEW."usuario_id"); RETURN NULL;',
                    hash="d81fe44579665f5b601f2663d14fb0da7e20c9a2",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_a29d8",
                    table="reporte",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="reportevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_reportevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="reportevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_reportevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="reportevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_reportevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="reportevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_reportevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="reportevent",
            index=models.Index(fields=["pgh_label"], name="idx_reportevent_pghlabel"),
        ),
        migrations.AddIndex(
            model_name="reportevent",
            index=models.Index(fields=["id"], name="idx_reportevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reportevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="a6f0c28343b1b3ec71c584198a195c3a731cda44",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_356a8",
                    table="reporte_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="sanction",
            index=models.Index(
                fields=["user", "-starts_at"], name="idx_sancion_usuario"
            ),
        ),
        migrations.AddConstraint(
            model_name="sanction",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "kind__in",
                    ["advertencia", "suspension", "expulsion"],
                )),
                name="chk_sancion_tipo",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sanction",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="dba6d1fd8ea52e99392e28bb08efd31a5c71da4f",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_336a9",
                    table="sancion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sanction",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="f3897595f509b52229dd02ebb2f458acfe32428b",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_0ed40",
                    table="sancion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sanction",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "sancion_cambio" ("id", "impuesta_por", "inicia_en", "levantada_en", "levantada_por", "motivo", "pgh_context", "pgh_created_at", "pgh_label", "reporte_id", "termina_en", "tipo", "usuario_id") VALUES (OLD."id", OLD."impuesta_por", OLD."inicia_en", OLD."levantada_en", OLD."levantada_por", OLD."motivo", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."reporte_id", OLD."termina_en", OLD."tipo", OLD."usuario_id"); RETURN NULL;',
                    hash="4d52541e8900143b2c0db592052eead4ae34f7a2",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_299aa",
                    table="sancion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sanction",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "sancion_cambio" ("id", "impuesta_por", "inicia_en", "levantada_en", "levantada_por", "motivo", "pgh_context", "pgh_created_at", "pgh_label", "reporte_id", "termina_en", "tipo", "usuario_id") VALUES (NEW."id", NEW."impuesta_por", NEW."inicia_en", NEW."levantada_en", NEW."levantada_por", NEW."motivo", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."reporte_id", NEW."termina_en", NEW."tipo", NEW."usuario_id"); RETURN NULL;',
                    hash="ed90e3bdee779f9c3f29ce15457fae3b0730a667",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_1dc08",
                    table="sancion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sanction",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "sancion_cambio" ("id", "impuesta_por", "inicia_en", "levantada_en", "levantada_por", "motivo", "pgh_context", "pgh_created_at", "pgh_label", "reporte_id", "termina_en", "tipo", "usuario_id") VALUES (NEW."id", NEW."impuesta_por", NEW."inicia_en", NEW."levantada_en", NEW."levantada_por", NEW."motivo", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."reporte_id", NEW."termina_en", NEW."tipo", NEW."usuario_id"); RETURN NULL;',
                    hash="24fd175c05063e534ccef91251313bc03d2ae225",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_413a1",
                    table="sancion",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="sanctionevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_sanctionevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="sanctionevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_sanctionevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="sanctionevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_sanctionevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="sanctionevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_sanctionevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="sanctionevent",
            index=models.Index(fields=["pgh_label"], name="idx_sanctionevent_pghlabel"),
        ),
        migrations.AddIndex(
            model_name="sanctionevent",
            index=models.Index(fields=["id"], name="idx_sanctionevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sanctionevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="e6f0d564b1f9f6ad6b40781c0ed60859847574a6",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_135f6",
                    table="sancion_cambio",
                    when="BEFORE",
                ),
            ),
        ),
    ]
