# Generated by Django 6.1 on 2026-10-06 17:33

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations, models

import api_utils.db


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apicatalogs", "0001_initial"),
        ("apiterritory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ruc", models.CharField(db_column="ruc", max_length=16)),
                ("name", models.CharField(db_column="nombre", max_length=150)),
                ("address", models.CharField(db_column="direccion", max_length=255)),
                ("phone", models.CharField(db_column="telefono", max_length=30)),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True,
                        db_column="telefono_alterno",
                        db_default="",
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        db_column="latitud", decimal_places=6, max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        db_column="longitud", decimal_places=6, max_digits=9
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        db_column="verificado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "business_type",
                    models.ForeignKey(
                        db_column="tipo_negocio_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="businesses",
                        to="apicatalogs.businesstype",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        db_column="ciudad_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="businesses",
                        to="apiterritory.city",
                    ),
                ),
            ],
            options={
                "db_table": "comercio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BusinessEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("ruc", models.CharField(db_column="ruc", max_length=16)),
                ("name", models.CharField(db_column="nombre", max_length=150)),
                ("address", models.CharField(db_column="direccion", max_length=255)),
                ("phone", models.CharField(db_column="telefono", max_length=30)),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True,
                        db_column="telefono_alterno",
                        db_default="",
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        db_column="latitud", decimal_places=6, max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        db_column="longitud", decimal_places=6, max_digits=9
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        db_column="verificado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "business_type",
                    models.ForeignKey(
                        db_column="tipo_negocio_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apicatalogs.businesstype",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        db_column="ciudad_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiterritory.city",
                    ),
                ),
            ],
            options={
                "db_table": "comercio_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("weekday", models.SmallIntegerField(db_column="dia_semana")),
                (
                    "closed",
                    models.BooleanField(
                        db_column="cerrado", db_default=False, default=False
                    ),
                ),
                (
                    "opens",
                    models.TimeField(
                        db_column="abre", db_default=None, default=None, null=True
                    ),
                ),
                (
                    "closes",
                    models.TimeField(
                        db_column="cierra", db_default=None, default=None, null=True
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        db_column="comercio_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours",
                        to="apiorganizations.business",
                    ),
                ),
            ],
            options={
                "db_table": "comercio_horario",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BusinessHoursEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("weekday", models.SmallIntegerField(db_column="dia_semana")),
                (
                    "closed",
                    models.BooleanField(
                        db_column="cerrado", db_default=False, default=False
                    ),
                ),
                (
                    "opens",
                    models.TimeField(
                        db_column="abre", db_default=None, default=None, null=True
                    ),
                ),
                (
                    "closes",
                    models.TimeField(
                        db_column="cierra", db_default=None, default=None, null=True
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        db_column="comercio_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiorganizations.business",
                    ),
                ),
            ],
            options={
                "db_table": "comercio_horario_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CulturalInstitution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="nombre", max_length=150)),
                (
                    "contact_email",
                    models.EmailField(db_column="correo_contacto", max_length=254),
                ),
                ("phone", models.CharField(db_column="telefono", max_length=30)),
                (
                    "document_key",
                    models.CharField(db_column="documento_id", max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        db_column="verificado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        db_column="ciudad_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="cultural_institutions",
                        to="apiterritory.city",
                    ),
                ),
                (
                    "institution_type",
                    models.ForeignKey(
                        db_column="tipo_institucion_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="cultural_institutions",
                        to="apicatalogs.institutiontype",
                    ),
                ),
            ],
            options={
                "db_table": "institucion_cultural",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CulturalInstitutionEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="nombre", max_length=150)),
                (
                    "contact_email",
                    models.EmailField(db_column="correo_contacto", max_length=254),
                ),
                ("phone", models.CharField(db_column="telefono", max_length=30)),
                (
                    "document_key",
                    models.CharField(db_column="documento_id", max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        db_column="verificado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        db_column="ciudad_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiterritory.city",
                    ),
                ),
                (
                    "institution_type",
                    models.ForeignKey(
                        db_column="tipo_institucion_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apicatalogs.institutiontype",
                    ),
                ),
            ],
            options={
                "db_table": "institucion_cultural_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_key", models.CharField(db_column="archivo_id", max_length=255)),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        db_column="texto_alternativo",
                        db_default="",
                        default="",
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        db_column="orden", db_default=0, default=0
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        db_column="comercio_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="apiorganizations.business",
                    ),
                ),
            ],
            options={
                "db_table": "foto",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PhotoEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("file_key", models.CharField(db_column="archivo_id", max_length=255)),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        db_column="texto_alternativo",
                        db_default="",
                        default="",
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        db_column="orden", db_default=0, default=0
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        db_column="comercio_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiorganizations.business",
                    ),
                ),
            ],
            options={
                "db_table": "foto_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SignatureDish",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="nombre", max_length=150)),
                (
                    "description",
                    models.TextField(
                        blank=True, db_column="descripcion", db_default="", default=""
                    ),
                ),
                (
                    "reference_price",
                    models.DecimalField(
                        db_column="precio_referencia", decimal_places=2, max_digits=12
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        db_column="retirado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        db_column="comercio_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature_dishes",
                        to="apiorganizations.business",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        db_column="moneda_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="apicatalogs.currency",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        db_column="foto_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="apiorganizations.photo",
                    ),
                ),
            ],
            options={
                "db_table": "platillo_estrella",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SignatureDishEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="nombre", max_length=150)),
                (
                    "description",
                    models.TextField(
                        blank=True, db_column="descripcion", db_default="", default=""
                    ),
                ),
                (
                    "reference_price",
                    models.DecimalField(
                        db_column="precio_referencia", decimal_places=2, max_digits=12
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        db_column="retirado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        db_column="comercio_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiorganizations.business",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        db_column="moneda_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apicatalogs.currency",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        db_column="foto_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiorganizations.photo",
                    ),
                ),
            ],
            options={
                "db_table": "platillo_estrella_cambio",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                condition=models.Q(("verified_at__isnull", False)),
                fields=["city"],
                name="idx_comercio_ciudad",
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                condition=models.Q(("verified_at__isnull", True)),
                fields=["created_at"],
                name="idx_comercio_cola",
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=models.Index(
                fields=["latitude", "longitude"], name="idx_comercio_punto"
            ),
        ),
        migrations.AddIndex(
            model_name="business",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.functions.text.Upper(
                        api_utils.db.ImmutableUnaccent("name")
                    ),
                    name="gin_trgm_ops",
                ),
                name="gin_comercio_nombre",
            ),
        ),
        migrations.AddConstraint(
            model_name="business",
            constraint=models.UniqueConstraint(
                fields=("ruc",), name="unq_comercio_ruc"
            ),
        ),
        migrations.AddConstraint(
            model_name="business",
            constraint=models.CheckConstraint(
                condition=models.Q(("ruc__regex", "^[A-Z0-9-]{13,16}$")),
                name="chk_comercio_ruc_formato",
            ),
        ),
        migrations.AddConstraint(
            model_name="business",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", 10.7), ("latitude__lte", 15.1)),
                name="chk_comercio_latitud_rango",
            ),
        ),
        migrations.AddConstraint(
            model_name="business",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("longitude__gte", -87.7), ("longitude__lte", -82.6)
                ),
                name="chk_comercio_longitud_rango",
            ),
        ),
        migrations.AddConstraint(
            model_name="business",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("verified_at__isnull", True),
                    ("verified_at__gte", models.F("created_at")),
                    _connector="OR",
                ),
                name="chk_comercio_verificado_coherente",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="business",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="63033a9269a45df77b2f3249618273891273188c",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_37b11",
                    table="comercio",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="business",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="77299598a7c298ab0476e377dfa8df483a47ad4d",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_2bdd4",
                    table="comercio",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="business",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_comercio_readonly_creadoen",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."creado_en" IS DISTINCT FROM (NEW."creado_en"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="0c43141c125a82e973382bf8627a92f41aad8a82",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_comercio_readonly_creadoen_24ba4",
                    table="comercio",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="business",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_comercio_readonly_ruc",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."verificado_en" IS NOT NULL AND OLD."ruc" IS DISTINCT FROM (NEW."ruc"))',
                    func="RAISE EXCEPTION 'El RUC no se reescribe una vez verificada la ficha.';",
                    hash="c04c9f364243bbcc4afab4b616e5d51aa67eb81a",
                    operation='UPDATE OF "ruc"',
                    pgid="pgtrigger_trg_comercio_readonly_ruc_bf428",
                    table="comercio",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="business",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_comercio_noreverifica",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."verificado_en" IS NULL AND OLD."verificado_en" IS NOT NULL)',
                    func="RAISE EXCEPTION 'La verificación de un comercio no se revierte.';",
                    hash="14efd2bc73bd7528fa78edb4c626886ffa8070f0",
                    operation='UPDATE OF "verificado_en"',
                    pgid="pgtrigger_trg_comercio_noreverifica_382ac",
                    table="comercio",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="business",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comercio_cambio" ("ciudad_id", "creado_en", "direccion", "id", "latitud", "longitud", "nombre", "pgh_context", "pgh_created_at", "pgh_label", "ruc", "telefono", "telefono_alterno", "tipo_negocio_id", "verificado_en") VALUES (OLD."ciudad_id", OLD."creado_en", OLD."direccion", OLD."id", OLD."latitud", OLD."longitud", OLD."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."ruc", OLD."telefono", OLD."telefono_alterno", OLD."tipo_negocio_id", OLD."verificado_en"); RETURN NULL;',
                    hash="521afea974e88c46945b7063daaf0510df9bf052",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_8de0a",
                    table="comercio",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="business",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comercio_cambio" ("ciudad_id", "creado_en", "direccion", "id", "latitud", "longitud", "nombre", "pgh_context", "pgh_created_at", "pgh_label", "ruc", "telefono", "telefono_alterno", "tipo_negocio_id", "verificado_en") VALUES (NEW."ciudad_id", NEW."creado_en", NEW."direccion", NEW."id", NEW."latitud", NEW."longitud", NEW."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."ruc", NEW."telefono", NEW."telefono_alterno", NEW."tipo_negocio_id", NEW."verificado_en"); RETURN NULL;',
                    hash="ec34bcf04ccd11340277041b3619cb60331828bb",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_26479",
                    table="comercio",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="business",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "comercio_cambio" ("ciudad_id", "creado_en", "direccion", "id", "latitud", "longitud", "nombre", "pgh_context", "pgh_created_at", "pgh_label", "ruc", "telefono", "telefono_alterno", "tipo_negocio_id", "verificado_en") VALUES (NEW."ciudad_id", NEW."creado_en", NEW."direccion", NEW."id", NEW."latitud", NEW."longitud", NEW."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."ruc", NEW."telefono", NEW."telefono_alterno", NEW."tipo_negocio_id", NEW."verificado_en"); RETURN NULL;',
                    hash="93d82f3a98a247ccf0715ba68754d804bcf9c67c",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_3f88e",
                    table="comercio",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="businessevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_businessevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="businessevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_businessevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="businessevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_businessevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="businessevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_businessevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="businessevent",
            index=models.Index(fields=["pgh_label"], name="idx_businessevent_pghlabel"),
        ),
        migrations.AddIndex(
            model_name="businessevent",
            index=models.Index(fields=["id"], name="idx_businessevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="businessevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="ce3a5c2f8deb4606312c9a606b2e8d6a9569d6c7",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_8b998",
                    table="comercio_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="businesshours",
            index=models.Index(
                condition=models.Q(("closed", False)),
                fields=["business", "weekday"],
                name="idx_comerciohorario_abierto",
            ),
        ),
        migrations.AddConstraint(
            model_name="businesshours",
            constraint=models.UniqueConstraint(
                fields=("business", "weekday"), name="unq_comerciohorario_dia"
            ),
        ),
        migrations.AddConstraint(
            model_name="businesshours",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                name="chk_comerciohorario_dia_rango",
            ),
        ),
        migrations.AddConstraint(
            model_name="businesshours",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("closed", True),
                        ("closes__isnull", True),
                        ("opens__isnull", True),
                    ),
                    models.Q(
                        ("closed", False),
                        ("closes__isnull", False),
                        ("opens__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="chk_comerciohorario_coherente",
            ),
        ),
        migrations.AddConstraint(
            model_name="businesshours",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closed", True),
                    models.Q(("opens", models.F("closes")), _negated=True),
                    _connector="OR",
                ),
                name="chk_comerciohorario_horas_distintas",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="businesshours",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="f1998ddb7a1297f461c161cce704dfe9495981fa",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_fdcbf",
                    table="comercio_horario",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="businesshours",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="d35de7e2a9d69c47c1e0fa1ab8430f4bc6cdec89",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_d4a7c",
                    table="comercio_horario",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="businesshours",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comercio_horario_cambio" ("abre", "cerrado", "cierra", "comercio_id", "dia_semana", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."abre", OLD."cerrado", OLD."cierra", OLD."comercio_id", OLD."dia_semana", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="dbe2d50016f5107ac6a05db23b3cc56adaa55fb1",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_c91d3",
                    table="comercio_horario",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="businesshours",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "comercio_horario_cambio" ("abre", "cerrado", "cierra", "comercio_id", "dia_semana", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."abre", NEW."cerrado", NEW."cierra", NEW."comercio_id", NEW."dia_semana", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="ac230532738d354e696747dff0a647ebdf28c398",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_b70a9",
                    table="comercio_horario",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="businesshours",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "comercio_horario_cambio" ("abre", "cerrado", "cierra", "comercio_id", "dia_semana", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."abre", NEW."cerrado", NEW."cierra", NEW."comercio_id", NEW."dia_semana", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="408f7487847195f439a3f6197e1a659501638509",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_85b50",
                    table="comercio_horario",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="businesshoursevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_businesshoursevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="businesshoursevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_businesshoursevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="businesshoursevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_businesshoursevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="businesshoursevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_businesshoursevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="businesshoursevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_businesshoursevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="businesshoursevent",
            index=models.Index(fields=["id"], name="idx_businesshoursevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="businesshoursevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="76c3afd26f3b8a9a527d80c2c1a089a1dca5080d",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_a9c71",
                    table="comercio_horario_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="culturalinstitution",
            index=models.Index(fields=["city"], name="idx_institucioncultural_ciudad"),
        ),
        migrations.AddIndex(
            model_name="culturalinstitution",
            index=models.Index(
                condition=models.Q(("verified_at__isnull", True)),
                fields=["created_at"],
                name="idx_institucioncultural_cola",
            ),
        ),
        migrations.AddConstraint(
            model_name="culturalinstitution",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("city"),
                name="unq_institucioncultural_nombre",
            ),
        ),
        migrations.AddConstraint(
            model_name="culturalinstitution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("verified_at__isnull", True),
                    ("verified_at__gte", models.F("created_at")),
                    _connector="OR",
                ),
                name="chk_institucioncultural_verificado_coherente",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="culturalinstitution",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="3decdb811158360773c98c7c1044004b4e4b3869",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_f34da",
                    table="institucion_cultural",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="culturalinstitution",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="eb51069c21b074ad8ba36beaba08db408e7e3035",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_761f9",
                    table="institucion_cultural",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="culturalinstitution",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_institucioncultural_readonly_creadoen",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."creado_en" IS DISTINCT FROM (NEW."creado_en"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="4474c30442313b39026f829ab93fbfbb0532329f",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_institucioncultural_readonly_creadoen_8dbff",
                    table="institucion_cultural",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="culturalinstitution",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_institucioncultural_noreverifica",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."verificado_en" IS NULL AND OLD."verificado_en" IS NOT NULL)',
                    func="RAISE EXCEPTION 'La verificación de una institución no se revierte.';",
                    hash="e3dc0125827ea0b956c73ad5507ac7a3987084df",
                    operation='UPDATE OF "verificado_en"',
                    pgid="pgtrigger_trg_institucioncultural_noreverifica_8379b",
                    table="institucion_cultural",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="culturalinstitution",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "institucion_cultural_cambio" ("ciudad_id", "correo_contacto", "creado_en", "documento_id", "id", "nombre", "pgh_context", "pgh_created_at", "pgh_label", "telefono", "tipo_institucion_id", "verificado_en") VALUES (OLD."ciudad_id", OLD."correo_contacto", OLD."creado_en", OLD."documento_id", OLD."id", OLD."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."telefono", OLD."tipo_institucion_id", OLD."verificado_en"); RETURN NULL;',
                    hash="c447b895e7e485e23895d91305f7354e6e1043bf",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_16cc5",
                    table="institucion_cultural",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="culturalinstitution",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "institucion_cultural_cambio" ("ciudad_id", "correo_contacto", "creado_en", "documento_id", "id", "nombre", "pgh_context", "pgh_created_at", "pgh_label", "telefono", "tipo_institucion_id", "verificado_en") VALUES (NEW."ciudad_id", NEW."correo_contacto", NEW."creado_en", NEW."documento_id", NEW."id", NEW."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."telefono", NEW."tipo_institucion_id", NEW."verificado_en"); RETURN NULL;',
                    hash="c3f2ac17730cba09e853f56c118bba8d4a171751",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_cef53",
                    table="institucion_cultural",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="culturalinstitution",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "institucion_cultural_cambio" ("ciudad_id", "correo_contacto", "creado_en", "documento_id", "id", "nombre", "pgh_context", "pgh_created_at", "pgh_label", "telefono", "tipo_institucion_id", "verificado_en") VALUES (NEW."ciudad_id", NEW."correo_contacto", NEW."creado_en", NEW."documento_id", NEW."id", NEW."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."telefono", NEW."tipo_institucion_id", NEW."verificado_en"); RETURN NULL;',
                    hash="554275792e216cb8f6dc4622bda8be52683ba695",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_0d0c2",
                    table="institucion_cultural",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="culturalinstitutionevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_culturalinstitutionevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="culturalinstitutionevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_culturalinstitutionevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="culturalinstitutionevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_culturalinstitutionevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="culturalinstitutionevent",
            index=models.Index(
                fields=["pgh_created_at"],
                name="idx_culturalinstitutionevent_pghcreatedat",
            ),
        ),
        migrations.AddIndex(
            model_name="culturalinstitutionevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_culturalinstitutionevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="culturalinstitutionevent",
            index=models.Index(fields=["id"], name="idx_culturalinstitutionevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="culturalinstitutionevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="842a791b22ae417eafb966a11d4aef7fab65c153",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_40851",
                    table="institucion_cultural_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.CheckConstraint(
                condition=models.Q(("business__isnull", False)),
                name="chk_foto_dueno_excluyente",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="photo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="7d673052f385b9320ce2d189d72527245b1b2fed",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_6e3df",
                    table="foto",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="photo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="80dca132137530ea428ddf131a3804b85fe45e12",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_5a012",
                    table="foto",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="photo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "foto_cambio" ("archivo_id", "comercio_id", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label", "texto_alternativo") VALUES (OLD."archivo_id", OLD."comercio_id", OLD."id", OLD."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."texto_alternativo"); RETURN NULL;',
                    hash="428d465aa357db9fe45389634b9b47091974b3c5",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_de88d",
                    table="foto",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="photo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "foto_cambio" ("archivo_id", "comercio_id", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label", "texto_alternativo") VALUES (NEW."archivo_id", NEW."comercio_id", NEW."id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."texto_alternativo"); RETURN NULL;',
                    hash="9da9b79980f10268e9a794e404d8c47dbcd73020",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_b27cb",
                    table="foto",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="photo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "foto_cambio" ("archivo_id", "comercio_id", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label", "texto_alternativo") VALUES (NEW."archivo_id", NEW."comercio_id", NEW."id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."texto_alternativo"); RETURN NULL;',
                    hash="1adaa03fb222cb828876a070d29e4a586a3691ff",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_78bc0",
                    table="foto",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="photoevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_photoevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="photoevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_photoevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="photoevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_photoevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="photoevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_photoevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="photoevent",
            index=models.Index(fields=["pgh_label"], name="idx_photoevent_pghlabel"),
        ),
        migrations.AddIndex(
            model_name="photoevent",
            index=models.Index(fields=["id"], name="idx_photoevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="photoevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="b79a32005b9d330a5af2ef96eefa3ee643e66491",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_ea1ec",
                    table="foto_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="signaturedish",
            constraint=models.CheckConstraint(
                condition=models.Q(("reference_price__gt", 0)),
                name="chk_platilloestrella_precio_positivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="signaturedish",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("withdrawn_at__isnull", True),
                    ("withdrawn_at__gte", models.F("created_at")),
                    _connector="OR",
                ),
                name="chk_platilloestrella_retirado_coherente",
            ),
        ),
        migrations.AddConstraint(
            model_name="signaturedish",
            constraint=models.UniqueConstraint(
                condition=models.Q(("withdrawn_at__isnull", True)),
                fields=("business",),
                name="unq_platilloestrella_vigente",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="signaturedish",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="62a35565fbac3bae0bdd11e57abbb90805fa6d9b",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_97959",
                    table="platillo_estrella",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="signaturedish",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="003e6cea9b0c13b63996a8630f6ed6e3bcd0a494",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_476e6",
                    table="platillo_estrella",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="signaturedish",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_platilloestrella_norevive",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."retirado_en" IS NULL AND OLD."retirado_en" IS NOT NULL)',
                    func="RAISE EXCEPTION 'Un platillo retirado no vuelve a ser el vigente.';",
                    hash="eff7875d7b90d565fb5dc558519d56b9786dd149",
                    operation='UPDATE OF "retirado_en"',
                    pgid="pgtrigger_trg_platilloestrella_norevive_f858f",
                    table="platillo_estrella",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="signaturedish",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "platillo_estrella_cambio" ("comercio_id", "creado_en", "descripcion", "foto_id", "id", "moneda_id", "nombre", "pgh_context", "pgh_created_at", "pgh_label", "precio_referencia", "retirado_en") VALUES (OLD."comercio_id", OLD."creado_en", OLD."descripcion", OLD."foto_id", OLD."id", OLD."moneda_id", OLD."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."precio_referencia", OLD."retirado_en"); RETURN NULL;',
                    hash="cc14cb506e16ae0b040885cd394ec778d213d64b",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_80e24",
                    table="platillo_estrella",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="signaturedish",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "platillo_estrella_cambio" ("comercio_id", "creado_en", "descripcion", "foto_id", "id", "moneda_id", "nombre", "pgh_context", "pgh_created_at", "pgh_label", "precio_referencia", "retirado_en") VALUES (NEW."comercio_id", NEW."creado_en", NEW."descripcion", NEW."foto_id", NEW."id", NEW."moneda_id", NEW."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."precio_referencia", NEW."retirado_en"); RETURN NULL;',
                    hash="e0f5e01039413ad02dcd137df4f149cd45c39b44",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_c9b09",
                    table="platillo_estrella",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="signaturedish",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "platillo_estrella_cambio" ("comercio_id", "creado_en", "descripcion", "foto_id", "id", "moneda_id", "nombre", "pgh_context", "pgh_created_at", "pgh_label", "precio_referencia", "retirado_en") VALUES (NEW."comercio_id", NEW."creado_en", NEW."descripcion", NEW."foto_id", NEW."id", NEW."moneda_id", NEW."nombre", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."precio_referencia", NEW."retirado_en"); RETURN NULL;',
                    hash="e4f9d54ce3ffeefb69c0917b28bd567a6d977d17",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_9e48c",
                    table="platillo_estrella",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="signaturedishevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_signaturedishevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="signaturedishevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_signaturedishevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="signaturedishevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_signaturedishevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="signaturedishevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_signaturedishevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="signaturedishevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_signaturedishevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="signaturedishevent",
            index=models.Index(fields=["id"], name="idx_signaturedishevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="signaturedishevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="5abad4f0fcb7fb932b00bf90e53e7b772ff9f096",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_2697a",
                    table="platillo_estrella_cambio",
                    when="BEFORE",
                ),
            ),
        ),
    ]
