# Generated by Django 6.1 on 2026-10-07 22:11

import pgtrigger.migrations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apiorganizations", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="photo",
            name="trg_log_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="photo",
            name="trg_log_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="photo",
            name="trg_log_update",
        ),
        migrations.RemoveConstraint(
            model_name="photo",
            name="chk_foto_dueno_excluyente",
        ),
    ]
