# Generated by Django 6.1 on 2026-10-07 22:11

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apiorganizations", "0002_foto_dueno_preparar"),
        ("apiterritory", "0002_lugares_circuitos"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="circuit",
            field=models.ForeignKey(
                db_column="circuito_id",
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="apiterritory.circuit",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="point",
            field=models.ForeignKey(
                db_column="punto_interes_id",
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="apiterritory.pointofinterest",
            ),
        ),
        migrations.AddField(
            model_name="photoevent",
            name="circuit",
            field=models.ForeignKey(
                db_column="circuito_id",
                db_constraint=False,
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiterritory.circuit",
            ),
        ),
        migrations.AddField(
            model_name="photoevent",
            name="point",
            field=models.ForeignKey(
                db_column="punto_interes_id",
                db_constraint=False,
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiterritory.pointofinterest",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("point__isnull", False)),
                fields=["point", "order"],
                name="idx_foto_lugar",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("circuit__isnull", False)),
                fields=["circuit", "order"],
                name="idx_foto_circuito",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="photo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "foto_cambio" ("archivo_id", "circuito_id", "comercio_id", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label", "punto_interes_id", "texto_alternativo") VALUES (OLD."archivo_id", OLD."circuito_id", OLD."comercio_id", OLD."id", OLD."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."punto_interes_id", OLD."texto_alternativo"); RETURN NULL;',
                    hash="674d67767b5c44d86a0bd9b4ec6723599131bbd3",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_de88d",
                    table="foto",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="photo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "foto_cambio" ("archivo_id", "circuito_id", "comercio_id", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label", "punto_interes_id", "texto_alternativo") VALUES (NEW."archivo_id", NEW."circuito_id", NEW."comercio_id", NEW."id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."punto_interes_id", NEW."texto_alternativo"); RETURN NULL;',
                    hash="dae99bbe47888250743a79f5adab5e5335c9fbae",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_b27cb",
                    table="foto",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="photo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "foto_cambio" ("archivo_id", "circuito_id", "comercio_id", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label", "punto_interes_id", "texto_alternativo") VALUES (NEW."archivo_id", NEW."circuito_id", NEW."comercio_id", NEW."id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."punto_interes_id", NEW."texto_alternativo"); RETURN NULL;',
                    hash="f88c0512fc152d4d98a94b2791501d8eb8ffb931",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_78bc0",
                    table="foto",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("business__isnull", False),
                        ("circuit__isnull", True),
                        ("point__isnull", True),
                    ),
                    models.Q(
                        ("business__isnull", True),
                        ("circuit__isnull", True),
                        ("point__isnull", False),
                    ),
                    models.Q(
                        ("business__isnull", True),
                        ("circuit__isnull", False),
                        ("point__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="chk_foto_dueno_excluyente",
            ),
        ),
    ]
