# Generated by Django 6.1 on 2026-10-07 23:54

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apiagenda", "0001_initial"),
        ("apiorganizations", "0003_foto_lugares_circuitos"),
        ("apiterritory", "0002_lugares_circuitos"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="photo",
            name="trg_log_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="photo",
            name="trg_log_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="photo",
            name="trg_log_update",
        ),
        migrations.RemoveConstraint(
            model_name="photo",
            name="chk_foto_dueno_excluyente",
        ),
        migrations.AddField(
            model_name="photo",
            name="event",
            field=models.ForeignKey(
                db_column="evento_id",
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="apiagenda.event",
            ),
        ),
        migrations.AddField(
            model_name="photoevent",
            name="event",
            field=models.ForeignKey(
                db_column="evento_id",
                db_constraint=False,
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiagenda.event",
            ),
        ),
        migrations.AddIndex(
            model_name="photo",
            index=models.Index(
                condition=models.Q(("event__isnull", False)),
                fields=["event", "order"],
                name="idx_foto_evento",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="photo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "foto_cambio" ("archivo_id", "circuito_id", "comercio_id", "evento_id", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label", "punto_interes_id", "texto_alternativo") VALUES (OLD."archivo_id", OLD."circuito_id", OLD."comercio_id", OLD."evento_id", OLD."id", OLD."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."punto_interes_id", OLD."texto_alternativo"); RETURN NULL;',
                    hash="aa4e2063ae0e36d130e47f8551e71712dea2107b",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_de88d",
                    table="foto",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="photo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "foto_cambio" ("archivo_id", "circuito_id", "comercio_id", "evento_id", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label", "punto_interes_id", "texto_alternativo") VALUES (NEW."archivo_id", NEW."circuito_id", NEW."comercio_id", NEW."evento_id", NEW."id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."punto_interes_id", NEW."texto_alternativo"); RETURN NULL;',
                    hash="653bcaf0e593cc87df8c86ad10f201795bca1c5c",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_b27cb",
                    table="foto",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="photo",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "foto_cambio" ("archivo_id", "circuito_id", "comercio_id", "evento_id", "id", "orden", "pgh_context", "pgh_created_at", "pgh_label", "punto_interes_id", "texto_alternativo") VALUES (NEW."archivo_id", NEW."circuito_id", NEW."comercio_id", NEW."evento_id", NEW."id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."punto_interes_id", NEW."texto_alternativo"); RETURN NULL;',
                    hash="53aecfe7abcf36b28e63e3fb6ce9b0c261d5317c",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_78bc0",
                    table="foto",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("business__isnull", False),
                        ("circuit__isnull", True),
                        ("event__isnull", True),
                        ("point__isnull", True),
                    ),
                    models.Q(
                        ("business__isnull", True),
                        ("circuit__isnull", True),
                        ("event__isnull", True),
                        ("point__isnull", False),
                    ),
                    models.Q(
                        ("business__isnull", True),
                        ("circuit__isnull", False),
                        ("event__isnull", True),
                        ("point__isnull", True),
                    ),
                    models.Q(
                        ("business__isnull", True),
                        ("circuit__isnull", True),
                        ("event__isnull", False),
                        ("point__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="chk_foto_dueno_excluyente",
            ),
        ),
    ]
