# Generated by Django 6.1 on 2026-10-06 17:38

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apiorganizations", "0001_initial"),
        ("apiterritory", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleAssignmentEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        db_column="otorgada_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        db_column="revocada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        db_column="comercio_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiorganizations.business",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        db_column="otorgada_por",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        db_column="institucion_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiorganizations.culturalinstitution",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        db_column="alcaldia_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiterritory.municipality",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="rol_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "asignacion_rol_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        db_column="otorgada_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        db_column="revocada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        db_column="comercio_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="role_assignments",
                        to="apiorganizations.business",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        db_column="otorgada_por",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        db_column="institucion_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="role_assignments",
                        to="apiorganizations.culturalinstitution",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        db_column="alcaldia_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="role_assignments",
                        to="apiterritory.municipality",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="rol_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="assignments",
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "asignacion_rol",
                "abstract": False,
                "indexes": [
                    models.Index(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=["user"],
                        name="idx_asignacionrol_vigentes",
                    ),
                    models.Index(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=["municipality"],
                        name="idx_asignacionrol_alcaldia",
                    ),
                    models.Index(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=["business"],
                        name="idx_asignacionrol_comercio",
                    ),
                    models.Index(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=["institution"],
                        name="idx_asignacionrol_institucion",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("business__isnull", True),
                                ("institution__isnull", True),
                            ),
                            models.Q(
                                ("business__isnull", True),
                                ("municipality__isnull", True),
                            ),
                            models.Q(
                                ("institution__isnull", True),
                                ("municipality__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="chk_asignacionrol_ambito_unico",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("revoked_at__isnull", True),
                            ("revoked_at__gte", models.F("granted_at")),
                            _connector="OR",
                        ),
                        name="chk_asignacionrol_revocada_coherente",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=(
                            "user",
                            "role",
                            "municipality",
                            "business",
                            "institution",
                        ),
                        name="unq_asignacionrol_vigente",
                        nulls_distinct=False,
                    ),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="roleassignment",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="3100ad7be0937dc08911ac64db6c501f276dd5a4",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_fe391",
                    table="asignacion_rol",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="roleassignment",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="1f9db142e374ab1266bb6d18b673c76b2e74b12e",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_1aa2c",
                    table="asignacion_rol",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="roleassignment",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_asignacionrol_ambito_coincide",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    declare="DECLARE required varchar; present varchar;",
                    func="\n                SELECT scope INTO required\n                FROM apiauth_apigroupprofile\n                WHERE group_id = NEW.rol_id;\n\n                IF required IS NULL THEN\n                    RAISE EXCEPTION 'El rol no tiene perfil y no se puede asignar.';\n                END IF;\n\n                IF NEW.alcaldia_id IS NOT NULL THEN\n                    present := 'municipality';\n                ELSIF NEW.comercio_id IS NOT NULL THEN\n                    present := 'business';\n                ELSIF NEW.institucion_id IS NOT NULL THEN\n                    present := 'institution';\n                ELSE\n                    present := 'global';\n                END IF;\n\n                IF present <> required THEN\n                    RAISE EXCEPTION 'El ámbito no es el que exige el rol.';\n                END IF;\n\n                RETURN NEW;\n                ",
                    hash="73cecd0f720e0a47bc47cf8ba00662dfe7534374",
                    operation="INSERT OR UPDATE",
                    pgid="pgtrigger_trg_asignacionrol_ambito_coincide_e5a44",
                    table="asignacion_rol",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="roleassignment",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_asignacionrol_norevive",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."revocada_en" IS NULL AND OLD."revocada_en" IS NOT NULL)',
                    func="RAISE EXCEPTION 'Una asignación revocada no se reactiva.';",
                    hash="99911a41d436e32e7b64eedccc65e90393c7deed",
                    operation='UPDATE OF "revocada_en"',
                    pgid="pgtrigger_trg_asignacionrol_norevive_4ed5d",
                    table="asignacion_rol",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="roleassignment",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_asignacionrol_no_borrar",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot delete rows from % table', TG_TABLE_NAME;",
                    hash="d25ab8b5e574ff63c4deb08b0a1bead7b065c7ea",
                    operation="DELETE",
                    pgid="pgtrigger_trg_asignacionrol_no_borrar_007e7",
                    table="asignacion_rol",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="roleassignment",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "asignacion_rol_cambio" ("alcaldia_id", "comercio_id", "id", "institucion_id", "otorgada_en", "otorgada_por", "pgh_context", "pgh_created_at", "pgh_label", "revocada_en", "rol_id", "usuario_id") VALUES (OLD."alcaldia_id", OLD."comercio_id", OLD."id", OLD."institucion_id", OLD."otorgada_en", OLD."otorgada_por", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."revocada_en", OLD."rol_id", OLD."usuario_id"); RETURN NULL;',
                    hash="2c7d6f747299c9f2d3458902f35d474a7aead361",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_fd8e0",
                    table="asignacion_rol",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="roleassignment",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "asignacion_rol_cambio" ("alcaldia_id", "comercio_id", "id", "institucion_id", "otorgada_en", "otorgada_por", "pgh_context", "pgh_created_at", "pgh_label", "revocada_en", "rol_id", "usuario_id") VALUES (NEW."alcaldia_id", NEW."comercio_id", NEW."id", NEW."institucion_id", NEW."otorgada_en", NEW."otorgada_por", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."revocada_en", NEW."rol_id", NEW."usuario_id"); RETURN NULL;',
                    hash="7e752b10ecd2ecc6d919156a72c50df92ee5ddde",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_a5585",
                    table="asignacion_rol",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="roleassignment",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "asignacion_rol_cambio" ("alcaldia_id", "comercio_id", "id", "institucion_id", "otorgada_en", "otorgada_por", "pgh_context", "pgh_created_at", "pgh_label", "revocada_en", "rol_id", "usuario_id") VALUES (NEW."alcaldia_id", NEW."comercio_id", NEW."id", NEW."institucion_id", NEW."otorgada_en", NEW."otorgada_por", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."revocada_en", NEW."rol_id", NEW."usuario_id"); RETURN NULL;',
                    hash="93cd3ec007aa455391a879a1926ba1e12a8531df",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_6bee6",
                    table="asignacion_rol",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignmentevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_roleassignmentevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignmentevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_roleassignmentevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignmentevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_roleassignmentevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignmentevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_roleassignmentevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignmentevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_roleassignmentevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignmentevent",
            index=models.Index(fields=["id"], name="idx_roleassignmentevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="roleassignmentevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="7f09d32db2caad9eb84e9289bceb195b1409ff17",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_72fb7",
                    table="asignacion_rol_cambio",
                    when="BEFORE",
                ),
            ),
        ),
    ]
