# Generated by Django 6.1 on 2026-10-09 01:14

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppReleaseEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("platform", models.CharField(db_column="plataforma", max_length=16)),
                ("version", models.CharField(db_column="version", max_length=32)),
                (
                    "notes",
                    models.TextField(
                        blank=True, db_column="notas", db_default="", default=""
                    ),
                ),
                ("file_key", models.CharField(db_column="archivo", max_length=200)),
                ("file_size", models.BigIntegerField(db_column="tamano")),
                (
                    "status",
                    models.CharField(
                        db_column="estado",
                        db_default="borrador",
                        default="borrador",
                        max_length=16,
                    ),
                ),
                (
                    "downloads",
                    models.PositiveIntegerField(
                        db_column="descargas", db_default=0, default=0
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        db_column="publicado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        db_column="retirado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="creado_por",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        db_column="publicado_por",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "version_app_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DemoRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="nombre", max_length=120)),
                ("email", models.CharField(db_column="correo", max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_column="telefono",
                        db_default="",
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "organization",
                    models.CharField(db_column="organizacion", max_length=160),
                ),
                ("kind", models.CharField(db_column="tipo", max_length=16)),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        db_column="ciudad",
                        db_default="",
                        default="",
                        max_length=120,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, db_column="mensaje", db_default="", default=""
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_column="estado",
                        db_default="nueva",
                        default="nueva",
                        max_length=16,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, db_column="notas", db_default="", default=""
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_column="actualizado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="actualizado_por",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "solicitud_demo",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DemoRequestEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="nombre", max_length=120)),
                ("email", models.CharField(db_column="correo", max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_column="telefono",
                        db_default="",
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "organization",
                    models.CharField(db_column="organizacion", max_length=160),
                ),
                ("kind", models.CharField(db_column="tipo", max_length=16)),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        db_column="ciudad",
                        db_default="",
                        default="",
                        max_length=120,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, db_column="mensaje", db_default="", default=""
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_column="estado",
                        db_default="nueva",
                        default="nueva",
                        max_length=16,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, db_column="notas", db_default="", default=""
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_column="actualizado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        db_column="actualizado_por",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "solicitud_demo_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AppRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("platform", models.CharField(db_column="plataforma", max_length=16)),
                ("version", models.CharField(db_column="version", max_length=32)),
                (
                    "notes",
                    models.TextField(
                        blank=True, db_column="notas", db_default="", default=""
                    ),
                ),
                ("file_key", models.CharField(db_column="archivo", max_length=200)),
                ("file_size", models.BigIntegerField(db_column="tamano")),
                (
                    "status",
                    models.CharField(
                        db_column="estado",
                        db_default="borrador",
                        default="borrador",
                        max_length=16,
                    ),
                ),
                (
                    "downloads",
                    models.PositiveIntegerField(
                        db_column="descargas", db_default=0, default=0
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        db_column="publicado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        db_column="retirado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="creado_por",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        db_column="publicado_por",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "version_app",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["platform", "status", "-published_at"],
                        name="idx_versionapp_vigente",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q((
                            "platform__in",
                            ["android", "macos", "windows"],
                        )),
                        name="chk_versionapp_plataforma",
                    ),
                    models.CheckConstraint(
                        condition=models.Q((
                            "status__in",
                            ["borrador", "publicada", "retirada"],
                        )),
                        name="chk_versionapp_estado",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("file_size__gt", 0)),
                        name="chk_versionapp_tamano",
                    ),
                    models.UniqueConstraint(
                        fields=("platform", "version"), name="unq_versionapp_version"
                    ),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apprelease",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="58e8d454c9dfe95bce070f5e7f8494b5f69fc302",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_86ca6",
                    table="version_app",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apprelease",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="c322652f21766d90320889900971706ca5a6ff08",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_aafcd",
                    table="version_app",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apprelease",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "version_app_cambio" ("archivo", "creado_en", "creado_por", "descargas", "estado", "id", "notas", "pgh_context", "pgh_created_at", "pgh_label", "plataforma", "publicado_en", "publicado_por", "retirado_en", "tamano", "version") VALUES (OLD."archivo", OLD."creado_en", OLD."creado_por", OLD."descargas", OLD."estado", OLD."id", OLD."notas", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."plataforma", OLD."publicado_en", OLD."publicado_por", OLD."retirado_en", OLD."tamano", OLD."version"); RETURN NULL;',
                    hash="855523c701ef450f6201893be7dff44b586da0ac",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_57c4b",
                    table="version_app",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apprelease",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "version_app_cambio" ("archivo", "creado_en", "creado_por", "descargas", "estado", "id", "notas", "pgh_context", "pgh_created_at", "pgh_label", "plataforma", "publicado_en", "publicado_por", "retirado_en", "tamano", "version") VALUES (NEW."archivo", NEW."creado_en", NEW."creado_por", NEW."descargas", NEW."estado", NEW."id", NEW."notas", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."plataforma", NEW."publicado_en", NEW."publicado_por", NEW."retirado_en", NEW."tamano", NEW."version"); RETURN NULL;',
                    hash="a8d6cc2fb5cb86f0653985d3f259e67f511edc1e",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_6b37b",
                    table="version_app",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="apprelease",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "version_app_cambio" ("archivo", "creado_en", "creado_por", "descargas", "estado", "id", "notas", "pgh_context", "pgh_created_at", "pgh_label", "plataforma", "publicado_en", "publicado_por", "retirado_en", "tamano", "version") VALUES (NEW."archivo", NEW."creado_en", NEW."creado_por", NEW."descargas", NEW."estado", NEW."id", NEW."notas", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."plataforma", NEW."publicado_en", NEW."publicado_por", NEW."retirado_en", NEW."tamano", NEW."version"); RETURN NULL;',
                    hash="abbaf0add7ec30f4eb6c323e8c380b7aacf1895d",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_cfc30",
                    table="version_app",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="appreleaseevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_appreleaseevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="appreleaseevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_appreleaseevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="appreleaseevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_appreleaseevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="appreleaseevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_appreleaseevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="appreleaseevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_appreleaseevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="appreleaseevent",
            index=models.Index(fields=["id"], name="idx_appreleaseevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="appreleaseevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="2e85823c71881fec30daea20fa9ae34dfa7f45d8",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_0e2ef",
                    table="version_app_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="demorequest",
            index=models.Index(
                fields=["status", "-created_at"], name="idx_solicituddemo_bandeja"
            ),
        ),
        migrations.AddIndex(
            model_name="demorequest",
            index=models.Index(fields=["email"], name="idx_solicituddemo_correo"),
        ),
        migrations.AddConstraint(
            model_name="demorequest",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "kind__in",
                    ["comercio", "alcaldia", "institucion", "operador", "otro"],
                )),
                name="chk_solicituddemo_tipo",
            ),
        ),
        migrations.AddConstraint(
            model_name="demorequest",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "status__in",
                    ["nueva", "contactada", "agendada", "realizada", "descartada"],
                )),
                name="chk_solicituddemo_estado",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="demorequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="fb5eb7a43531f783015953b31a4508269f1ad084",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_82011",
                    table="solicitud_demo",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="demorequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="ca2369b2a3a58248d973b76a4caebd8ff9a807ab",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_b9573",
                    table="solicitud_demo",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="demorequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "solicitud_demo_cambio" ("actualizado_en", "actualizado_por", "ciudad", "correo", "creado_en", "estado", "id", "mensaje", "nombre", "notas", "organizacion", "pgh_context", "pgh_created_at", "pgh_label", "telefono", "tipo") VALUES (OLD."actualizado_en", OLD."actualizado_por", OLD."ciudad", OLD."correo", OLD."creado_en", OLD."estado", OLD."id", OLD."mensaje", OLD."nombre", OLD."notas", OLD."organizacion", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."telefono", OLD."tipo"); RETURN NULL;',
                    hash="fc971294f3aef68aaaf981be73c2e7532ca62d12",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_51bdb",
                    table="solicitud_demo",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="demorequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "solicitud_demo_cambio" ("actualizado_en", "actualizado_por", "ciudad", "correo", "creado_en", "estado", "id", "mensaje", "nombre", "notas", "organizacion", "pgh_context", "pgh_created_at", "pgh_label", "telefono", "tipo") VALUES (NEW."actualizado_en", NEW."actualizado_por", NEW."ciudad", NEW."correo", NEW."creado_en", NEW."estado", NEW."id", NEW."mensaje", NEW."nombre", NEW."notas", NEW."organizacion", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."telefono", NEW."tipo"); RETURN NULL;',
                    hash="4a8a573d8ddfdd3d5005c08cb3a8613a3fe98c97",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_01b48",
                    table="solicitud_demo",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="demorequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "solicitud_demo_cambio" ("actualizado_en", "actualizado_por", "ciudad", "correo", "creado_en", "estado", "id", "mensaje", "nombre", "notas", "organizacion", "pgh_context", "pgh_created_at", "pgh_label", "telefono", "tipo") VALUES (NEW."actualizado_en", NEW."actualizado_por", NEW."ciudad", NEW."correo", NEW."creado_en", NEW."estado", NEW."id", NEW."mensaje", NEW."nombre", NEW."notas", NEW."organizacion", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."telefono", NEW."tipo"); RETURN NULL;',
                    hash="eb7db4eedfaf9fcce27e0714a0e9146423c7aa27",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_fbd71",
                    table="solicitud_demo",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="demorequestevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_demorequestevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="demorequestevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_demorequestevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="demorequestevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_demorequestevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="demorequestevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_demorequestevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="demorequestevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_demorequestevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="demorequestevent",
            index=models.Index(fields=["id"], name="idx_demorequestevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="demorequestevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="bf3325dfed5aaeaf68704d964c86b194b2fedf82",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_0b070",
                    table="solicitud_demo_cambio",
                    when="BEFORE",
                ),
            ),
        ),
    ]
