# Generated by Django 6.1 on 2026-10-08 15:47

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceTokenEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("platform", models.CharField(db_column="plataforma", max_length=16)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        db_column="visto_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "token_notificacion_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(db_column="tipo", max_length=40)),
                ("title", models.CharField(db_column="titulo", max_length=120)),
                ("body", models.TextField(db_column="cuerpo")),
                (
                    "data",
                    models.JSONField(db_column="datos", db_default={}, default=dict),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        db_column="leido_en", db_default=None, default=None, null=True
                    ),
                ),
                (
                    "push_status",
                    models.CharField(
                        db_column="estado_push",
                        db_default="omitido",
                        default="omitido",
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "aviso_emitido",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(db_column="tipo", max_length=40)),
                ("title", models.CharField(db_column="titulo", max_length=120)),
                ("body", models.TextField(db_column="cuerpo")),
                (
                    "data",
                    models.JSONField(db_column="datos", db_default={}, default=dict),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        db_column="leido_en", db_default=None, default=None, null=True
                    ),
                ),
                (
                    "push_status",
                    models.CharField(
                        db_column="estado_push",
                        db_default="omitido",
                        default="omitido",
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "aviso_emitido_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(db_column="tipo", max_length=40)),
                (
                    "push_enabled",
                    models.BooleanField(
                        db_column="push_activo", db_default=True, default=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "preferencia_aviso",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationPreferenceEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(db_column="tipo", max_length=40)),
                (
                    "push_enabled",
                    models.BooleanField(
                        db_column="push_activo", db_default=True, default=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "preferencia_aviso_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(db_column="token", max_length=500)),
                ("platform", models.CharField(db_column="plataforma", max_length=16)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        db_column="visto_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "token_notificacion",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("token",), name="unq_tokennotificacion_token"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("platform__in", ["android", "ios", "web"])),
                        name="chk_tokennotificacion_plataforma",
                    ),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="devicetoken",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="697f618921f0acb2135c7b7c94ecace2d8b5d581",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_0d540",
                    table="token_notificacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="devicetoken",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="259195837844efcec1118d6850f543facd258d8e",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_48e0a",
                    table="token_notificacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="devicetoken",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "token_notificacion_cambio" ("creado_en", "id", "pgh_context", "pgh_created_at", "pgh_label", "plataforma", "usuario_id", "visto_en") VALUES (OLD."creado_en", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."plataforma", OLD."usuario_id", OLD."visto_en"); RETURN NULL;',
                    hash="4cc5324e836c607d5555b20e1062caed2b1aa098",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_999f9",
                    table="token_notificacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="devicetoken",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "token_notificacion_cambio" ("creado_en", "id", "pgh_context", "pgh_created_at", "pgh_label", "plataforma", "usuario_id", "visto_en") VALUES (NEW."creado_en", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."plataforma", NEW."usuario_id", NEW."visto_en"); RETURN NULL;',
                    hash="09a7102710566c2cdc13db7751e4374d5a5e03a0",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_1b20e",
                    table="token_notificacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="devicetoken",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."creado_en" IS DISTINCT FROM (NEW."creado_en") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."visto_en" IS DISTINCT FROM (NEW."visto_en") OR OLD."plataforma" IS DISTINCT FROM (NEW."plataforma") OR OLD."usuario_id" IS DISTINCT FROM (NEW."usuario_id"))',
                    func='INSERT INTO "token_notificacion_cambio" ("creado_en", "id", "pgh_context", "pgh_created_at", "pgh_label", "plataforma", "usuario_id", "visto_en") VALUES (NEW."creado_en", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."plataforma", NEW."usuario_id", NEW."visto_en"); RETURN NULL;',
                    hash="5e7ad41c89ac8ae06bc3dee932191f3171c689dd",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_1a831",
                    table="token_notificacion",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="devicetokenevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_devicetokenevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="devicetokenevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_devicetokenevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="devicetokenevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_devicetokenevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="devicetokenevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_devicetokenevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="devicetokenevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_devicetokenevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="devicetokenevent",
            index=models.Index(fields=["id"], name="idx_devicetokenevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="devicetokenevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="44130376a39644aa237c81d0a815762a2a4e8035",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_687b7",
                    table="token_notificacion_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_avisoemitido_bandeja"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "push_status__in",
                    ["omitido", "enviado", "fallido"],
                )),
                name="chk_avisoemitido_estadopush",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notification",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="c021056f27c76fee8f27ec63635c13351abda877",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_c951e",
                    table="aviso_emitido",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notification",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="2e18618a527f96c78ca14eaae1e2e704e8a466d3",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_7ac1f",
                    table="aviso_emitido",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notification",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "aviso_emitido_cambio" ("creado_en", "cuerpo", "datos", "estado_push", "id", "leido_en", "pgh_context", "pgh_created_at", "pgh_label", "tipo", "titulo", "usuario_id") VALUES (OLD."creado_en", OLD."cuerpo", OLD."datos", OLD."estado_push", OLD."id", OLD."leido_en", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."tipo", OLD."titulo", OLD."usuario_id"); RETURN NULL;',
                    hash="7861b87c745d06e99c066ffe98fd92cc559f3f66",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_ed31c",
                    table="aviso_emitido",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notification",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "aviso_emitido_cambio" ("creado_en", "cuerpo", "datos", "estado_push", "id", "leido_en", "pgh_context", "pgh_created_at", "pgh_label", "tipo", "titulo", "usuario_id") VALUES (NEW."creado_en", NEW."cuerpo", NEW."datos", NEW."estado_push", NEW."id", NEW."leido_en", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."tipo", NEW."titulo", NEW."usuario_id"); RETURN NULL;',
                    hash="b44de706ba1f2f4ecbcaddad5c047724c8afcff6",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_ee670",
                    table="aviso_emitido",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notification",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "aviso_emitido_cambio" ("creado_en", "cuerpo", "datos", "estado_push", "id", "leido_en", "pgh_context", "pgh_created_at", "pgh_label", "tipo", "titulo", "usuario_id") VALUES (NEW."creado_en", NEW."cuerpo", NEW."datos", NEW."estado_push", NEW."id", NEW."leido_en", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."tipo", NEW."titulo", NEW."usuario_id"); RETURN NULL;',
                    hash="2be805b5464c3df67b3ac8af0a6ab7ef451b5597",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_60422",
                    table="aviso_emitido",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_notificationevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_notificationevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_notificationevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_notificationevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_notificationevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(fields=["id"], name="idx_notificationevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notificationevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="76793ab543070edae61c588911627fedda0bb0fe",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_de71c",
                    table="aviso_emitido_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "kind"), name="unq_preferenciaaviso_tipo"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notificationpreference",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="20762d668fc090537a7a211415238e0ef51ce867",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_71c8e",
                    table="preferencia_aviso",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notificationpreference",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="e9fa11ef63cbdeb824c4361d76dd22b208765d16",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_ec49c",
                    table="preferencia_aviso",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notificationpreference",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "preferencia_aviso_cambio" ("id", "pgh_context", "pgh_created_at", "pgh_label", "push_activo", "tipo", "usuario_id") VALUES (OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."push_activo", OLD."tipo", OLD."usuario_id"); RETURN NULL;',
                    hash="1e68d6f4c30c6b038cca6fe14f898e710cd7b50a",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_03b84",
                    table="preferencia_aviso",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notificationpreference",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "preferencia_aviso_cambio" ("id", "pgh_context", "pgh_created_at", "pgh_label", "push_activo", "tipo", "usuario_id") VALUES (NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."push_activo", NEW."tipo", NEW."usuario_id"); RETURN NULL;',
                    hash="36ab0b6b4ed907266bbd83c959a650ffc5db51e0",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_8a7a0",
                    table="preferencia_aviso",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notificationpreference",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "preferencia_aviso_cambio" ("id", "pgh_context", "pgh_created_at", "pgh_label", "push_activo", "tipo", "usuario_id") VALUES (NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."push_activo", NEW."tipo", NEW."usuario_id"); RETURN NULL;',
                    hash="b149e9308cc188bde16a4a6321da775f10c281a7",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_29119",
                    table="preferencia_aviso",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreferenceevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_notificationpreferenceevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreferenceevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_notificationpreferenceevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreferenceevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_notificationpreferenceevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreferenceevent",
            index=models.Index(
                fields=["pgh_created_at"],
                name="idx_notificationpreferenceevent_pghcreatedat",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreferenceevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_notificationpreferenceevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreferenceevent",
            index=models.Index(
                fields=["id"], name="idx_notificationpreferenceevent_id"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="notificationpreferenceevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="497922ac6b8fa4927b335bf98e7add4bf17dacd8",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_b6d01",
                    table="preferencia_aviso_cambio",
                    when="BEFORE",
                ),
            ),
        ),
    ]
