# Generated by Django 6.1 on 2026-10-08 00:14

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apiitineraries", "0001_initial"),
        ("apiprofiles", "0001_initial"),
        ("apiterritory", "0002_lugares_circuitos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingStatusEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=24)),
                ("label", models.CharField(db_column="etiqueta", max_length=60)),
                (
                    "allows_cancellation",
                    models.BooleanField(db_column="admite_cancelacion"),
                ),
                ("is_terminal", models.BooleanField(db_column="es_terminal")),
            ],
            options={
                "db_table": "estado_reserva_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GuidedDeparture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_column="fecha")),
                ("start_time", models.TimeField(db_column="hora_salida")),
                ("capacity", models.SmallIntegerField(db_column="cupos")),
                (
                    "exclusive",
                    models.BooleanField(
                        db_column="exclusiva", db_default=False, default=False
                    ),
                ),
                (
                    "transport_included",
                    models.BooleanField(
                        db_column="incluye_transporte", db_default=False, default=False
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        db_column="nota",
                        db_default="",
                        default="",
                        max_length=500,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        db_column="cancelada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        db_column="motivo_cancelacion",
                        db_default="",
                        default="",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "db_table": "salida_guiada",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GuidedDepartureEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_column="fecha")),
                ("start_time", models.TimeField(db_column="hora_salida")),
                ("capacity", models.SmallIntegerField(db_column="cupos")),
                (
                    "exclusive",
                    models.BooleanField(
                        db_column="exclusiva", db_default=False, default=False
                    ),
                ),
                (
                    "transport_included",
                    models.BooleanField(
                        db_column="incluye_transporte", db_default=False, default=False
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        db_column="nota",
                        db_default="",
                        default="",
                        max_length=500,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        db_column="cancelada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        db_column="motivo_cancelacion",
                        db_default="",
                        default="",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "db_table": "salida_guiada_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RequestStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=24)),
                ("label", models.CharField(db_column="etiqueta", max_length=60)),
                (
                    "accepts_applications",
                    models.BooleanField(db_column="admite_postulaciones"),
                ),
                ("is_terminal", models.BooleanField(db_column="es_terminal")),
            ],
            options={
                "db_table": "estado_convocatoria",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RequestStatusEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=24)),
                ("label", models.CharField(db_column="etiqueta", max_length=60)),
                (
                    "accepts_applications",
                    models.BooleanField(db_column="admite_postulaciones"),
                ),
                ("is_terminal", models.BooleanField(db_column="es_terminal")),
            ],
            options={
                "db_table": "estado_convocatoria_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_column="fecha")),
                ("start_time", models.TimeField(db_column="hora_inicio")),
                (
                    "adults",
                    models.SmallIntegerField(
                        db_column="adultos", db_default=1, default=1
                    ),
                ),
                (
                    "children",
                    models.SmallIntegerField(
                        db_column="ninos", db_default=0, default=0
                    ),
                ),
                (
                    "max_fee",
                    models.IntegerField(
                        db_column="tarifa_maxima",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, db_column="nota", db_default="", default=""
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        db_column="cerrada_en", db_default=None, default=None, null=True
                    ),
                ),
            ],
            options={
                "db_table": "convocatoria",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceRequestEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_column="fecha")),
                ("start_time", models.TimeField(db_column="hora_inicio")),
                (
                    "adults",
                    models.SmallIntegerField(
                        db_column="adultos", db_default=1, default=1
                    ),
                ),
                (
                    "children",
                    models.SmallIntegerField(
                        db_column="ninos", db_default=0, default=0
                    ),
                ),
                (
                    "max_fee",
                    models.IntegerField(
                        db_column="tarifa_maxima",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, db_column="nota", db_default="", default=""
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        db_column="cerrada_en", db_default=None, default=None, null=True
                    ),
                ),
            ],
            options={
                "db_table": "convocatoria_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fee", models.IntegerField(db_column="tarifa")),
                (
                    "message",
                    models.TextField(
                        blank=True, db_column="mensaje", db_default="", default=""
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_column="estado",
                        db_default="enviada",
                        default="enviada",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        db_column="perfil_prestador_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="applications",
                        to="apiprofiles.providerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "postulacion",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApplicationEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("fee", models.IntegerField(db_column="tarifa")),
                (
                    "message",
                    models.TextField(
                        blank=True, db_column="mensaje", db_default="", default=""
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_column="estado",
                        db_default="enviada",
                        default="enviada",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        db_column="perfil_prestador_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiprofiles.providerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "postulacion_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BookingStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=24)),
                ("label", models.CharField(db_column="etiqueta", max_length=60)),
                (
                    "allows_cancellation",
                    models.BooleanField(db_column="admite_cancelacion"),
                ),
                ("is_terminal", models.BooleanField(db_column="es_terminal")),
            ],
            options={
                "db_table": "estado_reserva",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",), name="unq_estadoreserva_codigo"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BookingEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_column="fecha")),
                ("start_time", models.TimeField(db_column="hora_inicio")),
                (
                    "adults",
                    models.SmallIntegerField(
                        db_column="adultos", db_default=1, default=1
                    ),
                ),
                (
                    "children",
                    models.SmallIntegerField(
                        db_column="ninos", db_default=0, default=0
                    ),
                ),
                ("amount", models.IntegerField(db_column="monto")),
                (
                    "payment_status",
                    models.CharField(
                        db_column="estado_pago",
                        db_default="sin_cobro",
                        default="sin_cobro",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_column="iniciada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        db_column="prestada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        db_column="cancelada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        db_column="motivo_cancelacion",
                        db_default="",
                        default="",
                        max_length=500,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        db_column="postulacion_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiservices.application",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        db_column="cancelada_por",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "circuit",
                    models.ForeignKey(
                        db_column="circuito_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiterritory.circuit",
                    ),
                ),
                (
                    "itinerary",
                    models.ForeignKey(
                        db_column="itinerario_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiitineraries.itinerary",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        db_column="perfil_prestador_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiprofiles.providerprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        db_column="estado_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiservices.bookingstatus",
                    ),
                ),
            ],
            options={
                "db_table": "reserva_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_column="fecha")),
                ("start_time", models.TimeField(db_column="hora_inicio")),
                (
                    "adults",
                    models.SmallIntegerField(
                        db_column="adultos", db_default=1, default=1
                    ),
                ),
                (
                    "children",
                    models.SmallIntegerField(
                        db_column="ninos", db_default=0, default=0
                    ),
                ),
                ("amount", models.IntegerField(db_column="monto")),
                (
                    "payment_status",
                    models.CharField(
                        db_column="estado_pago",
                        db_default="sin_cobro",
                        default="sin_cobro",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_column="iniciada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        db_column="prestada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        db_column="cancelada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        db_column="motivo_cancelacion",
                        db_default="",
                        default="",
                        max_length=500,
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        db_column="postulacion_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="booking",
                        to="apiservices.application",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        db_column="cancelada_por",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "circuit",
                    models.ForeignKey(
                        db_column="circuito_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bookings",
                        to="apiterritory.circuit",
                    ),
                ),
                (
                    "itinerary",
                    models.ForeignKey(
                        db_column="itinerario_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bookings",
                        to="apiitineraries.itinerary",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        db_column="perfil_prestador_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bookings",
                        to="apiprofiles.providerprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        db_column="estado_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bookings",
                        to="apiservices.bookingstatus",
                    ),
                ),
            ],
            options={
                "db_table": "reserva",
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bookingstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="5dbd435bc610da59ab62308b723109746cc8dd9c",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_758c5",
                    table="estado_reserva",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bookingstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="28b10a1bb377b5c5f3d56006fdec0302fec37477",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_b8b47",
                    table="estado_reserva",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bookingstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estado_reserva_cambio" ("admite_cancelacion", "codigo", "es_terminal", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."admite_cancelacion", OLD."codigo", OLD."es_terminal", OLD."etiqueta", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="8ecc02cde8ec7ec7d5879649957f81c99073ee75",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_7e515",
                    table="estado_reserva",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bookingstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estado_reserva_cambio" ("admite_cancelacion", "codigo", "es_terminal", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."admite_cancelacion", NEW."codigo", NEW."es_terminal", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="7389f92371418378f81973a08390cf5f7db985ef",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_a47a8",
                    table="estado_reserva",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bookingstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "estado_reserva_cambio" ("admite_cancelacion", "codigo", "es_terminal", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."admite_cancelacion", NEW."codigo", NEW."es_terminal", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="a3115c5d1339de55816a6026a0276e6f93e6a9ef",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_bdb7d",
                    table="estado_reserva",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="bookingstatusevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_bookingstatusevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="bookingstatusevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_bookingstatusevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingstatusevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_bookingstatusevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingstatusevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_bookingstatusevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingstatusevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_bookingstatusevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingstatusevent",
            index=models.Index(fields=["id"], name="idx_bookingstatusevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bookingstatusevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="059a323a560efab477309d281a5a1383f71932bb",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_ef065",
                    table="estado_reserva_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddField(
            model_name="guideddeparture",
            name="circuit",
            field=models.ForeignKey(
                db_column="circuito_id",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="departures",
                to="apiterritory.circuit",
            ),
        ),
        migrations.AddField(
            model_name="guideddeparture",
            name="provider",
            field=models.ForeignKey(
                db_column="perfil_prestador_id",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="departures",
                to="apiprofiles.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="bookingevent",
            name="departure",
            field=models.ForeignKey(
                db_column="salida_guiada_id",
                db_constraint=False,
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiservices.guideddeparture",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="departure",
            field=models.ForeignKey(
                db_column="salida_guiada_id",
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="bookings",
                to="apiservices.guideddeparture",
            ),
        ),
        migrations.AddField(
            model_name="guideddepartureevent",
            name="circuit",
            field=models.ForeignKey(
                db_column="circuito_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiterritory.circuit",
            ),
        ),
        migrations.AddField(
            model_name="guideddepartureevent",
            name="provider",
            field=models.ForeignKey(
                db_column="perfil_prestador_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiprofiles.providerprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="requeststatus",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unq_estadoconvocatoria_codigo"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="requeststatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="98245a267e3e0ddad3ec235e44cfb51fa3219e0e",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_a4546",
                    table="estado_convocatoria",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="requeststatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="0af8ae9bbea44ad84f34b9827c4360b08c024735",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_72270",
                    table="estado_convocatoria",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="requeststatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estado_convocatoria_cambio" ("admite_postulaciones", "codigo", "es_terminal", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."admite_postulaciones", OLD."codigo", OLD."es_terminal", OLD."etiqueta", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="ab0651a1c11127a4c8eda225a5353f9cca42efba",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_2713c",
                    table="estado_convocatoria",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="requeststatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estado_convocatoria_cambio" ("admite_postulaciones", "codigo", "es_terminal", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."admite_postulaciones", NEW."codigo", NEW."es_terminal", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="ecef29ad204ab1ef9d04a13e955f0aa8a34b6929",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_b091a",
                    table="estado_convocatoria",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="requeststatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "estado_convocatoria_cambio" ("admite_postulaciones", "codigo", "es_terminal", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."admite_postulaciones", NEW."codigo", NEW."es_terminal", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="b10ec14bf8b3e071f40510891f14f2379832d3c3",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_ac15f",
                    table="estado_convocatoria",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="requeststatusevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_requeststatusevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="requeststatusevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_requeststatusevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="requeststatusevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_requeststatusevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="requeststatusevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_requeststatusevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="requeststatusevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_requeststatusevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="requeststatusevent",
            index=models.Index(fields=["id"], name="idx_requeststatusevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="requeststatusevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="f807c686871ecf49882d943f76bb5661a1f038fd",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_44b31",
                    table="estado_convocatoria_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="city",
            field=models.ForeignKey(
                db_column="ciudad_id",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="service_requests",
                to="apiterritory.city",
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="itinerary",
            field=models.ForeignKey(
                db_column="itinerario_id",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="service_requests",
                to="apiitineraries.itinerary",
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="status",
            field=models.ForeignKey(
                db_column="estado_id",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="requests",
                to="apiservices.requeststatus",
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="user",
            field=models.ForeignKey(
                db_column="usuario_id",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="service_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="applicationevent",
            name="request",
            field=models.ForeignKey(
                db_column="convocatoria_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiservices.servicerequest",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="request",
            field=models.ForeignKey(
                db_column="convocatoria_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="apiservices.servicerequest",
            ),
        ),
        migrations.AddField(
            model_name="servicerequestevent",
            name="city",
            field=models.ForeignKey(
                db_column="ciudad_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiterritory.city",
            ),
        ),
        migrations.AddField(
            model_name="servicerequestevent",
            name="itinerary",
            field=models.ForeignKey(
                db_column="itinerario_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiitineraries.itinerary",
            ),
        ),
        migrations.AddField(
            model_name="servicerequestevent",
            name="status",
            field=models.ForeignKey(
                db_column="estado_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiservices.requeststatus",
            ),
        ),
        migrations.AddField(
            model_name="servicerequestevent",
            name="user",
            field=models.ForeignKey(
                db_column="usuario_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="guideddeparture",
            index=models.Index(
                condition=models.Q(("cancelled_at__isnull", True)),
                fields=["circuit", "date"],
                name="idx_salidaguiada_circuito",
            ),
        ),
        migrations.AddConstraint(
            model_name="guideddeparture",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gte", 1), ("capacity__lte", 50)),
                name="chk_salidaguiada_cupos_rango",
            ),
        ),
        migrations.AddConstraint(
            model_name="guideddeparture",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cancelled_at__isnull", True)),
                fields=("provider", "date", "start_time"),
                name="unq_salidaguiada_guia_hora",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="guideddeparture",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="497ed42b0138c5133b3d8da345e4b18d64203b3b",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_9ed36",
                    table="salida_guiada",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="guideddeparture",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="091166532c6c32401b7692120a86a583fc3d4a60",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_b1139",
                    table="salida_guiada",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="guideddeparture",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_salidaguiada_readonly_creadoen",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."creado_en" IS DISTINCT FROM (NEW."creado_en"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="5f08b22f75cf35822d9caebb8883829922ac55a5",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_salidaguiada_readonly_creadoen_6d476",
                    table="salida_guiada",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="guideddeparture",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "salida_guiada_cambio" ("cancelada_en", "circuito_id", "creado_en", "cupos", "exclusiva", "fecha", "hora_salida", "id", "incluye_transporte", "motivo_cancelacion", "nota", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."cancelada_en", OLD."circuito_id", OLD."creado_en", OLD."cupos", OLD."exclusiva", OLD."fecha", OLD."hora_salida", OLD."id", OLD."incluye_transporte", OLD."motivo_cancelacion", OLD."nota", OLD."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="3555e533c570a71c20ab68f0a4140b9e35d70369",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_04ee3",
                    table="salida_guiada",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="guideddeparture",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "salida_guiada_cambio" ("cancelada_en", "circuito_id", "creado_en", "cupos", "exclusiva", "fecha", "hora_salida", "id", "incluye_transporte", "motivo_cancelacion", "nota", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."cancelada_en", NEW."circuito_id", NEW."creado_en", NEW."cupos", NEW."exclusiva", NEW."fecha", NEW."hora_salida", NEW."id", NEW."incluye_transporte", NEW."motivo_cancelacion", NEW."nota", NEW."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="4397b19d90220aa5fcfed6d19ed283b9278837c0",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_daace",
                    table="salida_guiada",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="guideddeparture",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "salida_guiada_cambio" ("cancelada_en", "circuito_id", "creado_en", "cupos", "exclusiva", "fecha", "hora_salida", "id", "incluye_transporte", "motivo_cancelacion", "nota", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."cancelada_en", NEW."circuito_id", NEW."creado_en", NEW."cupos", NEW."exclusiva", NEW."fecha", NEW."hora_salida", NEW."id", NEW."incluye_transporte", NEW."motivo_cancelacion", NEW."nota", NEW."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="b2ce7ac6e688e23286532174ea94daa1c1d4fdbc",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_ca404",
                    table="salida_guiada",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_bookingevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_bookingevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_bookingevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_bookingevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=models.Index(fields=["pgh_label"], name="idx_bookingevent_pghlabel"),
        ),
        migrations.AddIndex(
            model_name="bookingevent",
            index=models.Index(fields=["id"], name="idx_bookingevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bookingevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="f0671cf7fc8d01fe5ec55263ea564800d2a8e36f",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_ec25e",
                    table="reserva_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["user", "-date"], name="idx_reserva_turista"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["provider", "date"], name="idx_reserva_prestador"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("application__isnull", True), ("departure__isnull", False)
                    ),
                    models.Q(
                        ("application__isnull", False), ("departure__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="chk_reserva_origen_excluyente",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("circuit__isnull", False),
                    ("itinerary__isnull", False),
                    _connector="OR",
                ),
                name="chk_reserva_recorrido_presente",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("adults__gte", 1), ("children__gte", 0)),
                name="chk_reserva_grupo_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="chk_reserva_monto_positivo",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="booking",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="a908102cef9924b6d208022c419932da1b09e15b",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_67c44",
                    table="reserva",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="booking",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="c3043ffb1511ab36179a12f4ddcc13a2329e7c0e",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_debec",
                    table="reserva",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="booking",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_reserva_readonly_acuerdo",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."monto" IS DISTINCT FROM (NEW."monto") OR OLD."creado_en" IS DISTINCT FROM (NEW."creado_en") OR OLD."salida_guiada_id" IS DISTINCT FROM (NEW."salida_guiada_id") OR OLD."postulacion_id" IS DISTINCT FROM (NEW."postulacion_id") OR OLD."usuario_id" IS DISTINCT FROM (NEW."usuario_id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="20bd6590a0fd8fe45e13b6ae6f577a091d4cb4c1",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_reserva_readonly_acuerdo_aed78",
                    table="reserva",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="booking",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "reserva_cambio" ("adultos", "cancelada_en", "cancelada_por", "circuito_id", "creado_en", "estado_id", "estado_pago", "fecha", "hora_inicio", "id", "iniciada_en", "itinerario_id", "monto", "motivo_cancelacion", "ninos", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label", "postulacion_id", "prestada_en", "salida_guiada_id", "usuario_id") VALUES (OLD."adultos", OLD."cancelada_en", OLD."cancelada_por", OLD."circuito_id", OLD."creado_en", OLD."estado_id", OLD."estado_pago", OLD."fecha", OLD."hora_inicio", OLD."id", OLD."iniciada_en", OLD."itinerario_id", OLD."monto", OLD."motivo_cancelacion", OLD."ninos", OLD."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."postulacion_id", OLD."prestada_en", OLD."salida_guiada_id", OLD."usuario_id"); RETURN NULL;',
                    hash="8aae8539f8fca663bf14843d5e99c373d6d4a2dc",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_08cdf",
                    table="reserva",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="booking",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "reserva_cambio" ("adultos", "cancelada_en", "cancelada_por", "circuito_id", "creado_en", "estado_id", "estado_pago", "fecha", "hora_inicio", "id", "iniciada_en", "itinerario_id", "monto", "motivo_cancelacion", "ninos", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label", "postulacion_id", "prestada_en", "salida_guiada_id", "usuario_id") VALUES (NEW."adultos", NEW."cancelada_en", NEW."cancelada_por", NEW."circuito_id", NEW."creado_en", NEW."estado_id", NEW."estado_pago", NEW."fecha", NEW."hora_inicio", NEW."id", NEW."iniciada_en", NEW."itinerario_id", NEW."monto", NEW."motivo_cancelacion", NEW."ninos", NEW."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."postulacion_id", NEW."prestada_en", NEW."salida_guiada_id", NEW."usuario_id"); RETURN NULL;',
                    hash="a3da8ab75c1082c04a975c817053a0041239a404",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_ead5e",
                    table="reserva",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="booking",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "reserva_cambio" ("adultos", "cancelada_en", "cancelada_por", "circuito_id", "creado_en", "estado_id", "estado_pago", "fecha", "hora_inicio", "id", "iniciada_en", "itinerario_id", "monto", "motivo_cancelacion", "ninos", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label", "postulacion_id", "prestada_en", "salida_guiada_id", "usuario_id") VALUES (NEW."adultos", NEW."cancelada_en", NEW."cancelada_por", NEW."circuito_id", NEW."creado_en", NEW."estado_id", NEW."estado_pago", NEW."fecha", NEW."hora_inicio", NEW."id", NEW."iniciada_en", NEW."itinerario_id", NEW."monto", NEW."motivo_cancelacion", NEW."ninos", NEW."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."postulacion_id", NEW."prestada_en", NEW."salida_guiada_id", NEW."usuario_id"); RETURN NULL;',
                    hash="487ff3acf3cf98af4eec6a666725867d9cca9bcf",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_3f1cf",
                    table="reserva",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="guideddepartureevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_guideddepartureevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="guideddepartureevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_guideddepartureevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="guideddepartureevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_guideddepartureevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="guideddepartureevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_guideddepartureevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="guideddepartureevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_guideddepartureevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="guideddepartureevent",
            index=models.Index(fields=["id"], name="idx_guideddepartureevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="guideddepartureevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="6ccfd3c74489ab6b70129c1b1e6c529712916410",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_4adbf",
                    table="salida_guiada_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["city", "status", "date"], name="idx_convocatoria_ciudad"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("adults__gte", 1), ("children__gte", 0)),
                name="chk_convocatoria_grupo_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("adults__lte", 50), ("children__lte", 50)),
                name="chk_convocatoria_grupo_tope",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_fee__isnull", True), ("max_fee__gt", 0), _connector="OR"
                ),
                name="chk_convocatoria_tarifa_positiva",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="servicerequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="6fa36e6f0a067b7553b099324e0e96bb70cd8fb0",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_3329f",
                    table="convocatoria",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="servicerequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="f2ac0de69d88cf2e4ce43d51a9fc8e1a1dab0ced",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_296ad",
                    table="convocatoria",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="servicerequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "convocatoria_cambio" ("adultos", "cerrada_en", "ciudad_id", "creado_en", "estado_id", "fecha", "hora_inicio", "id", "itinerario_id", "ninos", "nota", "pgh_context", "pgh_created_at", "pgh_label", "tarifa_maxima", "usuario_id") VALUES (OLD."adultos", OLD."cerrada_en", OLD."ciudad_id", OLD."creado_en", OLD."estado_id", OLD."fecha", OLD."hora_inicio", OLD."id", OLD."itinerario_id", OLD."ninos", OLD."nota", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."tarifa_maxima", OLD."usuario_id"); RETURN NULL;',
                    hash="d905b481d4a9c69fad24908e4715c8506b1900f1",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_3bca7",
                    table="convocatoria",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="servicerequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "convocatoria_cambio" ("adultos", "cerrada_en", "ciudad_id", "creado_en", "estado_id", "fecha", "hora_inicio", "id", "itinerario_id", "ninos", "nota", "pgh_context", "pgh_created_at", "pgh_label", "tarifa_maxima", "usuario_id") VALUES (NEW."adultos", NEW."cerrada_en", NEW."ciudad_id", NEW."creado_en", NEW."estado_id", NEW."fecha", NEW."hora_inicio", NEW."id", NEW."itinerario_id", NEW."ninos", NEW."nota", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."tarifa_maxima", NEW."usuario_id"); RETURN NULL;',
                    hash="fdddf6ea2b318f93c0e2ea29d8160cda9fbbcf4d",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_0b0bf",
                    table="convocatoria",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="servicerequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "convocatoria_cambio" ("adultos", "cerrada_en", "ciudad_id", "creado_en", "estado_id", "fecha", "hora_inicio", "id", "itinerario_id", "ninos", "nota", "pgh_context", "pgh_created_at", "pgh_label", "tarifa_maxima", "usuario_id") VALUES (NEW."adultos", NEW."cerrada_en", NEW."ciudad_id", NEW."creado_en", NEW."estado_id", NEW."fecha", NEW."hora_inicio", NEW."id", NEW."itinerario_id", NEW."ninos", NEW."nota", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."tarifa_maxima", NEW."usuario_id"); RETURN NULL;',
                    hash="39563130b23b30d46e3ac9bec8725dc19efe5b34",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_f89a3",
                    table="convocatoria",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="applicationevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_applicationevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="applicationevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_applicationevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="applicationevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_applicationevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="applicationevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_applicationevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_applicationevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationevent",
            index=models.Index(fields=["id"], name="idx_applicationevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="applicationevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="e5e3aeb087a2766d80687105240842eb2024e240",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_dbe69",
                    table="postulacion_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "status__in",
                    ["enviada", "aceptada", "rechazada", "retirada"],
                )),
                name="chk_postulacion_estado",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q(("fee__gt", 0)),
                name="chk_postulacion_tarifa_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("request", "provider"), name="unq_postulacion_guia"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="application",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="707f20b5a8e7e621e37ed3f860601f68dafd5b2a",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_0fca2",
                    table="postulacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="application",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="84e92b84c85017ef73353ddb00f481e98951ac35",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_9c211",
                    table="postulacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="application",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "postulacion_cambio" ("convocatoria_id", "creado_en", "estado", "id", "mensaje", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label", "tarifa") VALUES (OLD."convocatoria_id", OLD."creado_en", OLD."estado", OLD."id", OLD."mensaje", OLD."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."tarifa"); RETURN NULL;',
                    hash="e6e640eb2e7e11d8485afdba9fc962e2d559ca7e",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_90e6c",
                    table="postulacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="application",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "postulacion_cambio" ("convocatoria_id", "creado_en", "estado", "id", "mensaje", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label", "tarifa") VALUES (NEW."convocatoria_id", NEW."creado_en", NEW."estado", NEW."id", NEW."mensaje", NEW."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."tarifa"); RETURN NULL;',
                    hash="cfbe89572289dade552de7ed728a72c933c13f4f",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_34940",
                    table="postulacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="application",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "postulacion_cambio" ("convocatoria_id", "creado_en", "estado", "id", "mensaje", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label", "tarifa") VALUES (NEW."convocatoria_id", NEW."creado_en", NEW."estado", NEW."id", NEW."mensaje", NEW."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."tarifa"); RETURN NULL;',
                    hash="b59280b151ffd302e6292a19b5cf6a2af41d06aa",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_3652a",
                    table="postulacion",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_servicerequestevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_servicerequestevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_servicerequestevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_servicerequestevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_servicerequestevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequestevent",
            index=models.Index(fields=["id"], name="idx_servicerequestevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="servicerequestevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="206719936e15525048d9bc669cb7f5e3aa988cb5",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_46b9d",
                    table="convocatoria_cambio",
                    when="BEFORE",
                ),
            ),
        ),
    ]
