# Generated by Django 6.1 on 2026-10-06 17:38

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apicatalogs", "0001_initial"),
        ("apiorganizations", "0001_initial"),
        ("apiterritory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationStatusEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=24)),
                ("label", models.CharField(db_column="etiqueta", max_length=60)),
                ("in_queue", models.BooleanField(db_column="en_bandeja")),
                ("is_terminal", models.BooleanField(db_column="es_terminal")),
            ],
            options={
                "db_table": "estado_verificacion_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        db_column="enviada_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        db_column="resuelta_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        db_column="comercio_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to="apiorganizations.business",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        db_column="institucion_cultural_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to="apiorganizations.culturalinstitution",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        db_column="alcaldia_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to="apiterritory.municipality",
                    ),
                ),
                (
                    "taken_by",
                    models.ForeignKey(
                        db_column="tomada_por",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "solicitud_verificacion",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VerificationResolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("approved", models.BooleanField(db_column="aprobada")),
                (
                    "note",
                    models.TextField(
                        blank=True, db_column="nota", db_default="", default=""
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        db_column="resuelta_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        db_column="motivo_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="apicatalogs.reason",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        db_column="solicitud_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution",
                        to="apimoderation.verificationrequest",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        db_column="resuelta_por",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resolucion_verificacion",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VerificationStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=24)),
                ("label", models.CharField(db_column="etiqueta", max_length=60)),
                ("in_queue", models.BooleanField(db_column="en_bandeja")),
                ("is_terminal", models.BooleanField(db_column="es_terminal")),
            ],
            options={
                "db_table": "estado_verificacion",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",), name="unq_estadoverificacion_codigo"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VerificationRequestEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        db_column="enviada_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        db_column="resuelta_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        db_column="comercio_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiorganizations.business",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        db_column="institucion_cultural_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiorganizations.culturalinstitution",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        db_column="alcaldia_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiterritory.municipality",
                    ),
                ),
                (
                    "taken_by",
                    models.ForeignKey(
                        db_column="tomada_por",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        db_column="estado_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apimoderation.verificationstatus",
                    ),
                ),
            ],
            options={
                "db_table": "solicitud_verificacion_cambio",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="verificationrequest",
            name="status",
            field=models.ForeignKey(
                db_column="estado_id",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="requests",
                to="apimoderation.verificationstatus",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="70a5279d7dda5c7b832ea278b184215c3ee054cd",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_0940c",
                    table="estado_verificacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="d92410979234443a2907932273d40517276dc351",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_0902d",
                    table="estado_verificacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estado_verificacion_cambio" ("codigo", "en_bandeja", "es_terminal", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."codigo", OLD."en_bandeja", OLD."es_terminal", OLD."etiqueta", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="ca56d5e857532e7bc251dac5a07e1bfbbd9c02e7",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_3c3b9",
                    table="estado_verificacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estado_verificacion_cambio" ("codigo", "en_bandeja", "es_terminal", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."codigo", NEW."en_bandeja", NEW."es_terminal", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="3abd139e81ed5a6acfb45ebfe4ef18e2b2575b52",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_e2632",
                    table="estado_verificacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "estado_verificacion_cambio" ("codigo", "en_bandeja", "es_terminal", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."codigo", NEW."en_bandeja", NEW."es_terminal", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="08b74ea94dc644b27db3493ad1255bcdbe93f58c",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_14f30",
                    table="estado_verificacion",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="verificationstatusevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_verificationstatusevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="verificationstatusevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_verificationstatusevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationstatusevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_verificationstatusevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationstatusevent",
            index=models.Index(
                fields=["pgh_created_at"],
                name="idx_verificationstatusevent_pghcreatedat",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationstatusevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_verificationstatusevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationstatusevent",
            index=models.Index(fields=["id"], name="idx_verificationstatusevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationstatusevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="099dac51f0f897ff945d5513d30c9b9cb5c31081",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_c083f",
                    table="estado_verificacion_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationresolution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved", True), ("reason__isnull", False), _connector="OR"
                ),
                name="chk_resolucionverificacion_motivo_exigido",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationresolution",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="954f7932b9fe0caea7a15495af80056d41ec7a14",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_b897b",
                    table="resolucion_verificacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationresolution",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="09fa5a9ee0e301a5e01592eb9f221ed1caddcaec",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_70e65",
                    table="resolucion_verificacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationresolution",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_resolucionverificacion_soloinsercion",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="3913ebcc113824ba8d549d1d439cba5af8db4c51",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_trg_resolucionverificacion_soloinsercion_4a830",
                    table="resolucion_verificacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationresolution",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_resolucionverificacion_aplica",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                IF NEW.aprobada THEN\n                    UPDATE comercio SET verificado_en = NEW.resuelta_en\n                    WHERE verificado_en IS NULL AND id = (\n                        SELECT comercio_id FROM solicitud_verificacion\n                        WHERE id = NEW.solicitud_id\n                    );\n\n                    UPDATE alcaldia SET verificado_en = NEW.resuelta_en\n                    WHERE verificado_en IS NULL AND id = (\n                        SELECT alcaldia_id FROM solicitud_verificacion\n                        WHERE id = NEW.solicitud_id\n                    );\n\n                    UPDATE institucion_cultural SET verificado_en = NEW.resuelta_en\n                    WHERE verificado_en IS NULL AND id = (\n                        SELECT institucion_cultural_id FROM solicitud_verificacion\n                        WHERE id = NEW.solicitud_id\n                    );\n                END IF;\n\n                RETURN NULL;\n                ",
                    hash="4d35cbf5884b48389184dd9e69da533dbb5f3251",
                    operation="INSERT",
                    pgid="pgtrigger_trg_resolucionverificacion_aplica_6e544",
                    table="resolucion_verificacion",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequestevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_verificationrequestevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequestevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_verificationrequestevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequestevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_verificationrequestevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequestevent",
            index=models.Index(
                fields=["pgh_created_at"],
                name="idx_verificationrequestevent_pghcreatedat",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequestevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_verificationrequestevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequestevent",
            index=models.Index(fields=["id"], name="idx_verificationrequestevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationrequestevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="d67dd2a5abdec06060b05d92065206b014c6523b",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_593b0",
                    table="solicitud_verificacion_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequest",
            index=models.Index(
                condition=models.Q(("resolved_at__isnull", True)),
                fields=["submitted_at"],
                name="idx_solicitudverificacion_bandeja",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationrequest",
            index=models.Index(
                condition=models.Q(("resolved_at__isnull", True)),
                fields=["taken_by"],
                name="idx_solicitudverificacion_tomada",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("business__isnull", False),
                        ("institution__isnull", True),
                        ("municipality__isnull", True),
                    ),
                    models.Q(
                        ("business__isnull", True),
                        ("institution__isnull", False),
                        ("municipality__isnull", True),
                    ),
                    models.Q(
                        ("business__isnull", True),
                        ("institution__isnull", True),
                        ("municipality__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="chk_solicitudverificacion_objeto_excluyente",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("resolved_at__isnull", True),
                    ("resolved_at__gte", models.F("submitted_at")),
                    _connector="OR",
                ),
                name="chk_solicitudverificacion_resuelta_coherente",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("business__isnull", False), ("resolved_at__isnull", True)
                ),
                fields=("business",),
                name="unq_solicitudverificacion_abierta_comercio",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("institution__isnull", False), ("resolved_at__isnull", True)
                ),
                fields=("institution",),
                name="unq_solicitudverificacion_abierta_institucion",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("municipality__isnull", False), ("resolved_at__isnull", True)
                ),
                fields=("municipality",),
                name="unq_solicitudverificacion_abierta_alcaldia",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="a3bdf23f700af2bcb2be1ae23d8ec33549496e6e",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_2a3a3",
                    table="solicitud_verificacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="9203b789498e298b137bb4db3af54ee45f997405",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_fdbea",
                    table="solicitud_verificacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_solicitudverificacion_readonly",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."comercio_id" IS DISTINCT FROM (NEW."comercio_id") OR OLD."institucion_cultural_id" IS DISTINCT FROM (NEW."institucion_cultural_id") OR OLD."alcaldia_id" IS DISTINCT FROM (NEW."alcaldia_id") OR OLD."enviada_en" IS DISTINCT FROM (NEW."enviada_en"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="5a0b4eda9e8cc6278f64e7d2d39c006beae9813d",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_solicitudverificacion_readonly_3d603",
                    table="solicitud_verificacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "solicitud_verificacion_cambio" ("alcaldia_id", "comercio_id", "enviada_en", "estado_id", "id", "institucion_cultural_id", "pgh_context", "pgh_created_at", "pgh_label", "resuelta_en", "tomada_por") VALUES (OLD."alcaldia_id", OLD."comercio_id", OLD."enviada_en", OLD."estado_id", OLD."id", OLD."institucion_cultural_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."resuelta_en", OLD."tomada_por"); RETURN NULL;',
                    hash="36349bc78f515fd17ab9a40185960cc1baef0e76",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_0e783",
                    table="solicitud_verificacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "solicitud_verificacion_cambio" ("alcaldia_id", "comercio_id", "enviada_en", "estado_id", "id", "institucion_cultural_id", "pgh_context", "pgh_created_at", "pgh_label", "resuelta_en", "tomada_por") VALUES (NEW."alcaldia_id", NEW."comercio_id", NEW."enviada_en", NEW."estado_id", NEW."id", NEW."institucion_cultural_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."resuelta_en", NEW."tomada_por"); RETURN NULL;',
                    hash="2a87ca540b8178aaabfeabc3704163fd186ea710",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_fd1e0",
                    table="solicitud_verificacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "solicitud_verificacion_cambio" ("alcaldia_id", "comercio_id", "enviada_en", "estado_id", "id", "institucion_cultural_id", "pgh_context", "pgh_created_at", "pgh_label", "resuelta_en", "tomada_por") VALUES (NEW."alcaldia_id", NEW."comercio_id", NEW."enviada_en", NEW."estado_id", NEW."id", NEW."institucion_cultural_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."resuelta_en", NEW."tomada_por"); RETURN NULL;',
                    hash="b03b5e311a264451b38c379a4e837375b2db5ebf",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_10dcb",
                    table="solicitud_verificacion",
                    when="AFTER",
                ),
            ),
        ),
    ]
