# Generated by Django 6.1 on 2026-10-06 22:57

import pgtrigger.migrations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apimoderation", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="verificationrequest",
            name="trg_solicitudverificacion_readonly",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="verificationrequest",
            name="trg_log_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="verificationrequest",
            name="trg_log_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="verificationrequest",
            name="trg_log_update",
        ),
        migrations.RemoveConstraint(
            model_name="verificationrequest",
            name="chk_solicitudverificacion_objeto_excluyente",
        ),
        migrations.AddField(
            model_name="verificationrequest",
            name="procedure",
            field=models.CharField(
                choices=[("alta", "Application"), ("renovacion", "Renewal")],
                db_column="tramite",
                db_default="alta",
                default="alta",
                max_length=16,
            ),
        ),
    ]
