# Generated by Django 6.1 on 2026-10-06 23:10

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apimoderation", "0002_tramite"),
        ("apiorganizations", "0001_initial"),
        ("apiprofiles", "0001_initial"),
        ("apiterritory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationrequest",
            name="provider",
            field=models.ForeignKey(
                db_column="perfil_prestador_id",
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_requests",
                to="apiprofiles.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="verificationrequestevent",
            name="procedure",
            field=models.CharField(
                choices=[("alta", "Application"), ("renovacion", "Renewal")],
                db_column="tramite",
                db_default="alta",
                default="alta",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="verificationrequestevent",
            name="provider",
            field=models.ForeignKey(
                db_column="perfil_prestador_id",
                db_constraint=False,
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiprofiles.providerprofile",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_solicitudverificacion_readonly",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."comercio_id" IS DISTINCT FROM (NEW."comercio_id") OR OLD."institucion_cultural_id" IS DISTINCT FROM (NEW."institucion_cultural_id") OR OLD."alcaldia_id" IS DISTINCT FROM (NEW."alcaldia_id") OR OLD."tramite" IS DISTINCT FROM (NEW."tramite") OR OLD."perfil_prestador_id" IS DISTINCT FROM (NEW."perfil_prestador_id") OR OLD."enviada_en" IS DISTINCT FROM (NEW."enviada_en"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="0000e107612ca7461a3feb321be669025653929d",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_solicitudverificacion_readonly_3d603",
                    table="solicitud_verificacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "solicitud_verificacion_cambio" ("alcaldia_id", "comercio_id", "enviada_en", "estado_id", "id", "institucion_cultural_id", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label", "resuelta_en", "tomada_por", "tramite") VALUES (OLD."alcaldia_id", OLD."comercio_id", OLD."enviada_en", OLD."estado_id", OLD."id", OLD."institucion_cultural_id", OLD."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."resuelta_en", OLD."tomada_por", OLD."tramite"); RETURN NULL;',
                    hash="4c2f571150ec5e6c08681a455e3e0a99f794df7f",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_0e783",
                    table="solicitud_verificacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "solicitud_verificacion_cambio" ("alcaldia_id", "comercio_id", "enviada_en", "estado_id", "id", "institucion_cultural_id", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label", "resuelta_en", "tomada_por", "tramite") VALUES (NEW."alcaldia_id", NEW."comercio_id", NEW."enviada_en", NEW."estado_id", NEW."id", NEW."institucion_cultural_id", NEW."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."resuelta_en", NEW."tomada_por", NEW."tramite"); RETURN NULL;',
                    hash="5e7ac5d9c43abdd1ec6577a971934f06c1f2dc45",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_fd1e0",
                    table="solicitud_verificacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="verificationrequest",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "solicitud_verificacion_cambio" ("alcaldia_id", "comercio_id", "enviada_en", "estado_id", "id", "institucion_cultural_id", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label", "resuelta_en", "tomada_por", "tramite") VALUES (NEW."alcaldia_id", NEW."comercio_id", NEW."enviada_en", NEW."estado_id", NEW."id", NEW."institucion_cultural_id", NEW."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."resuelta_en", NEW."tomada_por", NEW."tramite"); RETURN NULL;',
                    hash="88df23e9b8f9e20960f56003e690840f4e3901bb",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_10dcb",
                    table="solicitud_verificacion",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("business__isnull", False),
                        ("institution__isnull", True),
                        ("municipality__isnull", True),
                        ("provider__isnull", True),
                    ),
                    models.Q(
                        ("business__isnull", True),
                        ("institution__isnull", False),
                        ("municipality__isnull", True),
                        ("provider__isnull", True),
                    ),
                    models.Q(
                        ("business__isnull", True),
                        ("institution__isnull", True),
                        ("municipality__isnull", False),
                        ("provider__isnull", True),
                    ),
                    models.Q(
                        ("business__isnull", True),
                        ("institution__isnull", True),
                        ("municipality__isnull", True),
                        ("provider__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="chk_solicitudverificacion_objeto_excluyente",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("procedure__in", ["alta", "renovacion"])),
                name="chk_solicitudverificacion_tramite",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("procedure", "alta"), ("provider__isnull", False), _connector="OR"
                ),
                name="chk_solicitudverificacion_renovacion_prestador",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("provider__isnull", False), ("resolved_at__isnull", True)
                ),
                fields=("provider",),
                name="unq_solicitudverificacion_abierta_prestador",
            ),
        ),
    ]
