# Generated by Django 6.1 on 2026-10-06 23:10

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apicatalogs", "0002_prestadores"),
        ("apimoderation", "0002_tramite"),
        ("apiterritory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialStatusEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=24)),
                ("label", models.CharField(db_column="etiqueta", max_length=60)),
                ("accredits", models.BooleanField(db_column="acredita")),
                ("is_terminal", models.BooleanField(db_column="es_terminal")),
            ],
            options={
                "db_table": "estado_acreditacion_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderLanguage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("basico", "Basic"),
                            ("intermedio", "Intermediate"),
                            ("avanzado", "Advanced"),
                            ("nativo", "Native"),
                        ],
                        db_column="nivel",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "prestador_idioma",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderLanguageEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("basico", "Basic"),
                            ("intermedio", "Intermediate"),
                            ("avanzado", "Advanced"),
                            ("nativo", "Native"),
                        ],
                        db_column="nivel",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "prestador_idioma_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(db_column="telefono", max_length=30)),
                (
                    "presentation",
                    models.TextField(
                        blank=True, db_column="presentacion", db_default="", default=""
                    ),
                ),
                (
                    "photo_key",
                    models.CharField(
                        blank=True,
                        db_column="foto_clave",
                        db_default="",
                        default="",
                        max_length=255,
                    ),
                ),
                (
                    "carries_tourists",
                    models.BooleanField(
                        db_column="lleva_turistas", db_default=False, default=False
                    ),
                ),
                (
                    "rating_average",
                    models.DecimalField(
                        db_column="promedio_valoracion",
                        db_default=None,
                        decimal_places=2,
                        default=None,
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "reviews_count",
                    models.IntegerField(
                        db_column="total_resenas", db_default=0, default=0
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        db_column="aprobado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "perfil_prestador",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderProfileEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(db_column="telefono", max_length=30)),
                (
                    "presentation",
                    models.TextField(
                        blank=True, db_column="presentacion", db_default="", default=""
                    ),
                ),
                (
                    "photo_key",
                    models.CharField(
                        blank=True,
                        db_column="foto_clave",
                        db_default="",
                        default="",
                        max_length=255,
                    ),
                ),
                (
                    "carries_tourists",
                    models.BooleanField(
                        db_column="lleva_turistas", db_default=False, default=False
                    ),
                ),
                (
                    "rating_average",
                    models.DecimalField(
                        db_column="promedio_valoracion",
                        db_default=None,
                        decimal_places=2,
                        default=None,
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "reviews_count",
                    models.IntegerField(
                        db_column="total_resenas", db_default=0, default=0
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        db_column="aprobado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "perfil_prestador_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "prestador_servicio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderServiceEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "prestador_servicio_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=24)),
                ("label", models.CharField(db_column="etiqueta", max_length=60)),
                ("is_visible", models.BooleanField(db_column="es_visible")),
                ("accepts_bookings", models.BooleanField(db_column="acepta_reservas")),
            ],
            options={
                "db_table": "estado_prestador",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderStatusEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=24)),
                ("label", models.CharField(db_column="etiqueta", max_length=60)),
                ("is_visible", models.BooleanField(db_column="es_visible")),
                ("accepts_bookings", models.BooleanField(db_column="acepta_reservas")),
            ],
            options={
                "db_table": "estado_prestador_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CredentialStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=24)),
                ("label", models.CharField(db_column="etiqueta", max_length=60)),
                ("accredits", models.BooleanField(db_column="acredita")),
                ("is_terminal", models.BooleanField(db_column="es_terminal")),
            ],
            options={
                "db_table": "estado_acreditacion",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",), name="unq_estadoacreditacion_codigo"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CredentialEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(db_column="numero", max_length=60)),
                ("file_key", models.CharField(db_column="archivo_id", max_length=255)),
                ("issued_on", models.DateField(db_column="emitida_el")),
                (
                    "expires_on",
                    models.DateField(
                        db_column="vence_el", db_default=None, default=None, null=True
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        db_column="cargada_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[("aceptada", "Accepted"), ("rechazada", "Rejected")],
                        db_column="veredicto",
                        db_default="",
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        db_column="revisada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, db_column="nota", db_default="", default=""
                    ),
                ),
                (
                    "credential_type",
                    models.ForeignKey(
                        db_column="tipo_acreditacion_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apicatalogs.credentialtype",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        db_column="motivo_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apicatalogs.reason",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        db_column="solicitud_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apimoderation.verificationrequest",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        db_column="revisada_por",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        db_column="estado_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiprofiles.credentialstatus",
                    ),
                ),
            ],
            options={
                "db_table": "acreditacion_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(db_column="numero", max_length=60)),
                ("file_key", models.CharField(db_column="archivo_id", max_length=255)),
                ("issued_on", models.DateField(db_column="emitida_el")),
                (
                    "expires_on",
                    models.DateField(
                        db_column="vence_el", db_default=None, default=None, null=True
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        db_column="cargada_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[("aceptada", "Accepted"), ("rechazada", "Rejected")],
                        db_column="veredicto",
                        db_default="",
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        db_column="revisada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, db_column="nota", db_default="", default=""
                    ),
                ),
                (
                    "credential_type",
                    models.ForeignKey(
                        db_column="tipo_acreditacion_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="credentials",
                        to="apicatalogs.credentialtype",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        db_column="motivo_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="apicatalogs.reason",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        db_column="solicitud_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="credentials",
                        to="apimoderation.verificationrequest",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        db_column="revisada_por",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        db_column="estado_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="credentials",
                        to="apiprofiles.credentialstatus",
                    ),
                ),
            ],
            options={
                "db_table": "acreditacion",
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credentialstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="ddf34299dfa5390be489d7d5bb422f792d944d32",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_e74dd",
                    table="estado_acreditacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credentialstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="099a5088984c962ce292d2951c0c84adac1f7fc1",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_e9e4b",
                    table="estado_acreditacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credentialstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estado_acreditacion_cambio" ("acredita", "codigo", "es_terminal", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."acredita", OLD."codigo", OLD."es_terminal", OLD."etiqueta", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="d7d6e6dc282dd5f401ef2a09e82eb439ce922e9d",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_4c71b",
                    table="estado_acreditacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credentialstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estado_acreditacion_cambio" ("acredita", "codigo", "es_terminal", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."acredita", NEW."codigo", NEW."es_terminal", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="3fb253030cafb679dfaa9ec3b353bc3a479892e3",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_5d124",
                    table="estado_acreditacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credentialstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "estado_acreditacion_cambio" ("acredita", "codigo", "es_terminal", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."acredita", NEW."codigo", NEW."es_terminal", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="709350c45bf9d7b8dd987e17df69efd00a660ef9",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_19aa6",
                    table="estado_acreditacion",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="credentialstatusevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_credentialstatusevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="credentialstatusevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_credentialstatusevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="credentialstatusevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_credentialstatusevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="credentialstatusevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_credentialstatusevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="credentialstatusevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_credentialstatusevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="credentialstatusevent",
            index=models.Index(fields=["id"], name="idx_credentialstatusevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credentialstatusevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="5c0888f094864bd82660bec282f109646302e975",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_11704",
                    table="estado_acreditacion_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddField(
            model_name="providerlanguage",
            name="language",
            field=models.ForeignKey(
                db_column="idioma_id",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="apicatalogs.language",
            ),
        ),
        migrations.AddField(
            model_name="providerlanguageevent",
            name="language",
            field=models.ForeignKey(
                db_column="idioma_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apicatalogs.language",
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="city",
            field=models.ForeignKey(
                db_column="ciudad_id",
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="providers",
                to="apiterritory.city",
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="user",
            field=models.OneToOneField(
                db_column="usuario_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="providerlanguageevent",
            name="provider",
            field=models.ForeignKey(
                db_column="perfil_prestador_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiprofiles.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="providerlanguage",
            name="provider",
            field=models.ForeignKey(
                db_column="perfil_prestador_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="languages",
                to="apiprofiles.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="credentialevent",
            name="provider",
            field=models.ForeignKey(
                db_column="perfil_prestador_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiprofiles.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="provider",
            field=models.ForeignKey(
                db_column="perfil_prestador_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credentials",
                to="apiprofiles.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="providerprofileevent",
            name="city",
            field=models.ForeignKey(
                db_column="ciudad_id",
                db_constraint=False,
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiterritory.city",
            ),
        ),
        migrations.AddField(
            model_name="providerprofileevent",
            name="user",
            field=models.ForeignKey(
                db_column="usuario_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="providerservice",
            name="provider",
            field=models.ForeignKey(
                db_column="perfil_prestador_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="apiprofiles.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="providerservice",
            name="service",
            field=models.ForeignKey(
                db_column="tipo_servicio_id",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="apicatalogs.servicetype",
            ),
        ),
        migrations.AddField(
            model_name="providerserviceevent",
            name="provider",
            field=models.ForeignKey(
                db_column="perfil_prestador_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiprofiles.providerprofile",
            ),
        ),
        migrations.AddField(
            model_name="providerserviceevent",
            name="service",
            field=models.ForeignKey(
                db_column="tipo_servicio_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apicatalogs.servicetype",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerstatus",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unq_estadoprestador_codigo"
            ),
        ),
        migrations.AddField(
            model_name="providerprofileevent",
            name="status",
            field=models.ForeignKey(
                db_column="estado_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiprofiles.providerstatus",
            ),
        ),
        migrations.AddField(
            model_name="providerprofile",
            name="status",
            field=models.ForeignKey(
                db_column="estado_id",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="profiles",
                to="apiprofiles.providerstatus",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="6c62ba8593ccad8f2c0228cb4caedb8f756eb71e",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_b61c9",
                    table="estado_prestador",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="1e5543b3685bb3f134277e1f5d0f94e1ef3da767",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_d3e5e",
                    table="estado_prestador",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estado_prestador_cambio" ("acepta_reservas", "codigo", "es_visible", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."acepta_reservas", OLD."codigo", OLD."es_visible", OLD."etiqueta", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="a4ed16e4de2cecb9604eef92cb7a7f3815701a5a",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_3b8a5",
                    table="estado_prestador",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estado_prestador_cambio" ("acepta_reservas", "codigo", "es_visible", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."acepta_reservas", NEW."codigo", NEW."es_visible", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="0ea18333580e59c5594fa6a621a4ca2faa25db0d",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_72ff4",
                    table="estado_prestador",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerstatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "estado_prestador_cambio" ("acepta_reservas", "codigo", "es_visible", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."acepta_reservas", NEW."codigo", NEW."es_visible", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="8f78a91678b380a50ba95a28c1e2ca2d7995e34d",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_4fec7",
                    table="estado_prestador",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="providerstatusevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_providerstatusevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="providerstatusevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_providerstatusevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="providerstatusevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_providerstatusevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="providerstatusevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_providerstatusevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="providerstatusevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_providerstatusevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="providerstatusevent",
            index=models.Index(fields=["id"], name="idx_providerstatusevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerstatusevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="05038555fc86ee9162a5fa76bee3ba6b810421fa",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_c1e82",
                    table="estado_prestador_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="providerlanguageevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_providerlanguageevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="providerlanguageevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_providerlanguageevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="providerlanguageevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_providerlanguageevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="providerlanguageevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_providerlanguageevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="providerlanguageevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_providerlanguageevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="providerlanguageevent",
            index=models.Index(fields=["id"], name="idx_providerlanguageevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerlanguageevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="d6e74db5392fecfa1cd617e664680cb2969ddf32",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_98988",
                    table="prestador_idioma_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="providerlanguage",
            constraint=models.UniqueConstraint(
                fields=("provider", "language"), name="unq_prestadoridioma_par"
            ),
        ),
        migrations.AddConstraint(
            model_name="providerlanguage",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "level__in",
                    ["basico", "intermedio", "avanzado", "nativo"],
                )),
                name="chk_prestadoridioma_nivel",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerlanguage",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="10940baa0b986ba5421ed0f4cc07b960abcbb9b0",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_9a798",
                    table="prestador_idioma",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerlanguage",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="dfc72a07a4df4e22075c5b1a22eaef30085db381",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_06d6e",
                    table="prestador_idioma",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerlanguage",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "prestador_idioma_cambio" ("id", "idioma_id", "nivel", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."id", OLD."idioma_id", OLD."nivel", OLD."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="7097c5ced4f4ba1941c8f300b993113431a1c016",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_0e7d6",
                    table="prestador_idioma",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerlanguage",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "prestador_idioma_cambio" ("id", "idioma_id", "nivel", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."id", NEW."idioma_id", NEW."nivel", NEW."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="164e473e21a318705e81cdef43ec7b287a8ef459",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_007d7",
                    table="prestador_idioma",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerlanguage",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "prestador_idioma_cambio" ("id", "idioma_id", "nivel", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."id", NEW."idioma_id", NEW."nivel", NEW."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="76e04f533fc8f630d87b138257047c5c8be71057",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_c087c",
                    table="prestador_idioma",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="credentialevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_credentialevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="credentialevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_credentialevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="credentialevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_credentialevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="credentialevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_credentialevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="credentialevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_credentialevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="credentialevent",
            index=models.Index(fields=["id"], name="idx_credentialevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credentialevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="9ff475fbf72dac304721ccd762b57066b5ca821c",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_7bc74",
                    table="acreditacion_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="credential",
            index=models.Index(
                condition=models.Q(("expires_on__isnull", False)),
                fields=["expires_on"],
                name="idx_acreditacion_vencimiento",
            ),
        ),
        migrations.AddIndex(
            model_name="credential",
            index=models.Index(
                models.F("provider"),
                models.F("credential_type"),
                models.OrderBy(models.F("uploaded_at"), descending=True),
                name="idx_acreditacion_perfil_tipo",
            ),
        ),
        migrations.AddConstraint(
            model_name="credential",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expires_on__isnull", True),
                    ("expires_on__gt", models.F("issued_on")),
                    _connector="OR",
                ),
                name="chk_acreditacion_vigencia_orden",
            ),
        ),
        migrations.AddConstraint(
            model_name="credential",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("verdict", ""),
                    ("verdict__in", ["aceptada", "rechazada"]),
                    _connector="OR",
                ),
                name="chk_acreditacion_veredicto",
            ),
        ),
        migrations.AddConstraint(
            model_name="credential",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("reason__isnull", True),
                        ("reviewed_at__isnull", True),
                        ("reviewed_by__isnull", True),
                        ("verdict", ""),
                    ),
                    models.Q(
                        ("reviewed_at__isnull", False),
                        ("reviewed_by__isnull", False),
                        models.Q(("verdict", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="chk_acreditacion_revision_coherente",
            ),
        ),
        migrations.AddConstraint(
            model_name="credential",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("verdict", "rechazada"), _negated=True),
                    ("reason__isnull", False),
                    _connector="OR",
                ),
                name="chk_acreditacion_motivo_exigido",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credential",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="c4a0d86be5dd50ebd76113430c541e381466bd99",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_c9e7a",
                    table="acreditacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credential",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="ca419a8cc2f0e12a0a947bafb621ad00574e9132",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_5922b",
                    table="acreditacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credential",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_acreditacion_readonly",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."tipo_acreditacion_id" IS DISTINCT FROM (NEW."tipo_acreditacion_id") OR OLD."vence_el" IS DISTINCT FROM (NEW."vence_el") OR OLD."archivo_id" IS DISTINCT FROM (NEW."archivo_id") OR OLD."emitida_el" IS DISTINCT FROM (NEW."emitida_el") OR OLD."numero" IS DISTINCT FROM (NEW."numero") OR OLD."perfil_prestador_id" IS DISTINCT FROM (NEW."perfil_prestador_id") OR OLD."solicitud_id" IS DISTINCT FROM (NEW."solicitud_id") OR OLD."cargada_en" IS DISTINCT FROM (NEW."cargada_en"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="248d6ee389c032196ca5e10de275ba1e419adda5",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_acreditacion_readonly_c1ec9",
                    table="acreditacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credential",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_acreditacion_vencimiento_exigido",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                IF NEW.vence_el IS NULL AND EXISTS (\n                    SELECT 1 FROM tipo_acreditacion\n                    WHERE id = NEW.tipo_acreditacion_id AND exige_vencimiento\n                ) THEN\n                    RAISE EXCEPTION 'Ese documento exige su fecha de vencimiento.';\n                END IF;\n\n                RETURN NEW;\n                ",
                    hash="9b863bce9b0fbabeffc010e9f2eff7277cd202aa",
                    operation="INSERT",
                    pgid="pgtrigger_trg_acreditacion_vencimiento_exigido_643e9",
                    table="acreditacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credential",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_acreditacion_vigente_unica",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                IF EXISTS (\n                    SELECT 1 FROM estado_acreditacion\n                    WHERE id = NEW.estado_id AND codigo = 'aprobada'\n                ) AND EXISTS (\n                    SELECT 1 FROM acreditacion a\n                    JOIN estado_acreditacion e ON e.id = a.estado_id\n                    WHERE a.perfil_prestador_id = NEW.perfil_prestador_id\n                    AND a.tipo_acreditacion_id = NEW.tipo_acreditacion_id\n                    AND a.id <> NEW.id\n                    AND e.codigo = 'aprobada'\n                ) THEN\n                    RAISE EXCEPTION 'Ya hay un documento de ese tipo en vigor.';\n                END IF;\n\n                RETURN NEW;\n                ",
                    hash="295a293ce976d98f10ea41151e307eb63784da73",
                    operation="INSERT OR UPDATE",
                    pgid="pgtrigger_trg_acreditacion_vigente_unica_76132",
                    table="acreditacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credential",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "acreditacion_cambio" ("archivo_id", "cargada_en", "emitida_el", "estado_id", "id", "motivo_id", "nota", "numero", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label", "revisada_en", "revisada_por", "solicitud_id", "tipo_acreditacion_id", "vence_el", "veredicto") VALUES (OLD."archivo_id", OLD."cargada_en", OLD."emitida_el", OLD."estado_id", OLD."id", OLD."motivo_id", OLD."nota", OLD."numero", OLD."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."revisada_en", OLD."revisada_por", OLD."solicitud_id", OLD."tipo_acreditacion_id", OLD."vence_el", OLD."veredicto"); RETURN NULL;',
                    hash="a071fd3f03be36bd41bef8ab411ae8ba892130bd",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_f300b",
                    table="acreditacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credential",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "acreditacion_cambio" ("archivo_id", "cargada_en", "emitida_el", "estado_id", "id", "motivo_id", "nota", "numero", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label", "revisada_en", "revisada_por", "solicitud_id", "tipo_acreditacion_id", "vence_el", "veredicto") VALUES (NEW."archivo_id", NEW."cargada_en", NEW."emitida_el", NEW."estado_id", NEW."id", NEW."motivo_id", NEW."nota", NEW."numero", NEW."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."revisada_en", NEW."revisada_por", NEW."solicitud_id", NEW."tipo_acreditacion_id", NEW."vence_el", NEW."veredicto"); RETURN NULL;',
                    hash="0adb336ca2a9fa0163bace832d3c25b6cb1a909a",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_1bf6f",
                    table="acreditacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="credential",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "acreditacion_cambio" ("archivo_id", "cargada_en", "emitida_el", "estado_id", "id", "motivo_id", "nota", "numero", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label", "revisada_en", "revisada_por", "solicitud_id", "tipo_acreditacion_id", "vence_el", "veredicto") VALUES (NEW."archivo_id", NEW."cargada_en", NEW."emitida_el", NEW."estado_id", NEW."id", NEW."motivo_id", NEW."nota", NEW."numero", NEW."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."revisada_en", NEW."revisada_por", NEW."solicitud_id", NEW."tipo_acreditacion_id", NEW."vence_el", NEW."veredicto"); RETURN NULL;',
                    hash="be411d419fd9bc4315843eae846e05bbb8a1758a",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_fc443",
                    table="acreditacion",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="providerservice",
            constraint=models.UniqueConstraint(
                fields=("provider", "service"), name="unq_prestadorservicio_par"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerservice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="e56b6d15a7fdb6a73ced8b164144a1b8c1f9e869",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_38c14",
                    table="prestador_servicio",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerservice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="a84226f28fdb3ffebc5fa27815a2d6fd52fbc81e",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_bfbd7",
                    table="prestador_servicio",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerservice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "prestador_servicio_cambio" ("id", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label", "tipo_servicio_id") VALUES (OLD."id", OLD."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."tipo_servicio_id"); RETURN NULL;',
                    hash="83ed6fbdd66da2feacae284df61f736feebe4cc7",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_ef2c6",
                    table="prestador_servicio",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerservice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "prestador_servicio_cambio" ("id", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label", "tipo_servicio_id") VALUES (NEW."id", NEW."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."tipo_servicio_id"); RETURN NULL;',
                    hash="a35c602c0960a4c0f13c57f2d2ee3ed7a1c4ca4a",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_dde8a",
                    table="prestador_servicio",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerservice",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "prestador_servicio_cambio" ("id", "perfil_prestador_id", "pgh_context", "pgh_created_at", "pgh_label", "tipo_servicio_id") VALUES (NEW."id", NEW."perfil_prestador_id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."tipo_servicio_id"); RETURN NULL;',
                    hash="686bf822cdc4388b4214076264fa9971dbfdfe22",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_e56eb",
                    table="prestador_servicio",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="providerserviceevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_providerserviceevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="providerserviceevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_providerserviceevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="providerserviceevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_providerserviceevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="providerserviceevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_providerserviceevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="providerserviceevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_providerserviceevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="providerserviceevent",
            index=models.Index(fields=["id"], name="idx_providerserviceevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerserviceevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="1f238f4871e65d474ae18522a976e50fc30c691f",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_50c48",
                    table="prestador_servicio_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="providerprofileevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_providerprofileevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="providerprofileevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_providerprofileevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="providerprofileevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_providerprofileevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="providerprofileevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_providerprofileevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="providerprofileevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_providerprofileevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="providerprofileevent",
            index=models.Index(fields=["id"], name="idx_providerprofileevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerprofileevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="f50d8759100c43e7cb655c4cfe3799b9fdb2ce54",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_407ed",
                    table="perfil_prestador_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="providerprofile",
            index=models.Index(
                models.F("status"),
                models.OrderBy(
                    models.F("rating_average"), descending=True, nulls_last=True
                ),
                name="idx_perfilprestador_busqueda",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rating_average__isnull", True),
                    models.Q(("rating_average__gte", 1), ("rating_average__lte", 5)),
                    _connector="OR",
                ),
                name="chk_perfilprestador_promedio_rango",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("rating_average__isnull", True), ("reviews_count", 0)),
                    models.Q(
                        ("rating_average__isnull", False), ("reviews_count__gt", 0)
                    ),
                    _connector="OR",
                ),
                name="chk_perfilprestador_promedio_coherente",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_at__isnull", True),
                    ("approved_at__gte", models.F("created_at")),
                    _connector="OR",
                ),
                name="chk_perfilprestador_aprobado_coherente",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="f1cfb7f1da75d7009f09bac41ad0ff997b2ee45e",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_fcb3e",
                    table="perfil_prestador",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="2fcf763734b82f7eee985fcbc453dfaab9373d89",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_5cfab",
                    table="perfil_prestador",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_perfilprestador_readonly",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."creado_en" IS DISTINCT FROM (NEW."creado_en") OR OLD."usuario_id" IS DISTINCT FROM (NEW."usuario_id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="158f536f34983e88ddc7dc8eb2db3f068fc4f499",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_perfilprestador_readonly_0e185",
                    table="perfil_prestador",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_perfilprestador_un_papel",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                IF EXISTS (\n                    SELECT 1\n                    FROM apiauth_apiusergroups ug\n                    JOIN apiauth_apigroupprofile gp ON gp.group_id = ug.group_id\n                    WHERE ug.api_user_id = NEW.usuario_id\n                    AND (gp.kind <> 'public' OR gp.role = 'turista')\n                ) THEN\n                    RAISE EXCEPTION 'Esta cuenta ya ejerce otro papel.';\n                END IF;\n\n                RETURN NEW;\n                ",
                    hash="91812949867b7e4c4a6e535d60c0722c6bb8e18f",
                    operation="INSERT",
                    pgid="pgtrigger_trg_perfilprestador_un_papel_55df4",
                    table="perfil_prestador",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_perfilprestador_noreaprueba",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NEW."aprobado_en" IS NULL AND OLD."aprobado_en" IS NOT NULL)',
                    func="RAISE EXCEPTION 'La primera aprobación no se borra.';",
                    hash="e6e6f009d99b413f2d7ffd03c2442d7a3394dcdf",
                    operation='UPDATE OF "aprobado_en"',
                    pgid="pgtrigger_trg_perfilprestador_noreaprueba_2be7e",
                    table="perfil_prestador",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "perfil_prestador_cambio" ("aprobado_en", "ciudad_id", "creado_en", "estado_id", "foto_clave", "id", "lleva_turistas", "pgh_context", "pgh_created_at", "pgh_label", "presentacion", "promedio_valoracion", "telefono", "total_resenas", "usuario_id") VALUES (OLD."aprobado_en", OLD."ciudad_id", OLD."creado_en", OLD."estado_id", OLD."foto_clave", OLD."id", OLD."lleva_turistas", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."presentacion", OLD."promedio_valoracion", OLD."telefono", OLD."total_resenas", OLD."usuario_id"); RETURN NULL;',
                    hash="632bc70e3823af80e16a9ca6863c0779f722f9b7",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_26a98",
                    table="perfil_prestador",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "perfil_prestador_cambio" ("aprobado_en", "ciudad_id", "creado_en", "estado_id", "foto_clave", "id", "lleva_turistas", "pgh_context", "pgh_created_at", "pgh_label", "presentacion", "promedio_valoracion", "telefono", "total_resenas", "usuario_id") VALUES (NEW."aprobado_en", NEW."ciudad_id", NEW."creado_en", NEW."estado_id", NEW."foto_clave", NEW."id", NEW."lleva_turistas", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."presentacion", NEW."promedio_valoracion", NEW."telefono", NEW."total_resenas", NEW."usuario_id"); RETURN NULL;',
                    hash="d8d6f8452c153d6f550761870bec86cbaaea5550",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_41c06",
                    table="perfil_prestador",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="providerprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "perfil_prestador_cambio" ("aprobado_en", "ciudad_id", "creado_en", "estado_id", "foto_clave", "id", "lleva_turistas", "pgh_context", "pgh_created_at", "pgh_label", "presentacion", "promedio_valoracion", "telefono", "total_resenas", "usuario_id") VALUES (NEW."aprobado_en", NEW."ciudad_id", NEW."creado_en", NEW."estado_id", NEW."foto_clave", NEW."id", NEW."lleva_turistas", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."presentacion", NEW."promedio_valoracion", NEW."telefono", NEW."total_resenas", NEW."usuario_id"); RETURN NULL;',
                    hash="0b74d30cbd2dc8acae8a9fad1c1ba7d713d716bc",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_56860",
                    table="perfil_prestador",
                    when="AFTER",
                ),
            ),
        ),
    ]
