# Generated by Django 6.1 on 2026-10-08 00:14

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.uuid
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apiservices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("direction", models.CharField(db_column="sentido", max_length=24)),
                ("rating", models.SmallIntegerField(db_column="calificacion")),
                (
                    "comment",
                    models.TextField(
                        blank=True, db_column="comentario", db_default="", default=""
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creada_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "hidden_at",
                    models.DateTimeField(
                        db_column="oculta_en", db_default=None, default=None, null=True
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        db_column="autor_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reviews_written",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        db_column="reserva_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reviews",
                        to="apiservices.booking",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="resenado_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reviews_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resena",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReviewDispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(db_column="motivo")),
                (
                    "status",
                    models.CharField(
                        db_column="estado",
                        db_default="pendiente",
                        default="pendiente",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creada_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        db_column="resuelta_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, db_column="nota", db_default="", default=""
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        db_column="presentada_por",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        db_column="resuelta_por",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        db_column="resena_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="apireputation.review",
                    ),
                ),
            ],
            options={
                "db_table": "resena_impugnacion",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReviewDisputeEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(db_column="motivo")),
                (
                    "status",
                    models.CharField(
                        db_column="estado",
                        db_default="pendiente",
                        default="pendiente",
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creada_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        db_column="resuelta_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, db_column="nota", db_default="", default=""
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        db_column="presentada_por",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        db_column="resuelta_por",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        db_column="resena_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apireputation.review",
                    ),
                ),
            ],
            options={
                "db_table": "resena_impugnacion_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReviewEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("direction", models.CharField(db_column="sentido", max_length=24)),
                ("rating", models.SmallIntegerField(db_column="calificacion")),
                (
                    "comment",
                    models.TextField(
                        blank=True, db_column="comentario", db_default="", default=""
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creada_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "hidden_at",
                    models.DateTimeField(
                        db_column="oculta_en", db_default=None, default=None, null=True
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        db_column="autor_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        db_column="reserva_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiservices.booking",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="resenado_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resena_cambio",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                condition=models.Q(("hidden_at__isnull", True)),
                fields=["subject", "-created_at"],
                name="idx_resena_resenado",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="chk_resena_calificacion_rango",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "direction__in",
                    ["tourist_to_guide", "guide_to_tourist"],
                )),
                name="chk_resena_sentido",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("author", models.F("subject")), _negated=True),
                name="chk_resena_no_autoresena",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("booking", "author"), name="unq_resena_autor"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="review",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="259efbea9ca9d6549fcb43666dc50123369ff420",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_fe4c4",
                    table="resena",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="review",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="55b5195b7cfc5bff5bbfaa478d6f81f606718886",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_6bb96",
                    table="resena",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="review",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_resena_inmutable",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."autor_id" IS DISTINCT FROM (NEW."autor_id") OR OLD."reserva_id" IS DISTINCT FROM (NEW."reserva_id") OR OLD."comentario" IS DISTINCT FROM (NEW."comentario") OR OLD."creada_en" IS DISTINCT FROM (NEW."creada_en") OR OLD."calificacion" IS DISTINCT FROM (NEW."calificacion") OR OLD."resenado_id" IS DISTINCT FROM (NEW."resenado_id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="654c51649c964f32ce889f2dec6c5eec21e519da",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_resena_inmutable_c5274",
                    table="resena",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="review",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "resena_cambio" ("autor_id", "calificacion", "comentario", "creada_en", "id", "oculta_en", "pgh_context", "pgh_created_at", "pgh_label", "resenado_id", "reserva_id", "sentido") VALUES (OLD."autor_id", OLD."calificacion", OLD."comentario", OLD."creada_en", OLD."id", OLD."oculta_en", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."resenado_id", OLD."reserva_id", OLD."sentido"); RETURN NULL;',
                    hash="6d919b9f29fd7f7271405aad3fe12bb1c5802b2d",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_b623b",
                    table="resena",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="review",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "resena_cambio" ("autor_id", "calificacion", "comentario", "creada_en", "id", "oculta_en", "pgh_context", "pgh_created_at", "pgh_label", "resenado_id", "reserva_id", "sentido") VALUES (NEW."autor_id", NEW."calificacion", NEW."comentario", NEW."creada_en", NEW."id", NEW."oculta_en", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."resenado_id", NEW."reserva_id", NEW."sentido"); RETURN NULL;',
                    hash="ee007291e311f53cbdadaf5eb2100d1baed4044a",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_8a84a",
                    table="resena",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="review",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "resena_cambio" ("autor_id", "calificacion", "comentario", "creada_en", "id", "oculta_en", "pgh_context", "pgh_created_at", "pgh_label", "resenado_id", "reserva_id", "sentido") VALUES (NEW."autor_id", NEW."calificacion", NEW."comentario", NEW."creada_en", NEW."id", NEW."oculta_en", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."resenado_id", NEW."reserva_id", NEW."sentido"); RETURN NULL;',
                    hash="0c34f4fc03bb4c8ecf2d0eda3465936128d7392f",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_debb3",
                    table="resena",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewdispute",
            constraint=models.CheckConstraint(
                condition=models.Q((
                    "status__in",
                    ["pendiente", "aceptada", "rechazada"],
                )),
                name="chk_resenaimpugnacion_estado",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewdispute",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pendiente")),
                fields=("review",),
                name="unq_resenaimpugnacion_abierta",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reviewdispute",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="24ca9b2f09d0bf9274886fcd33651ae335033840",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_acc68",
                    table="resena_impugnacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reviewdispute",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="865c8270c0d598953e6d7329cdb14f7ad24252dd",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_2a185",
                    table="resena_impugnacion",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reviewdispute",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "resena_impugnacion_cambio" ("creada_en", "estado", "id", "motivo", "nota", "pgh_context", "pgh_created_at", "pgh_label", "presentada_por", "resena_id", "resuelta_en", "resuelta_por") VALUES (OLD."creada_en", OLD."estado", OLD."id", OLD."motivo", OLD."nota", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."presentada_por", OLD."resena_id", OLD."resuelta_en", OLD."resuelta_por"); RETURN NULL;',
                    hash="aa279920ca432bef134144158deb17e8e44aef61",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_ccf64",
                    table="resena_impugnacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reviewdispute",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "resena_impugnacion_cambio" ("creada_en", "estado", "id", "motivo", "nota", "pgh_context", "pgh_created_at", "pgh_label", "presentada_por", "resena_id", "resuelta_en", "resuelta_por") VALUES (NEW."creada_en", NEW."estado", NEW."id", NEW."motivo", NEW."nota", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."presentada_por", NEW."resena_id", NEW."resuelta_en", NEW."resuelta_por"); RETURN NULL;',
                    hash="5b7b2ca3d6e60a540e5749a551bc6216d107c9a7",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_b461b",
                    table="resena_impugnacion",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reviewdispute",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "resena_impugnacion_cambio" ("creada_en", "estado", "id", "motivo", "nota", "pgh_context", "pgh_created_at", "pgh_label", "presentada_por", "resena_id", "resuelta_en", "resuelta_por") VALUES (NEW."creada_en", NEW."estado", NEW."id", NEW."motivo", NEW."nota", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."presentada_por", NEW."resena_id", NEW."resuelta_en", NEW."resuelta_por"); RETURN NULL;',
                    hash="14ed591a06365fe34d7851978bf6ca19ef70f26c",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_eb43a",
                    table="resena_impugnacion",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="reviewdisputeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_reviewdisputeevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="reviewdisputeevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_reviewdisputeevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewdisputeevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_reviewdisputeevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewdisputeevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_reviewdisputeevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewdisputeevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_reviewdisputeevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewdisputeevent",
            index=models.Index(fields=["id"], name="idx_reviewdisputeevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reviewdisputeevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="a80288573889f04a810a05e5e9fb901997f86c3f",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_6d449",
                    table="resena_impugnacion_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="reviewevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_reviewevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="reviewevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_reviewevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_reviewevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_reviewevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewevent",
            index=models.Index(fields=["pgh_label"], name="idx_reviewevent_pghlabel"),
        ),
        migrations.AddIndex(
            model_name="reviewevent",
            index=models.Index(fields=["id"], name="idx_reviewevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reviewevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="9177b936a487494079c47f1e1c2c483f53990b74",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_8dd03",
                    table="resena_cambio",
                    when="BEFORE",
                ),
            ),
        ),
    ]
