# Generated by Django 6.1 on 2026-10-07 22:11

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.fields.json
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.db.models.functions.uuid
import django.db.models.lookups
import django.template.defaulttags
import django.utils.timezone
import pghistory.utils
import pgtrigger.compiler
import pgtrigger.migrations

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apiterritory", "0002_lugares_circuitos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItineraryStatusEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=24)),
                ("label", models.CharField(db_column="etiqueta", max_length=60)),
                ("allows_editing", models.BooleanField(db_column="admite_edicion")),
                ("allows_booking", models.BooleanField(db_column="admite_reserva")),
                ("is_terminal", models.BooleanField(db_column="es_terminal")),
            ],
            options={
                "db_table": "estado_itinerario_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItineraryStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="nombre", max_length=80)),
                (
                    "latitude",
                    models.DecimalField(
                        db_column="latitud", decimal_places=6, max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        db_column="longitud", decimal_places=6, max_digits=9
                    ),
                ),
                ("order", models.SmallIntegerField(db_column="orden")),
                (
                    "visited_at",
                    models.DateTimeField(
                        db_column="visitada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "itinerario_parada",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItineraryStopEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="nombre", max_length=80)),
                (
                    "latitude",
                    models.DecimalField(
                        db_column="latitud", decimal_places=6, max_digits=9
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        db_column="longitud", decimal_places=6, max_digits=9
                    ),
                ),
                ("order", models.SmallIntegerField(db_column="orden")),
                (
                    "visited_at",
                    models.DateTimeField(
                        db_column="visitada_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "itinerario_parada_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_column="titulo", max_length=80)),
                (
                    "adjusted",
                    models.BooleanField(
                        db_column="ajustado", db_default=False, default=False
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        db_column="hora_salida", db_default="09:00", default="09:00"
                    ),
                ),
                (
                    "travel_mode",
                    models.CharField(
                        db_column="modo_traslado",
                        db_default="walking",
                        default="walking",
                        max_length=16,
                    ),
                ),
                (
                    "pace",
                    models.CharField(
                        db_column="ritmo",
                        db_default="balanced",
                        default="balanced",
                        max_length=16,
                    ),
                ),
                (
                    "fixed_arrivals",
                    models.JSONField(
                        db_column="llegadas_fijas", db_default={}, default=dict
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_column="iniciado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        db_column="completado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_column="eliminado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "followed_circuit",
                    models.ForeignKey(
                        db_column="circuito_seguido_id",
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="followers",
                        to="apiterritory.circuit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "itinerario",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItineraryCircuit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        db_column="orden", db_default=0, default=0
                    ),
                ),
                (
                    "circuit",
                    models.ForeignKey(
                        db_column="circuito_id",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="derived_itineraries",
                        to="apiterritory.circuit",
                    ),
                ),
                (
                    "itinerary",
                    models.ForeignKey(
                        db_column="itinerario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origins",
                        to="apiitineraries.itinerary",
                    ),
                ),
            ],
            options={
                "db_table": "itinerario_circuito",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItineraryCircuitEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        db_column="orden", db_default=0, default=0
                    ),
                ),
                (
                    "circuit",
                    models.ForeignKey(
                        db_column="circuito_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiterritory.circuit",
                    ),
                ),
                (
                    "itinerary",
                    models.ForeignKey(
                        db_column="itinerario_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiitineraries.itinerary",
                    ),
                ),
            ],
            options={
                "db_table": "itinerario_circuito_cambio",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItineraryStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_column="codigo", max_length=24)),
                ("label", models.CharField(db_column="etiqueta", max_length=60)),
                ("allows_editing", models.BooleanField(db_column="admite_edicion")),
                ("allows_booking", models.BooleanField(db_column="admite_reserva")),
                ("is_terminal", models.BooleanField(db_column="es_terminal")),
            ],
            options={
                "db_table": "estado_itinerario",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",), name="unq_estadoitinerario_codigo"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ItineraryEvent",
            fields=[
                (
                    "pgh_id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pgh_context",
                    pghistory.utils.JSONField(db_default=None, default=None, null=True),
                ),
                (
                    "pgh_created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.template.defaulttags.now,
                    ),
                ),
                ("pgh_label", models.TextField(db_default="", default="")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        default=uuid.uuid7,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_column="titulo", max_length=80)),
                (
                    "adjusted",
                    models.BooleanField(
                        db_column="ajustado", db_default=False, default=False
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        db_column="hora_salida", db_default="09:00", default="09:00"
                    ),
                ),
                (
                    "travel_mode",
                    models.CharField(
                        db_column="modo_traslado",
                        db_default="walking",
                        default="walking",
                        max_length=16,
                    ),
                ),
                (
                    "pace",
                    models.CharField(
                        db_column="ritmo",
                        db_default="balanced",
                        default="balanced",
                        max_length=16,
                    ),
                ),
                (
                    "fixed_arrivals",
                    models.JSONField(
                        db_column="llegadas_fijas", db_default={}, default=dict
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="creado_en",
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.utils.timezone.now,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_column="iniciado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        db_column="completado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        db_column="eliminado_en",
                        db_default=None,
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "followed_circuit",
                    models.ForeignKey(
                        db_column="circuito_seguido_id",
                        db_constraint=False,
                        db_default=None,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiterritory.circuit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="usuario_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        db_column="estado_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="apiitineraries.itinerarystatus",
                    ),
                ),
            ],
            options={
                "db_table": "itinerario_cambio",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="itinerary",
            name="status",
            field=models.ForeignKey(
                db_column="estado_id",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="itineraries",
                to="apiitineraries.itinerarystatus",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarystatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="884fd5b2caa68f5aa31b3228a2a59f6aca039f00",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_723f5",
                    table="estado_itinerario",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarystatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="c8c661673759bc3d539ed7b359cec89fc636a541",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_406da",
                    table="estado_itinerario",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarystatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estado_itinerario_cambio" ("admite_edicion", "admite_reserva", "codigo", "es_terminal", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."admite_edicion", OLD."admite_reserva", OLD."codigo", OLD."es_terminal", OLD."etiqueta", OLD."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="0a3702c1fdc56b1e7a1787abf71bc4b00c69777c",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_d4f41",
                    table="estado_itinerario",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarystatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "estado_itinerario_cambio" ("admite_edicion", "admite_reserva", "codigo", "es_terminal", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."admite_edicion", NEW."admite_reserva", NEW."codigo", NEW."es_terminal", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="2b8f3918b91672e99d666f5d28cce8e2b743aa42",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_ba377",
                    table="estado_itinerario",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarystatus",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "estado_itinerario_cambio" ("admite_edicion", "admite_reserva", "codigo", "es_terminal", "etiqueta", "id", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."admite_edicion", NEW."admite_reserva", NEW."codigo", NEW."es_terminal", NEW."etiqueta", NEW."id", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="72478000e2fc3274aa9355e0d5ba541986a78fa4",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_a1c2d",
                    table="estado_itinerario",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarystatusevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_itinerarystatusevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarystatusevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_itinerarystatusevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarystatusevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_itinerarystatusevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarystatusevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_itinerarystatusevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarystatusevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_itinerarystatusevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarystatusevent",
            index=models.Index(fields=["id"], name="idx_itinerarystatusevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarystatusevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="cc0718be3dfbf0f89071549806285ea7a1f3190c",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_668b0",
                    table="estado_itinerario_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddField(
            model_name="itinerarystop",
            name="itinerary",
            field=models.ForeignKey(
                db_column="itinerario_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stops",
                to="apiitineraries.itinerary",
            ),
        ),
        migrations.AddField(
            model_name="itinerarystop",
            name="point",
            field=models.ForeignKey(
                db_column="punto_interes_id",
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itinerary_stops",
                to="apiterritory.pointofinterest",
            ),
        ),
        migrations.AddField(
            model_name="itinerarystopevent",
            name="itinerary",
            field=models.ForeignKey(
                db_column="itinerario_id",
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiitineraries.itinerary",
            ),
        ),
        migrations.AddField(
            model_name="itinerarystopevent",
            name="point",
            field=models.ForeignKey(
                db_column="punto_interes_id",
                db_constraint=False,
                db_default=None,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="apiterritory.pointofinterest",
            ),
        ),
        migrations.AddConstraint(
            model_name="itinerarycircuit",
            constraint=models.UniqueConstraint(
                fields=("itinerary", "circuit"), name="unq_itinerariocircuito_par"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarycircuit",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="a8db47306b5f22816644fb85018e1ddcb321366f",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_9202b",
                    table="itinerario_circuito",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarycircuit",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="3b3aa6deb5b213e6d521f39b613ddd64f58dc081",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_03f95",
                    table="itinerario_circuito",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarycircuit",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "itinerario_circuito_cambio" ("circuito_id", "id", "itinerario_id", "orden", "pgh_context", "pgh_created_at", "pgh_label") VALUES (OLD."circuito_id", OLD."id", OLD."itinerario_id", OLD."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\'); RETURN NULL;',
                    hash="c988b6869d95f53baec41ea6ee81e5c818dc8115",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_27702",
                    table="itinerario_circuito",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarycircuit",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "itinerario_circuito_cambio" ("circuito_id", "id", "itinerario_id", "orden", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."circuito_id", NEW."id", NEW."itinerario_id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\'); RETURN NULL;',
                    hash="dd90c109b688706691e67c86d7f220def6b44bd3",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_d778c",
                    table="itinerario_circuito",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarycircuit",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "itinerario_circuito_cambio" ("circuito_id", "id", "itinerario_id", "orden", "pgh_context", "pgh_created_at", "pgh_label") VALUES (NEW."circuito_id", NEW."id", NEW."itinerario_id", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\'); RETURN NULL;',
                    hash="4f8d254e77ba3696a058fc5eefbfe98607be356e",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_de817",
                    table="itinerario_circuito",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarycircuitevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_itinerarycircuitevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarycircuitevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_itinerarycircuitevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarycircuitevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_itinerarycircuitevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarycircuitevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_itinerarycircuitevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarycircuitevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_itinerarycircuitevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarycircuitevent",
            index=models.Index(fields=["id"], name="idx_itinerarycircuitevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarycircuitevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="ff252a68ecb326534ae441df479ec863f4dbe011",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_4dcfd",
                    table="itinerario_circuito_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="itineraryevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_itineraryevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="itineraryevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_itineraryevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="itineraryevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_itineraryevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="itineraryevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_itineraryevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="itineraryevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_itineraryevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="itineraryevent",
            index=models.Index(fields=["id"], name="idx_itineraryevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itineraryevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="79a46a7c78efcb1e3e123b3df2efdf6e088eb113",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_3c136",
                    table="itinerario_cambio",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="itinerary",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["user", "-created_at"],
                name="idx_itinerario_turista",
            ),
        ),
        migrations.AddIndex(
            model_name="itinerary",
            index=models.Index(
                fields=["followed_circuit", "adjusted"], name="idx_itinerario_metricas"
            ),
        ),
        migrations.AddConstraint(
            model_name="itinerary",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("adjusted", True),
                    ("followed_circuit__isnull", False),
                    _connector="OR",
                ),
                name="chk_itinerario_seguido_coherente",
            ),
        ),
        migrations.AddConstraint(
            model_name="itinerary",
            constraint=models.CheckConstraint(
                condition=django.db.models.lookups.GreaterThanOrEqual(
                    django.db.models.functions.text.Length("title"), 3
                ),
                name="chk_itinerario_titulo_longitud",
            ),
        ),
        migrations.AddConstraint(
            model_name="itinerary",
            constraint=models.CheckConstraint(
                condition=models.Q(("travel_mode__in", ["walking", "vehicle"])),
                name="chk_itinerario_modo",
            ),
        ),
        migrations.AddConstraint(
            model_name="itinerary",
            constraint=models.CheckConstraint(
                condition=models.Q(("pace__in", ["relaxed", "balanced", "intense"])),
                name="chk_itinerario_ritmo",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerary",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="fd881da9d327fc01e7800ef52aba4c73bda1cfb3",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_c1de0",
                    table="itinerario",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerary",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="32cb2016147ad95434bd09e34417a70b867e16e9",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_5ddec",
                    table="itinerario",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerary",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_itinerario_readonly_creadoen",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."creado_en" IS DISTINCT FROM (NEW."creado_en"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="c49e42a8dc3a6b44ff45fb0a22ba285c9db976e0",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_itinerario_readonly_creadoen_03f66",
                    table="itinerario",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerary",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_itinerario_ajustado_irreversible",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (NOT NEW."ajustado" AND OLD."ajustado")',
                    func="RAISE EXCEPTION 'Un itinerario ajustado no vuelve a seguir el circuito.';",
                    hash="c38841bc6a914869feebf2ffd50fd1cc6a6aaaa2",
                    operation='UPDATE OF "ajustado"',
                    pgid="pgtrigger_trg_itinerario_ajustado_irreversible_cc001",
                    table="itinerario",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerary",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "itinerario_cambio" ("ajustado", "circuito_seguido_id", "completado_en", "creado_en", "eliminado_en", "estado_id", "hora_salida", "id", "iniciado_en", "llegadas_fijas", "modo_traslado", "pgh_context", "pgh_created_at", "pgh_label", "ritmo", "titulo", "usuario_id") VALUES (OLD."ajustado", OLD."circuito_seguido_id", OLD."completado_en", OLD."creado_en", OLD."eliminado_en", OLD."estado_id", OLD."hora_salida", OLD."id", OLD."iniciado_en", OLD."llegadas_fijas", OLD."modo_traslado", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."ritmo", OLD."titulo", OLD."usuario_id"); RETURN NULL;',
                    hash="e77eff1e5df87d0d1dfb589071a7bb5f21a6f89e",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_59846",
                    table="itinerario",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerary",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "itinerario_cambio" ("ajustado", "circuito_seguido_id", "completado_en", "creado_en", "eliminado_en", "estado_id", "hora_salida", "id", "iniciado_en", "llegadas_fijas", "modo_traslado", "pgh_context", "pgh_created_at", "pgh_label", "ritmo", "titulo", "usuario_id") VALUES (NEW."ajustado", NEW."circuito_seguido_id", NEW."completado_en", NEW."creado_en", NEW."eliminado_en", NEW."estado_id", NEW."hora_salida", NEW."id", NEW."iniciado_en", NEW."llegadas_fijas", NEW."modo_traslado", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."ritmo", NEW."titulo", NEW."usuario_id"); RETURN NULL;',
                    hash="567270df8dfbfb6965e0b41f5338576ae7eb7126",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_8bcc5",
                    table="itinerario",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerary",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "itinerario_cambio" ("ajustado", "circuito_seguido_id", "completado_en", "creado_en", "eliminado_en", "estado_id", "hora_salida", "id", "iniciado_en", "llegadas_fijas", "modo_traslado", "pgh_context", "pgh_created_at", "pgh_label", "ritmo", "titulo", "usuario_id") VALUES (NEW."ajustado", NEW."circuito_seguido_id", NEW."completado_en", NEW."creado_en", NEW."eliminado_en", NEW."estado_id", NEW."hora_salida", NEW."id", NEW."iniciado_en", NEW."llegadas_fijas", NEW."modo_traslado", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."ritmo", NEW."titulo", NEW."usuario_id"); RETURN NULL;',
                    hash="8e27796445518d487ddf5a14d5e7447df4138f9a",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_f85e7",
                    table="itinerario",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="itinerarystop",
            constraint=models.UniqueConstraint(
                fields=("itinerary", "order"), name="unq_itinerarioparada_orden"
            ),
        ),
        migrations.AddConstraint(
            model_name="itinerarystop",
            constraint=models.CheckConstraint(
                condition=models.Q(("order__gte", 0)),
                name="chk_itinerarioparada_orden_positivo",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarystop",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_protect_truncate",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'No se permite truncar tablas.';",
                    hash="c7e3e3c75219f7c618d03d1e91df8a7bf85e4055",
                    level="STATEMENT",
                    operation="TRUNCATE",
                    pgid="pgtrigger_trg_protect_truncate_96223",
                    table="itinerario_parada",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarystop",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_readonly_primarykey",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id"))',
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update rows from % table', TG_TABLE_NAME;",
                    hash="c4fc1d92950041fadde820e4cd473db625d527ca",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_readonly_primarykey_002b4",
                    table="itinerario_parada",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarystop",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_itinerario_sin_paradas_propias",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="IF NOT EXISTS (SELECT 1 FROM itinerario WHERE id = NEW.itinerario_id AND ajustado) THEN RAISE EXCEPTION 'Un itinerario que sigue un circuito no tiene paradas propias.'; END IF; RETURN NEW;",
                    hash="e7a4d20969f38d8d9f8b939d8f968c98304c68b2",
                    operation="INSERT",
                    pgid="pgtrigger_trg_itinerario_sin_paradas_propias_7929c",
                    table="itinerario_parada",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarystop",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "itinerario_parada_cambio" ("id", "itinerario_id", "latitud", "longitud", "nombre", "orden", "pgh_context", "pgh_created_at", "pgh_label", "punto_interes_id", "visitada_en") VALUES (OLD."id", OLD."itinerario_id", OLD."latitud", OLD."longitud", OLD."nombre", OLD."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'delete\', OLD."punto_interes_id", OLD."visitada_en"); RETURN NULL;',
                    hash="1eb376cb02a1fe496f0b310e46a2293f1bca62ec",
                    operation="DELETE",
                    pgid="pgtrigger_trg_log_delete_27af9",
                    table="itinerario_parada",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarystop",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "itinerario_parada_cambio" ("id", "itinerario_id", "latitud", "longitud", "nombre", "orden", "pgh_context", "pgh_created_at", "pgh_label", "punto_interes_id", "visitada_en") VALUES (NEW."id", NEW."itinerario_id", NEW."latitud", NEW."longitud", NEW."nombre", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'insert\', NEW."punto_interes_id", NEW."visitada_en"); RETURN NULL;',
                    hash="ccc557dcf7734c9316ddce1c01e3db027a7a9cdc",
                    operation="INSERT",
                    pgid="pgtrigger_trg_log_insert_ecd5e",
                    table="itinerario_parada",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarystop",
            trigger=pgtrigger.compiler.Trigger(
                name="trg_log_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "itinerario_parada_cambio" ("id", "itinerario_id", "latitud", "longitud", "nombre", "orden", "pgh_context", "pgh_created_at", "pgh_label", "punto_interes_id", "visitada_en") VALUES (NEW."id", NEW."itinerario_id", NEW."latitud", NEW."longitud", NEW."nombre", NEW."orden", COALESCE(NULLIF(CURRENT_SETTING(\'pghistory.context_metadata\', TRUE), \'\'), NULL)::JSONB, NOW(), \'update\', NEW."punto_interes_id", NEW."visitada_en"); RETURN NULL;',
                    hash="df5c45626be541fbfcdcfab57138a5cb94b567d9",
                    operation="UPDATE",
                    pgid="pgtrigger_trg_log_update_f0c85",
                    table="itinerario_parada",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarystopevent",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("pgh_context__isnull", False)),
                fields=["pgh_context"],
                name="gin_itinerarystopevent_ctx_path",
                opclasses=["jsonb_path_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarystopevent",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    expression=django.db.models.fields.json.KeyTextTransform(
                        "url", "pgh_context"
                    ),
                    name="gin_trgm_ops",
                ),
                condition=models.Q(("pgh_context__isnull", False)),
                name="gin_itinerarystopevent_ctx_url",
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarystopevent",
            index=models.Index(
                django.db.models.fields.json.KeyTransform(
                    "id",
                    django.db.models.fields.json.KeyTransform("user", "pgh_context"),
                ),
                condition=models.Q(
                    ("pgh_context__has_key", "user"), ("pgh_context__isnull", False)
                ),
                name="idx_itinerarystopevent_ctx_userid",
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarystopevent",
            index=models.Index(
                fields=["pgh_created_at"], name="idx_itinerarystopevent_pghcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarystopevent",
            index=models.Index(
                fields=["pgh_label"], name="idx_itinerarystopevent_pghlabel"
            ),
        ),
        migrations.AddIndex(
            model_name="itinerarystopevent",
            index=models.Index(fields=["id"], name="idx_itinerarystopevent_id"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="itinerarystopevent",
            trigger=pgtrigger.compiler.Trigger(
                name="append_only",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;",
                    hash="c29133c0d0fee556fb8ce8897a357561d9922fbf",
                    operation="UPDATE OR DELETE",
                    pgid="pgtrigger_append_only_3bfe0",
                    table="itinerario_parada_cambio",
                    when="BEFORE",
                ),
            ),
        ),
    ]
